SFC_TIMER_DM_HMS_T_TO_HMS = T_TO_HMS_FUNCTION( 0 , SFC_TIMER_DM_T_A_TO_T );
SFC_TIMER_DM_M_A_NAME = A_NAME_FUNCTION( SFC_TIMER_DM_HMS_MIN );
SFC_TIMER_DM_S_A_NAME = A_NAME_FUNCTION( SFC_TIMER_DM_HMS_SEC );
SFC_TIMER_DM_T_A_TO_T = A_TO_T_FUNCTION( SHUTDOWN_DMTIMER_A_OUT_1 );
SFC_TIMER_NM1CLDNHMS_T_TO_HMS = T_TO_HMS_FUNCTION( 0 , SFC_TIMER_SYNCCL_T_A_TO_T );
SFC_TIMER_NM1CLDN_M_A_NAME = A_NAME_FUNCTION( SFC_TIMER_NM1CLDNHMS_MIN );
SFC_TIMER_NM1CLDN_S_A_NAME = A_NAME_FUNCTION( SFC_TIMER_NM1CLDNHMS_SEC );
SFC_TIMER_SYNCCL_T_A_TO_T = A_TO_T_FUNCTION( VENT_FANTIMERS_OUT_9 );
