IFACE_HDWR_MW_A_NAME = IFACE_HDWR_MWSEL_A_SW;
IFACE_HDWR_MWFAILSW_B_SW = B_SW_FUNCTION( IFACE_HDWR_Z_BREAKER_DELAY , FALSE , A1_A06_AIO_WX_LATCH_OR );
IFACE_HDWR_MWSEL_A_SW = A_SW_FUNCTION( IFACE_HDWR_Z_BREAKER_DELAY , 0.0 , A1_A06_AIO_WX_AI_COMBO );
IFACE_HDWR_MWVST_B_NAME = IFACE_HDWR_MWFAILSW_B_SW;
DELAY_FUNCTION(1 , 0 , 0 , IFACE_CORE_Z_BREAKER_B_NAME,&IFACE_HDWR_Z_BREAKER_DELAY,&IFACE_HDWR_Z_BREAKER_R_TIME);
