B_BODWFQP_B_WFQPERR_A_NAME = B_BODWFQP_WFQPERRTMP_CALCULATE;
B_BODWFQP_B_WFQPS32_DIVIDE = B_BODINPUT_B_PS32_A_NAME / F_INPUT_F_WF36DMD_A_NAME;
B_BODWFQP_WFQPERRTMP_CALCULATE =  ( (B_BODWFQP_WFQPS32STM_DIVIDE -B_BODWFQP_B_WFQPS32_DIVIDE ) /B_BODWFQP_WFQPS32STM_DIVIDE ) *    100;
B_BODWFQP_WFQPS32SEL_A_NAME = B_BODWFQP_WFQPS32STM_DIVIDE;
B_BODWFQP_WFQPS32STM_DIVIDE = F_INPUT_F_WF36DMD_A_NAME / I_PS3_PS32SEL_A_NAME;
