T_TO_HMS_FUNCTION(1 , SFC_TIMER_DM_T_A_TO_T,&SFC_TIMER_DM_HMS_DAY,&SFC_TIMER_DM_HMS_HOUR,&SFC_TIMER_DM_HMS_MICROSEC,&SFC_TIMER_DM_HMS_MIN,&SFC_TIMER_DM_HMS_MONTH,&SFC_TIMER_DM_HMS_SEC,&SFC_TIMER_DM_HMS_YEAR);
SFC_TIMER_DM_M_A_NAME = SFC_TIMER_DM_HMS_MIN;
SFC_TIMER_DM_S_A_NAME = SFC_TIMER_DM_HMS_SEC;
SFC_TIMER_DM_T_A_TO_T = A_TO_T_FUNCTION( SHUTDOWN_DMTIMER_A_OUT_1 );
T_TO_HMS_FUNCTION(1 , SFC_TIMER_SYNCCL_T_A_TO_T,&SFC_TIMER_NM1CLDNHMS_DAY,&SFC_TIMER_NM1CLDNHMS_HOUR,&SFC_TIMER_NM1CLDNHMS_MICROSEC,&SFC_TIMER_NM1CLDNHMS_MIN,&SFC_TIMER_NM1CLDNHMS_MONTH,&SFC_TIMER_NM1CLDNHMS_SEC,&SFC_TIMER_NM1CLDNHMS_YEAR);
SFC_TIMER_NM1CLDN_M_A_NAME = SFC_TIMER_NM1CLDNHMS_MIN;
SFC_TIMER_NM1CLDN_S_A_NAME = SFC_TIMER_NM1CLDNHMS_SEC;
SFC_TIMER_SYNCCL_T_A_TO_T = A_TO_T_FUNCTION( VENT_FANTIMERS_OUT_9 );
