V_VDPS3F_INVROOTRT_A_NAME = V_VDPS3F_INVROOTTMP_DIVIDE;
V_VDPS3F_INVROOTTMP_DIVIDE = 1 / V_VDPS3F_RGSTFSRTMP_SQRT;
V_VDPS3F_RGASTF_A_NAME = V_VDPS3F_RGASTFTMP_CALCULATE;
V_VDPS3F_RGASTFSQRT_A_NAME = V_VDPS3F_RGSTFSRTMP_SQRT;
V_VDPS3F_RGASTFTMP_CALCULATE =  (I_TGS_TGSSEL_A_NAME + 459.67 ) *C_RGAS_RGAS_A_NAME;
V_VDPS3F_RGSTFSRTMP_SQRT = SQRT_FUNCTION( 1 , V_VDPS3F_RGASTFTMP_CALCULATE );
