VSV_CAL_AVERAGE_CALCULATE =  (20.0 )  -  (  (VSV_CAL_AVG1_A_OUT_7 +VSV_CAL_AVG2_A_OUT_7 +VSV_CAL_AVG3_A_OUT_7 +VSV_CAL_AVG4_A_OUT_7 +VSV_CAL_AVG5_A_OUT_7 )  / 5 ) ;
if (VSV_CAL_MIN_AND== TRUE){   VSV_CAL_AVG1_A_OUT_6 = VSV_CAL_AVG1_A_OUT_5;   VSV_CAL_AVG1_A_OUT_5 = VSV_CAL_AVG1_A_OUT_4;   VSV_CAL_AVG1_A_OUT_4 = VSV_CAL_AVG1_A_OUT_3;   VSV_CAL_AVG1_A_OUT_3 = VSV_CAL_AVG1_A_OUT_2;   VSV_CAL_AVG1_A_OUT_2 = VSV_CAL_AVG1_A_OUT_1;   VSV_CAL_AVG1_A_OUT_1 = VSV_CAL_CURRENT_A_NAME;   VSV_CAL_AVG1_A_OUT_7 = (VSV_CAL_AVG1_A_OUT_1+VSV_CAL_AVG1_A_OUT_2+VSV_CAL_AVG1_A_OUT_3+   VSV_CAL_AVG1_A_OUT_4+VSV_CAL_AVG1_A_OUT_5+VSV_CAL_AVG1_A_OUT_6)/6;}   else {   VSV_CAL_AVG1_A_OUT_6 = VSV_CAL_AVG1_A_OUT_6;   VSV_CAL_AVG1_A_OUT_5 = VSV_CAL_AVG1_A_OUT_5;   VSV_CAL_AVG1_A_OUT_4 = VSV_CAL_AVG1_A_OUT_4;   VSV_CAL_AVG1_A_OUT_3 = VSV_CAL_AVG1_A_OUT_3;   VSV_CAL_AVG1_A_OUT_2 = VSV_CAL_AVG1_A_OUT_2;   VSV_CAL_AVG1_A_OUT_1 = VSV_CAL_AVG1_A_OUT_1;   VSV_CAL_AVG1_A_OUT_7 = VSV_CAL_AVG1_A_OUT_7;};
if (VSV_CAL_LO_MID_AND== TRUE){   VSV_CAL_AVG2_A_OUT_6 = VSV_CAL_AVG2_A_OUT_5;   VSV_CAL_AVG2_A_OUT_5 = VSV_CAL_AVG2_A_OUT_4;   VSV_CAL_AVG2_A_OUT_4 = VSV_CAL_AVG2_A_OUT_3;   VSV_CAL_AVG2_A_OUT_3 = VSV_CAL_AVG2_A_OUT_2;   VSV_CAL_AVG2_A_OUT_2 = VSV_CAL_AVG2_A_OUT_1;   VSV_CAL_AVG2_A_OUT_1 = VSV_CAL_CURRENT_A_NAME;   VSV_CAL_AVG2_A_OUT_7 = (VSV_CAL_AVG2_A_OUT_1+VSV_CAL_AVG2_A_OUT_2+VSV_CAL_AVG2_A_OUT_3+   VSV_CAL_AVG2_A_OUT_4+VSV_CAL_AVG2_A_OUT_5+VSV_CAL_AVG2_A_OUT_6)/6;}   else {   VSV_CAL_AVG2_A_OUT_6 = VSV_CAL_AVG2_A_OUT_6;   VSV_CAL_AVG2_A_OUT_5 = VSV_CAL_AVG2_A_OUT_5;   VSV_CAL_AVG2_A_OUT_4 = VSV_CAL_AVG2_A_OUT_4;   VSV_CAL_AVG2_A_OUT_3 = VSV_CAL_AVG2_A_OUT_3;   VSV_CAL_AVG2_A_OUT_2 = VSV_CAL_AVG2_A_OUT_2;   VSV_CAL_AVG2_A_OUT_1 = VSV_CAL_AVG2_A_OUT_1;   VSV_CAL_AVG2_A_OUT_7 = VSV_CAL_AVG2_A_OUT_7;};
if (VSV_CAL_MID_AND== TRUE){   VSV_CAL_AVG3_A_OUT_6 = VSV_CAL_AVG3_A_OUT_5;   VSV_CAL_AVG3_A_OUT_5 = VSV_CAL_AVG3_A_OUT_4;   VSV_CAL_AVG3_A_OUT_4 = VSV_CAL_AVG3_A_OUT_3;   VSV_CAL_AVG3_A_OUT_3 = VSV_CAL_AVG3_A_OUT_2;   VSV_CAL_AVG3_A_OUT_2 = VSV_CAL_AVG3_A_OUT_1;   VSV_CAL_AVG3_A_OUT_1 = VSV_CAL_CURRENT_A_NAME;   VSV_CAL_AVG3_A_OUT_7 = (VSV_CAL_AVG3_A_OUT_1+VSV_CAL_AVG3_A_OUT_2+VSV_CAL_AVG3_A_OUT_3+   VSV_CAL_AVG3_A_OUT_4+VSV_CAL_AVG3_A_OUT_5+VSV_CAL_AVG3_A_OUT_6)/6;}   else {   VSV_CAL_AVG3_A_OUT_6 = VSV_CAL_AVG3_A_OUT_6;   VSV_CAL_AVG3_A_OUT_5 = VSV_CAL_AVG3_A_OUT_5;   VSV_CAL_AVG3_A_OUT_4 = VSV_CAL_AVG3_A_OUT_4;   VSV_CAL_AVG3_A_OUT_3 = VSV_CAL_AVG3_A_OUT_3;   VSV_CAL_AVG3_A_OUT_2 = VSV_CAL_AVG3_A_OUT_2;   VSV_CAL_AVG3_A_OUT_1 = VSV_CAL_AVG3_A_OUT_1;   VSV_CAL_AVG3_A_OUT_7 = VSV_CAL_AVG3_A_OUT_7;};
if (VSV_CAL_HI_MID_AND== TRUE){   VSV_CAL_AVG4_A_OUT_6 = VSV_CAL_AVG4_A_OUT_5;   VSV_CAL_AVG4_A_OUT_5 = VSV_CAL_AVG4_A_OUT_4;   VSV_CAL_AVG4_A_OUT_4 = VSV_CAL_AVG4_A_OUT_3;   VSV_CAL_AVG4_A_OUT_3 = VSV_CAL_AVG4_A_OUT_2;   VSV_CAL_AVG4_A_OUT_2 = VSV_CAL_AVG4_A_OUT_1;   VSV_CAL_AVG4_A_OUT_1 = VSV_CAL_CURRENT_A_NAME;   VSV_CAL_AVG4_A_OUT_7 = (VSV_CAL_AVG4_A_OUT_1+VSV_CAL_AVG4_A_OUT_2+VSV_CAL_AVG4_A_OUT_3+   VSV_CAL_AVG4_A_OUT_4+VSV_CAL_AVG4_A_OUT_5+VSV_CAL_AVG4_A_OUT_6)/6;}   else {   VSV_CAL_AVG4_A_OUT_6 = VSV_CAL_AVG4_A_OUT_6;   VSV_CAL_AVG4_A_OUT_5 = VSV_CAL_AVG4_A_OUT_5;   VSV_CAL_AVG4_A_OUT_4 = VSV_CAL_AVG4_A_OUT_4;   VSV_CAL_AVG4_A_OUT_3 = VSV_CAL_AVG4_A_OUT_3;   VSV_CAL_AVG4_A_OUT_2 = VSV_CAL_AVG4_A_OUT_2;   VSV_CAL_AVG4_A_OUT_1 = VSV_CAL_AVG4_A_OUT_1;   VSV_CAL_AVG4_A_OUT_7 = VSV_CAL_AVG4_A_OUT_7;};
if (VSV_CAL_MAX_AND== TRUE){   VSV_CAL_AVG5_A_OUT_6 = VSV_CAL_AVG5_A_OUT_5;   VSV_CAL_AVG5_A_OUT_5 = VSV_CAL_AVG5_A_OUT_4;   VSV_CAL_AVG5_A_OUT_4 = VSV_CAL_AVG5_A_OUT_3;   VSV_CAL_AVG5_A_OUT_3 = VSV_CAL_AVG5_A_OUT_2;   VSV_CAL_AVG5_A_OUT_2 = VSV_CAL_AVG5_A_OUT_1;   VSV_CAL_AVG5_A_OUT_1 = VSV_CAL_CURRENT_A_NAME;   VSV_CAL_AVG5_A_OUT_7 = (VSV_CAL_AVG5_A_OUT_1+VSV_CAL_AVG5_A_OUT_2+VSV_CAL_AVG5_A_OUT_3+   VSV_CAL_AVG5_A_OUT_4+VSV_CAL_AVG5_A_OUT_5+VSV_CAL_AVG5_A_OUT_6)/6;}   else {   VSV_CAL_AVG5_A_OUT_6 = VSV_CAL_AVG5_A_OUT_6;   VSV_CAL_AVG5_A_OUT_5 = VSV_CAL_AVG5_A_OUT_5;   VSV_CAL_AVG5_A_OUT_4 = VSV_CAL_AVG5_A_OUT_4;   VSV_CAL_AVG5_A_OUT_3 = VSV_CAL_AVG5_A_OUT_3;   VSV_CAL_AVG5_A_OUT_2 = VSV_CAL_AVG5_A_OUT_2;   VSV_CAL_AVG5_A_OUT_1 = VSV_CAL_AVG5_A_OUT_1;   VSV_CAL_AVG5_A_OUT_7 = VSV_CAL_AVG5_A_OUT_7;};
VSV_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 1 , VSV_CAL_AVERAGE_CALCULATE );
if(VSV_CAL_CAL_09_TRAN_3 || VSV_CAL_CAL_00_TRAN_2) { 
	if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_10_TRAN_1 = VSV_CAL_PUNCH_OR_OR;
	} else if( VSV_CAL_DLY_TRAN_1_DELAY) {
		VSV_CAL_CAL_10_TRAN_2 = VSV_CAL_DLY_TRAN_1_DELAY;
	} else 
		VSV_CAL_CAL_10_SFC_STEP= 1
} else {
  VSV_CAL_CAL_10_ACTIVETIME= 0; 
  VSV_CAL_CAL_10_SFC_STEP= 0; 
  VSV_CAL_CAL_10_TRAN_1= 0; 
  VSV_CAL_CAL_10_TRAN_2 = 0; 
}
if(VSV_CAL_CAL_10_TRAN_2) { 
	if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_11_TRAN_1 = VSV_CAL_PUNCH_OR_OR;
	} else if( VSV_CAL_DLY_TRAN_2_DELAY) {
		VSV_CAL_CAL_11_TRAN_2 = VSV_CAL_DLY_TRAN_2_DELAY;
	} else 
		VSV_CAL_CAL_11_SFC_STEP= 1
} else {
  VSV_CAL_CAL_11_ACTIVETIME= 0; 
  VSV_CAL_CAL_11_SFC_STEP= 0; 
  VSV_CAL_CAL_11_TRAN_1= 0; 
  VSV_CAL_CAL_11_TRAN_2 = 0; 
}
if(VSV_CAL_CAL_11_TRAN_2) { 
	if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_12_TRAN_1 = VSV_CAL_PUNCH_OR_OR;
	} else if( VSV_CAL_DLY_TRAN_3_DELAY) {
		VSV_CAL_CAL_12_TRAN_2 = VSV_CAL_DLY_TRAN_3_DELAY;
	} else 
		VSV_CAL_CAL_12_SFC_STEP= 1
} else {
  VSV_CAL_CAL_12_ACTIVETIME= 0; 
  VSV_CAL_CAL_12_SFC_STEP= 0; 
  VSV_CAL_CAL_12_TRAN_1= 0; 
  VSV_CAL_CAL_12_TRAN_2 = 0; 
}
if(VSV_CAL_CAL_12_TRAN_2) { 
	if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_13_TRAN_1 = VSV_CAL_PUNCH_OR_OR;
	} else if( VSV_CAL_DLY_TRAN_4_DELAY) {
		VSV_CAL_CAL_13_TRAN_2 = VSV_CAL_DLY_TRAN_4_DELAY;
	} else 
		VSV_CAL_CAL_13_SFC_STEP= 1
} else {
  VSV_CAL_CAL_13_ACTIVETIME= 0; 
  VSV_CAL_CAL_13_SFC_STEP= 0; 
  VSV_CAL_CAL_13_TRAN_1= 0; 
  VSV_CAL_CAL_13_TRAN_2 = 0; 
}
if(VSV_CAL_CAL_13_TRAN_2) { 
	if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_14_TRAN_1 = VSV_CAL_PUNCH_OR_OR;
	} else if( VSV_CAL_DLY_TRAN_5_DELAY) {
		VSV_CAL_CAL_14_TRAN_2 = VSV_CAL_DLY_TRAN_5_DELAY;
	} else 
		VSV_CAL_CAL_14_SFC_STEP= 1
} else {
  VSV_CAL_CAL_14_ACTIVETIME= 0; 
  VSV_CAL_CAL_14_SFC_STEP= 0; 
  VSV_CAL_CAL_14_TRAN_1= 0; 
  VSV_CAL_CAL_14_TRAN_2 = 0; 
}
  bool VSV_CAL_CAL_14_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , VSV_CAL_CAL_15_SFC_STEP,&VSV_CAL_CAL_14_OS_ONE_SHOT,&VSV_CAL_CAL_14_OS_R_TIME,&VSV_CAL_CAL_14_OS_LAST_TRIGGER);
if(VSV_CAL_CAL_14_TRAN_2) { 
	if( VSV_CAL_CAL_14_OS_ONE_SHOT) {
		VSV_CAL_CAL_15_TRAN_1 = VSV_CAL_CAL_14_OS_ONE_SHOT;
	} else 
		VSV_CAL_CAL_15_SFC_STEP= 1
} else {
  VSV_CAL_CAL_15_ACTIVETIME= 0; 
  VSV_CAL_CAL_15_SFC_STEP= 0; 
  VSV_CAL_CAL_15_TRAN_1 = 0; 
}
if(VSV_CAL_CAL_00_TRAN_1) { 
	if( VSV_CAL_NOTSTROKE_NOT) {
		VSV_CAL_CAL_16_TRAN_1 = VSV_CAL_NOTSTROKE_NOT;
	} else if( VSV_CAL_PUNCH_OR_OR) {
		VSV_CAL_CAL_16_TRAN_2 = VSV_CAL_PUNCH_OR_OR;
	} else 
		VSV_CAL_CAL_16_SFC_STEP= 1
} else {
  VSV_CAL_CAL_16_ACTIVETIME= 0; 
  VSV_CAL_CAL_16_SFC_STEP= 0; 
  VSV_CAL_CAL_16_TRAN_1= 0; 
  VSV_CAL_CAL_16_TRAN_2 = 0; 
}
DELAY_FUNCTION(1 , 5 , 0 , VSV_CAL_DMDVSFDBK_B_OUT_1,&VSV_CAL_DLY_DFCMP_DELAY,&VSV_CAL_DLY_DFCMP_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , VSV_CAL_TRAN_1_AND,&VSV_CAL_DLY_TRAN_1_DELAY,&VSV_CAL_DLY_TRAN_1_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , VSV_CAL_TRAN_2_AND,&VSV_CAL_DLY_TRAN_2_DELAY,&VSV_CAL_DLY_TRAN_2_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , VSV_CAL_TRAN_3_AND,&VSV_CAL_DLY_TRAN_3_DELAY,&VSV_CAL_DLY_TRAN_3_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , VSV_CAL_TRAN_4_AND,&VSV_CAL_DLY_TRAN_4_DELAY,&VSV_CAL_DLY_TRAN_4_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , VSV_CAL_TRAN_5_AND,&VSV_CAL_DLY_TRAN_5_DELAY,&VSV_CAL_DLY_TRAN_5_R_TIME);
if (fabs(VSV_CAL_DEMAND_A_NAME-VSV_CAL_AVG_POS_A_NAME) < VSV_CAL_ERROR_A_NAME)   { VSV_CAL_DMDVSFDBK_B_OUT_1 = true; }   else   { VSV_CAL_DMDVSFDBK_B_OUT_1 = false; };
VSV_CAL_HI_MID_AND = VSV_CAL_CAL_13_SFC_STEP && VSV_CAL_I_CNT_ONE_DELAY && VSV_CAL_DLY_DFCMP_DELAY;
VSV_CAL_I_CNT_NOT =! VSV_CAL_I_CNT_ONE_DELAY;
VSV_CAL_I_CNTPV_ZMINUS1_B = VSV_CAL_I_CNT_NOT;
DELAY_FUNCTION(1 , 0.32 , 0 , VSV_CAL_I_CNTPV_ZMINUS1_B,&VSV_CAL_I_CNT_ONE_DELAY,&VSV_CAL_I_CNT_ONE_R_TIME);
VSV_CAL_LO_MID_AND = VSV_CAL_CAL_11_SFC_STEP && VSV_CAL_I_CNT_ONE_DELAY && VSV_CAL_DLY_DFCMP_DELAY;
VSV_CAL_MAX_AND = VSV_CAL_CAL_14_SFC_STEP && VSV_CAL_I_CNT_ONE_DELAY && VSV_CAL_DLY_DFCMP_DELAY;
VSV_CAL_MID_AND = VSV_CAL_CAL_12_SFC_STEP && VSV_CAL_I_CNT_ONE_DELAY && VSV_CAL_DLY_DFCMP_DELAY;
VSV_CAL_MIN_AND = VSV_CAL_CAL_10_SFC_STEP && VSV_CAL_I_CNT_ONE_DELAY && VSV_CAL_DLY_DFCMP_DELAY;
VSV_CAL_NOTSTROKE_NOT =! VSV_CAL_CALMODE_B_NAME;
VSV_CAL_NULJA_A_NAME = VSV_CAL_NULLBIAS_NO;
A_SW_REV_FUNCTION(VSV_CAL_CAL_14_OS_ONE_SHOT , VSV_CAL_NULLBIAS_NC , VSV_CAL_AVG_NEGATE_NEGATE,&VSV_CAL_NULLBIAS_NC,&VSV_CAL_NULLBIAS_NO);
VSV_CAL_TRAN_1_AND = VSV_CAL_DLY_DFCMP_DELAY && VSV_CAL_CAL_10_SFC_STEP;
VSV_CAL_TRAN_2_AND = VSV_CAL_DLY_DFCMP_DELAY && VSV_CAL_CAL_11_SFC_STEP;
VSV_CAL_TRAN_3_AND = VSV_CAL_DLY_DFCMP_DELAY && VSV_CAL_CAL_12_SFC_STEP;
VSV_CAL_TRAN_4_AND = VSV_CAL_DLY_DFCMP_DELAY && VSV_CAL_CAL_13_SFC_STEP;
VSV_CAL_TRAN_5_AND = VSV_CAL_DLY_DFCMP_DELAY && VSV_CAL_CAL_14_SFC_STEP;
