O_VLVCAL_CALMODE_B_NAME = O_VLVCAL_CALPERM_AND;
O_VLVCAL_CALPERM_AND = E_SEQUENCG_FUELOFF_B_NAME && IFACE_CORE_CALMODE;
O_VLVCAL_N_CALMODE_B_NAME = O_VLVCAL_N_CALTMP_NOT;
O_VLVCAL_N_CALTMP_NOT =! O_VLVCAL_CALPERM_AND;
O_VLVCAL_N_STAGING_B_NAME = O_VLVCAL_N_STAGTMP_NOT;
O_VLVCAL_N_STAGTMP_NOT =! S_BRNSTATG_STAGING_B_NAME;
