A_PX36FV_FVPX36_A_NAME = A_PX36FV_FVPXCLC_CALCULATE;
A_PX36FV_FVPXCLC_CALCULATE = px36s + (A_PX36AVG_VPX36S_A_NAME *ADJ_TIMEAHDJ_A_NAME ) +     (ADJ_TIMEAHDJ_A_NAME *ADJ_TIMEAHDJ_A_NAME *A_PX36AVG_APX36S_A_NAME * 0.5 ) ;
