S_PSMPSTDN_P0QA_A_NAME = S_PSMPSTDN_P0QATMP_DIVIDE;
S_PSMPSTDN_P0QATMP_DIVIDE = 14.7 / I_P0_P0SEL_A_NAME;
S_PSMPSTDN_PSUMPCA_A_NAME = S_PSMPSTDN_PSUMPCATMP_MULTIPLY;
S_PSMPSTDN_PSUMPCATMP_MULTIPLY = ADJ_PSUMPMINJ_A_NAME * S_PSMPSTDN_P0QATMP_DIVIDE;
A_COMPARE_FUNCTION(0 , C_PSUMP_PSUMPEST_A_NAME , S_PSMPSTDN_PSUMPCATMP_MULTIPLY,&S_PSMPSTDN_PSUMPCMP_A_COMPARE,&S_PSMPSTDN_PSUMPCMP_A_EQUAL);
S_PSMPSTDN_PSUMPSTGDN_B_NAME = S_PSMPSTDN_STGDNTMP_AND;
DELAY_FUNCTION(1 , 0 , ADJ_PSUMPPERSJ_A_NAME , S_PSMPSTDN_PSUMPCMP_A_COMPARE,&S_PSMPSTDN_STGDNDLY_DELAY,&S_PSMPSTDN_STGDNDLY_R_TIME);
S_PSMPSTDN_STGDNTMP_AND = R_NSDSCHES_GT1MW_B_NAME && S_PSMPSTDN_STGDNDLY_DELAY;
