switch(ENGMODE_SIMULATE_I_SW) { 
  case_1:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_2:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_3:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_4:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_5:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_6:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_7:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_8:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_9:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_10:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_11:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_12:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_13:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_14:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_15:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_16:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_17:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_18:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_19:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_20:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_21:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_22:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_23:
    ENGMODE_BREAKDOWN_OUT_1 = 0;
  break;
  case_24:
    ENGMODE_BREAKDOWN_OUT_1 = *TRUE;
  break;
}
B_MUX_S_N_FUNCTION(,&ENGMODE_BREAKDOWN_OUT_1,&ENGMODE_BREAKDOWN_OUT_10,&ENGMODE_BREAKDOWN_OUT_11,&ENGMODE_BREAKDOWN_OUT_12,&ENGMODE_BREAKDOWN_OUT_13,&ENGMODE_BREAKDOWN_OUT_14,&ENGMODE_BREAKDOWN_OUT_15,&ENGMODE_BREAKDOWN_OUT_16,&ENGMODE_BREAKDOWN_OUT_17,&ENGMODE_BREAKDOWN_OUT_18,&ENGMODE_BREAKDOWN_OUT_19,&ENGMODE_BREAKDOWN_OUT_2,&ENGMODE_BREAKDOWN_OUT_20,&ENGMODE_BREAKDOWN_OUT_21,&ENGMODE_BREAKDOWN_OUT_22,&ENGMODE_BREAKDOWN_OUT_23,&ENGMODE_BREAKDOWN_OUT_3,&ENGMODE_BREAKDOWN_OUT_4,&ENGMODE_BREAKDOWN_OUT_5,&ENGMODE_BREAKDOWN_OUT_6,&ENGMODE_BREAKDOWN_OUT_7,&ENGMODE_BREAKDOWN_OUT_8,&ENGMODE_BREAKDOWN_OUT_9);
ENGMODE_CLR_LAT_OR = FUEL_SYS_IGNITORS_B_NAME || SHUTDOWN_ANY_SD_B_NAME;
ENGMODE_CRANKING_OR = SFC_STEP_HISPD_OR_OR || SFC_STEP_LOSPD_OR_OR;
I_COMPARE_FUNCTION(ENGMODE_MODE_INT_SEL , 4,&ENGMODE_ENABLESEL_EQ,&ENGMODE_ENABLESEL_GT,&ENGMODE_ENABLESEL_LT);
ENGMODE_ENABL_Z_ZMINUS1_B = ENGMODE_ENABLESEL_LT;
ENGMODE_ENGMODE_A_NAME = ENGMODE_I_MODE_OUT_1;
ENGMODE_ENGMODE21_LATCH = LATCH_FUNCTION( 1 , ENGMODE_RESET21_OR_OR , SHUTDOWN_CDLO_OR_OR );
ENGMODE_E_13_OR_OR = SFC_STEP_READY2SYNC_SFC_STEP || FALSE;
ENGMODE_I_MODE_OUT_1 = I_TO_AN_FUNCTION( 1 , ENGMODE_MODE_INT_SEL );
A_MUX_HSS_FUNCTION(1 ,  , 1.0 , 10.0 , 11.0 , 12.0 , 13.0 , 14.0 , 15.0 , 16.0 , 17.0 , 18.0 , 19.0 , 2.0 , 20.0 , 21.0 , 22.0 , 23.0 , 3.0 , 4.0 , 5.0 , 6.0 , 7.0 , 8.0 , 9.0 , SFC_STEP_OUTOFOP_SFC_STEP , SFC_STEP_ACCTOSYNC_SFC_STEP , SFC_STEP_WARMUP_SFC_STEP , SFC_STEP_WATER_INJ_SFC_STEP , ENGMODE_E_13_OR_OR , SFC_STEP_FSNL_SFC_STEP , ENGMODE_ONLINENWTR_AND , ENGMODE_ONLINEWTR_AND , FALSE , SHUTDOWN_CDLO_B_NAME , SHUTDOWN_DECELMIN_B_NAME , ENGMODE_UNITCRANK_AND , SHUTDOWN_STEPIDLE_B_NAME , ENGMODE_ENGMODE21_LATCH , SHUTDOWN_SD_CORE_B_NAME , SHUTDOWN_SDN_CORE_B_NAME , ENGMODE_UNITREADY_AND , WTR_WASH_WW_ACTIVE_B_NAME , ENGMODE_CRANKING_OR , SFC_STEP_START_INIT_B_NAME , ENGMODE_PRGACTLAT_LATCH , FUEL_SYS_IGNITORS_B_NAME , SFC_STEP_RUN_RELAY_B_NAME,&ENGMODE_MODE_A_MUX_HSS,&ENGMODE_MODE_INT_SEL);
ENGMODE_ONLINENWTR_AND = SFC_STEP_UNITONLINE_SFC_STEP && TRUE;
ENGMODE_ONLINEWTR_AND = SFC_STEP_UNITONLINE_SFC_STEP && FALSE;
ENGMODE_PRGACTLAT_LATCH = LATCH_FUNCTION( 1 , ENGMODE_CLR_LAT_OR , FUEL_SYS_GASSTRT_01_SFC_STEP );
ENGMODE_RESET21_OR_OR = SFC_STEP_RST_AND_ST_AND || SPEED_SW_N25LT300_NOT;
ENGMODE_SIMULATE_I_SW = I_SW_FUNCTION( *FALSE , ENGMODE_MODE_INT_SEL , 0 );
ENGMODE_UNITCRANK_AND = SFC_STEP_OUTOFOP_SFC_STEP && START_PERM_C_READY_B_NAME;
ENGMODE_UNITREADY_AND = SFC_STEP_OUTOFOP_SFC_STEP && START_PERM_T_READY_B_NAME;
