BENTLY_RESET_OR_OR = ALARM_RESET_B_NAME;
if ( HMI_INTER_ENG_SI_B_NAME )   { HMI_INTER_N25_CRF_1X_A_OUT_1 = NEVADA_XE6876B_CALCULATE * 25.4; }   else   { HMI_INTER_N25_CRF_1X_A_OUT_1 = NEVADA_XE6876B_CALCULATE; };
if ( HMI_INTER_ENG_SI_B_NAME )   { HMI_INTER_N25_TRF_1X_A_OUT_1 = NEVADA_XE6877B_CALCULATE * 25.4; }   else   { HMI_INTER_N25_TRF_1X_A_OUT_1 = NEVADA_XE6877B_CALCULATE; };
if ( HMI_INTER_ENG_SI_B_NAME )   { HMI_INTER_NSD_CRF_1X_A_OUT_1 = NEVADA_XE6876A_CALCULATE * 25.4; }   else   { HMI_INTER_NSD_CRF_1X_A_OUT_1 = NEVADA_XE6876A_CALCULATE; };
if ( HMI_INTER_ENG_SI_B_NAME )   { HMI_INTER_NSD_TRF_1X_A_OUT_1 = NEVADA_XE6877A_CALCULATE * 25.4; }   else   { HMI_INTER_NSD_TRF_1X_A_OUT_1 = NEVADA_XE6877A_CALCULATE; };
LATCH1_FUNCTION(ALARM_ACKN_B_NAME , 1 , GENERATOR X AXIS VIBRATION (DE) ALRT , GENERATOR Y AXIS VIBRATION (NDE) ALRT , GENERATOR Y AXIS VIBRATION (NDE) VST , GENERATOR Y AXIS VIBRATION (NDE) DNGR , LP ROTOR VIBRATION 1X (CRF) ALRT , LP ROTOR VIBRATION 1X (CRF) VST , LP ROTOR VIBRATION 1X (CRF) DNGR , LP ROTOR VIBRATION 1X (TRF) ALRT , LP ROTOR VIBRATION 1X (TRF) VST , LP ROTOR VIBRATION 1X (TRF) DNGR , HP ROTOR VIBRATION 1X (CRF) ALRT , GENERATOR X AXIS VIBRATION (DE) VST , HP ROTOR VIBRATION 1X (CRF) VST , HP ROTOR VIBRATION 1X (CRF) DNGR , HP ROTOR VIBRATION 1X (TRF) ALRT , HP ROTOR VIBRATION 1X (TRF) VST , HP ROTOR VIBRATION 1X (TRF) DNGR , GENERATOR X AXIS VIBRATION (DE) DNGR , GENERATOR Y AXIS VIBRATION (DE) ALRT , GENERATOR Y AXIS VIBRATION (DE) VST , GENERATOR Y AXIS VIBRATION (DE) DNGR , GENERATOR X AXIS VIBRATION (NDE) ALRT , GENERATOR X AXIS VIBRATION (NDE) VST , GENERATOR X AXIS VIBRATION (NDE) DNGR , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , NEVADA_COMM_BR_V_5_2 , NEVADA_COMM_BR_V_5_26 , NEVADA_COMM_BR_V_5_25 , NEVADA_COMM_BR_V_5_27 , NEVADA_COMM_BR_V_3_2 , NEVADA_COMM_BR_V_3_1 , NEVADA_COMM_BR_V_3_3 , NEVADA_COMM_BR_V_3_10 , NEVADA_COMM_BR_V_3_9 , NEVADA_COMM_BR_V_3_11 , NEVADA_COMM_BR_V_3_18 , NEVADA_COMM_BR_V_5_1 , NEVADA_COMM_BR_V_3_17 , NEVADA_COMM_BR_V_3_19 , NEVADA_COMM_BR_V_3_26 , NEVADA_COMM_BR_V_3_25 , NEVADA_COMM_BR_V_3_27 , NEVADA_COMM_BR_V_5_3 , NEVADA_COMM_BR_V_5_10 , NEVADA_COMM_BR_V_5_9 , NEVADA_COMM_BR_V_5_11 , NEVADA_COMM_BR_V_5_18 , NEVADA_COMM_BR_V_5_17 , NEVADA_COMM_BR_V_5_19 , *FALSE , ALARM_RESET_B_NAME,&NEVADA_ALARMS_ALM_NO_1,&NEVADA_ALARMS_ALM_NO_10,&NEVADA_ALARMS_ALM_NO_11,&NEVADA_ALARMS_ALM_NO_12,&NEVADA_ALARMS_ALM_NO_13,&NEVADA_ALARMS_ALM_NO_14,&NEVADA_ALARMS_ALM_NO_15,&NEVADA_ALARMS_ALM_NO_16,&NEVADA_ALARMS_ALM_NO_17,&NEVADA_ALARMS_ALM_NO_18,&NEVADA_ALARMS_ALM_NO_19,&NEVADA_ALARMS_ALM_NO_2,&NEVADA_ALARMS_ALM_NO_20,&NEVADA_ALARMS_ALM_NO_21,&NEVADA_ALARMS_ALM_NO_22,&NEVADA_ALARMS_ALM_NO_23,&NEVADA_ALARMS_ALM_NO_24,&NEVADA_ALARMS_ALM_NO_3,&NEVADA_ALARMS_ALM_NO_4,&NEVADA_ALARMS_ALM_NO_5,&NEVADA_ALARMS_ALM_NO_6,&NEVADA_ALARMS_ALM_NO_7,&NEVADA_ALARMS_ALM_NO_8,&NEVADA_ALARMS_ALM_NO_9,&NEVADA_ALARMS_FIRST_ALM,&NEVADA_ALARMS_HORN,&NEVADA_ALARMS_LATCH1,&NEVADA_ALARMS_SEL_1,&NEVADA_ALARMS_SEL_10,&NEVADA_ALARMS_SEL_11,&NEVADA_ALARMS_SEL_12,&NEVADA_ALARMS_SEL_13,&NEVADA_ALARMS_SEL_14,&NEVADA_ALARMS_SEL_15,&NEVADA_ALARMS_SEL_16,&NEVADA_ALARMS_SEL_17,&NEVADA_ALARMS_SEL_18,&NEVADA_ALARMS_SEL_19,&NEVADA_ALARMS_SEL_2,&NEVADA_ALARMS_SEL_20,&NEVADA_ALARMS_SEL_21,&NEVADA_ALARMS_SEL_22,&NEVADA_ALARMS_SEL_23,&NEVADA_ALARMS_SEL_24,&NEVADA_ALARMS_SEL_3,&NEVADA_ALARMS_SEL_4,&NEVADA_ALARMS_SEL_5,&NEVADA_ALARMS_SEL_6,&NEVADA_ALARMS_SEL_7,&NEVADA_ALARMS_SEL_8,&NEVADA_ALARMS_SEL_9);
// MODBUS_M 
switch(4) { 
  case 1:
    NEVADA_HP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_16;
  break;
  case 2:
    NEVADA_HP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_17;
  break;
  case 3:
    NEVADA_HP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_18;
  break;
  case 4:
    NEVADA_HP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_19;
  break;
  case 5:
    NEVADA_HP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_20;
  break;
}
switch(4) { 
  case 1:
    NEVADA_HP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_11;
  break;
  case 2:
    NEVADA_HP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_12;
  break;
  case 3:
    NEVADA_HP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_13;
  break;
  case 4:
    NEVADA_HP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_14;
  break;
  case 5:
    NEVADA_HP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_15;
  break;
}
switch(4) { 
  case 1:
    NEVADA_LP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_6;
  break;
  case 2:
    NEVADA_LP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_7;
  break;
  case 3:
    NEVADA_LP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_8;
  break;
  case 4:
    NEVADA_LP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_9;
  break;
  case 5:
    NEVADA_LP_AFT_A_MUX_N_1 = NEVADA_COMM_AR_V_3_10;
  break;
}
switch(4) { 
  case 1:
    NEVADA_LP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_1;
  break;
  case 2:
    NEVADA_LP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_2;
  break;
  case 3:
    NEVADA_LP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_3;
  break;
  case 4:
    NEVADA_LP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_4;
  break;
  case 5:
    NEVADA_LP_FWD_A_MUX_N_1 = NEVADA_COMM_AR_V_3_5;
  break;
}
NEVADA_PX36A_CALCULATE =  (NEVADA_COMM_AR_V_8_1 / 32767 )  *undefined;
NEVADA_PX36B_CALCULATE =  (NEVADA_COMM_AR_V_8_2 / 32767 )  *undefined;
NEVADA_SLOT10CH1_CALCULATE =  (NEVADA_COMM_AR_V_9_1 / 32767 )  *undefined;
NEVADA_SLOT10CH2_CALCULATE =  (NEVADA_COMM_AR_V_9_2 / 32767 )  *undefined;
NEVADA_XE6876A_CALCULATE =  (NEVADA_LP_FWD_A_MUX_N_1 / 32767 )  *undefined;
NEVADA_XE6876A_AH_CALCULATE =  (NEVADA_COMM_AR_V_3_1 / 32767 )  *undefined;
NEVADA_XE6876A_DH_CALCULATE =  (NEVADA_COMM_AR_V_3_3 / 32767 )  *undefined;
NEVADA_XE6876B_CALCULATE =  (NEVADA_HP_FWD_A_MUX_N_1 / 32767 )  *undefined;
NEVADA_XE6876B_AH_CALCULATE =  (NEVADA_COMM_AR_V_3_8 / 32767 )  *undefined;
NEVADA_XE6876B_DH_CALCULATE =  (NEVADA_COMM_AR_V_3_9 / 32767 )  *undefined;
NEVADA_XE6877A_CALCULATE =  (NEVADA_LP_AFT_A_MUX_N_1 / 32767 )  *undefined;
NEVADA_XE6877A_AH_CALCULATE =  (NEVADA_COMM_AR_V_3_5 / 32767 )  *undefined;
NEVADA_XE6877A_DH_CALCULATE =  (NEVADA_COMM_AR_V_3_7 / 32767 )  *undefined;
NEVADA_XE6877B_CALCULATE =  (NEVADA_HP_AFT_A_MUX_N_1 / 32767 )  *undefined;
NEVADA_XE6877B_AH_CALCULATE =  (NEVADA_COMM_AR_V_3_10 / 32767 )  *undefined;
NEVADA_XE6877B_DH_CALCULATE =  (NEVADA_COMM_AR_V_3_11 / 32767 )  *undefined;
