ST8_CAL_ABORT_B_NAME = OP_INTRFC_ST8_ABORT_B_NAME;
ST8_CAL_AB_AUT_OR = ST8_CAL_CAL_AUT_NOT || ST8_CAL_PUNCH_OR_OR;
ST8_CAL_AT_0_B_NAME = ST8_CAL_AT_0_SW_B_SW;
ST8_CAL_AT_0_IN_B_NAME = OP_INTRFC_ST8_AT_0_B_NAME;
  bool ST8_CAL_AT_0_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , ST8_CAL_AT_0_IN_B_NAME,&ST8_CAL_AT_0_OS_ONE_SHOT,&ST8_CAL_AT_0_OS_R_TIME,&ST8_CAL_AT_0_OS_LAST_TRIGGER);
ST8_CAL_AT_0_SW_B_SW = B_SW_FUNCTION( ST8_CAL_AUTMAN_FF_T_FLIPFLOP , ST8_CAL_CAL_04_SFC_STEP , ST8_CAL_AT_0_OS_ONE_SHOT );
ST8_CAL_AT_100_B_NAME = ST8_CAL_AT_100_SW_B_SW;
ST8_CAL_AT_100_IN_B_NAME = OP_INTRFC_ST8_AT_100_B_NAME;
  bool ST8_CAL_AT_100_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , ST8_CAL_AT_100_IN_B_NAME,&ST8_CAL_AT_100_OS_ONE_SHOT,&ST8_CAL_AT_100_OS_R_TIME,&ST8_CAL_AT_100_OS_LAST_TRIGGER);
ST8_CAL_AT_100_SW_B_SW = B_SW_FUNCTION( ST8_CAL_AUTMAN_FF_T_FLIPFLOP , ST8_CAL_CAL_07_SFC_STEP , ST8_CAL_AT_100_OS_ONE_SHOT );
ST8_CAL_AUTMANSEL_B_NAME = OP_INTRFC_ST8_A_M_B_NAME;
  bool ST8_CAL_AUTMAN_FF_IN_1_LAST; 
  bool ST8_CAL_AUTMAN_FF_IN_2_LAST; 
T_FLIPFLOP_FUNCTION(1 , ST8_CAL_AUTMANSEL_B_NAME , *FALSE , LOC_REM_DELAY_WAR_DELAY,&ST8_CAL_AUTMAN_FF_T_FLIPFLOP,&ST8_CAL_AUTMAN_FF_IN_1_LAST, &ST8_CAL_AUTMAN_FF_IN_2_LAST); 
 ST8_CAL_AUTO_NOT =! ST8_CAL_AUTMAN_FF_T_FLIPFLOP;
ST8_CAL_AUTO_MAN_B_NAME = ST8_CAL_AUTMAN_FF_T_FLIPFLOP;
ST8_CAL_CALENBL_B_NAME = OP_INTRFC_ST8CALENBL_B_NAME;
  bool ST8_CAL_CALENBLOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , ST8_CAL_NOT_START_NOT , ST8_CAL_WAR_OR_OR,&ST8_CAL_CALENBLOS_ONE_SHOT,&ST8_CAL_CALENBLOS_R_TIME,&ST8_CAL_CALENBLOS_LAST_TRIGGER);
if(ST8_CAL_SFC_HOLD_TRAN_1 || ST8_CAL_CAL_01_TRAN_1 || ST8_CAL_CAL_02_TRAN_1 || ST8_CAL_CAL_03_TRAN_1 || ST8_CAL_CAL_04_TRAN_1 || ST8_CAL_CAL_05_TRAN_1 || ST8_CAL_CAL_06_TRAN_1 || ST8_CAL_CAL_07_TRAN_1 || ST8_CAL_CAL_09_TRAN_1) { 
	if( ST8_CAL_STRKENOS_ONE_SHOT) {
		ST8_CAL_CAL_00_TRAN_1 = ST8_CAL_STRKENOS_ONE_SHOT;
	} else if( ST8_CAL_NULL_ONE_SHOT) {
		ST8_CAL_CAL_00_TRAN_2 = ST8_CAL_NULL_ONE_SHOT;
	} else if( ST8_CAL_CALENBLOS_ONE_SHOT) {
		ST8_CAL_CAL_00_TRAN_3 = ST8_CAL_CALENBLOS_ONE_SHOT;
	} else 
		ST8_CAL_CAL_00_SFC_STEP= 1
} else {
  ST8_CAL_CAL_00_ACTIVETIME= 0; 
  ST8_CAL_CAL_00_SFC_STEP= 0; 
  ST8_CAL_CAL_00_TRAN_1= 0; 
  ST8_CAL_CAL_00_TRAN_2= 0; 
  ST8_CAL_CAL_00_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_00_TRAN_3) { 
	if( ST8_CAL_NOT_START_NOT) {
		ST8_CAL_CAL_01_TRAN_1 = ST8_CAL_NOT_START_NOT;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_01_TRAN_2 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_EQ_1_EQ) {
		ST8_CAL_CAL_01_TRAN_3 = ST8_CAL_EQ_1_EQ;
	} else 
		ST8_CAL_CAL_01_SFC_STEP= 1
} else {
  ST8_CAL_CAL_01_ACTIVETIME= 0; 
  ST8_CAL_CAL_01_SFC_STEP= 0; 
  ST8_CAL_CAL_01_TRAN_1= 0; 
  ST8_CAL_CAL_01_TRAN_2= 0; 
  ST8_CAL_CAL_01_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_01_TRAN_3) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_02_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_02_TRAN_2 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_NULLDVR_P_LIM_1) {
		ST8_CAL_CAL_02_TRAN_3 = ST8_CAL_NULLDVR_P_LIM_1;
	} else 
		ST8_CAL_CAL_02_SFC_STEP= 1
} else {
  ST8_CAL_CAL_02_ACTIVETIME= 0; 
  ST8_CAL_CAL_02_SFC_STEP= 0; 
  ST8_CAL_CAL_02_TRAN_1= 0; 
  ST8_CAL_CAL_02_TRAN_2= 0; 
  ST8_CAL_CAL_02_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_02_TRAN_3) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_03_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_DLYFAIL_1_DELAY) {
		ST8_CAL_CAL_03_TRAN_2 = ST8_CAL_DLYFAIL_1_DELAY;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_03_TRAN_3 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_DLY_LO_DELAY) {
		ST8_CAL_CAL_03_TRAN_4 = ST8_CAL_DLY_LO_DELAY;
	} else 
		ST8_CAL_CAL_03_SFC_STEP= 1
} else {
  ST8_CAL_CAL_03_ACTIVETIME= 0; 
  ST8_CAL_CAL_03_SFC_STEP= 0; 
  ST8_CAL_CAL_03_TRAN_1= 0; 
  ST8_CAL_CAL_03_TRAN_2= 0; 
  ST8_CAL_CAL_03_TRAN_3= 0; 
  ST8_CAL_CAL_03_TRAN_4 = 0; 
}
if(ST8_CAL_CAL_03_TRAN_4) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_04_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_04_TRAN_2 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_EQ_2_EQ) {
		ST8_CAL_CAL_04_TRAN_3 = ST8_CAL_EQ_2_EQ;
	} else 
		ST8_CAL_CAL_04_SFC_STEP= 1
} else {
  ST8_CAL_CAL_04_ACTIVETIME= 0; 
  ST8_CAL_CAL_04_SFC_STEP= 0; 
  ST8_CAL_CAL_04_TRAN_1= 0; 
  ST8_CAL_CAL_04_TRAN_2= 0; 
  ST8_CAL_CAL_04_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_04_TRAN_3) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_05_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_05_TRAN_2 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_NULLDVR_P_LIM_2) {
		ST8_CAL_CAL_05_TRAN_3 = ST8_CAL_NULLDVR_P_LIM_2;
	} else 
		ST8_CAL_CAL_05_SFC_STEP= 1
} else {
  ST8_CAL_CAL_05_ACTIVETIME= 0; 
  ST8_CAL_CAL_05_SFC_STEP= 0; 
  ST8_CAL_CAL_05_TRAN_1= 0; 
  ST8_CAL_CAL_05_TRAN_2= 0; 
  ST8_CAL_CAL_05_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_05_TRAN_3) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_06_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_DLYFAIL_2_DELAY) {
		ST8_CAL_CAL_06_TRAN_2 = ST8_CAL_DLYFAIL_2_DELAY;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_06_TRAN_3 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_DLY_HI_DELAY) {
		ST8_CAL_CAL_06_TRAN_4 = ST8_CAL_DLY_HI_DELAY;
	} else 
		ST8_CAL_CAL_06_SFC_STEP= 1
} else {
  ST8_CAL_CAL_06_ACTIVETIME= 0; 
  ST8_CAL_CAL_06_SFC_STEP= 0; 
  ST8_CAL_CAL_06_TRAN_1= 0; 
  ST8_CAL_CAL_06_TRAN_2= 0; 
  ST8_CAL_CAL_06_TRAN_3= 0; 
  ST8_CAL_CAL_06_TRAN_4 = 0; 
}
if(ST8_CAL_CAL_06_TRAN_4) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_CAL_07_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_07_TRAN_2 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_EQ_3_NOSTR_AND) {
		ST8_CAL_CAL_07_TRAN_3 = ST8_CAL_EQ_3_NOSTR_AND;
	} else 
		ST8_CAL_CAL_07_SFC_STEP= 1
} else {
  ST8_CAL_CAL_07_ACTIVETIME= 0; 
  ST8_CAL_CAL_07_SFC_STEP= 0; 
  ST8_CAL_CAL_07_TRAN_1= 0; 
  ST8_CAL_CAL_07_TRAN_2= 0; 
  ST8_CAL_CAL_07_TRAN_3 = 0; 
}
if(ST8_CAL_CAL_07_TRAN_3) { 
	if( ST8_CAL_NOT_STROKE_NOT) {
		ST8_CAL_CAL_07A_TRAN_1 = ST8_CAL_NOT_STROKE_NOT;
	} else if( ST8_CAL_AB_AUT_OR) {
		ST8_CAL_CAL_07A_TRAN_2 = ST8_CAL_AB_AUT_OR;
	} else 
		ST8_CAL_CAL_07A_SFC_STEP= 1
} else {
  ST8_CAL_CAL_07A_ACTIVETIME= 0; 
  ST8_CAL_CAL_07A_SFC_STEP= 0; 
  ST8_CAL_CAL_07A_TRAN_1= 0; 
  ST8_CAL_CAL_07A_TRAN_2 = 0; 
}
if(ST8_CAL_CAL_07A_TRAN_2) { 
	if( ST8_CAL_NV_WRITE_ONE_SHOT) {
		ST8_CAL_CAL_08_TRAN_1 = ST8_CAL_NV_WRITE_ONE_SHOT;
	} else 
		ST8_CAL_CAL_08_SFC_STEP= 1
} else {
  ST8_CAL_CAL_08_ACTIVETIME= 0; 
  ST8_CAL_CAL_08_SFC_STEP= 0; 
  ST8_CAL_CAL_08_TRAN_1 = 0; 
}
if(ST8_CAL_CAL_08_TRAN_1) { 
	if( ST8_CAL_PUNCH_OR_OR) {
		ST8_CAL_CAL_09_TRAN_1 = ST8_CAL_PUNCH_OR_OR;
	} else if( ST8_CAL_MASK_MAN_AND) {
		ST8_CAL_CAL_09_TRAN_2 = ST8_CAL_MASK_MAN_AND;
	} else if( ST8_CAL_MASK_AUTO_AND) {
		ST8_CAL_CAL_09_TRAN_3 = ST8_CAL_MASK_AUTO_AND;
	} else 
		ST8_CAL_CAL_09_SFC_STEP= 1
} else {
  ST8_CAL_CAL_09_ACTIVETIME= 0; 
  ST8_CAL_CAL_09_SFC_STEP= 0; 
  ST8_CAL_CAL_09_TRAN_1= 0; 
  ST8_CAL_CAL_09_TRAN_2= 0; 
  ST8_CAL_CAL_09_TRAN_3 = 0; 
}
ST8_CAL_CAL_AUT_NOT =! ST8_CAL_AUTMAN_FF_T_FLIPFLOP;
ST8_CAL_CAL_ENBL_B_NAME = ST8_CAL_ENABLE_Z_ZMINUS1_B;
if(ST8_CAL_CAL_03_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		ST8_CAL_CAL_FAIL_1_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		ST8_CAL_CAL_FAIL_1_SFC_STEP= 1
} else {
  ST8_CAL_CAL_FAIL_1_ACTIVETIME= 0; 
  ST8_CAL_CAL_FAIL_1_SFC_STEP= 0; 
  ST8_CAL_CAL_FAIL_1_TRAN_1 = 0; 
}
if(ST8_CAL_CAL_06_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		ST8_CAL_CAL_FAIL_2_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		ST8_CAL_CAL_FAIL_2_SFC_STEP= 1
} else {
  ST8_CAL_CAL_FAIL_2_ACTIVETIME= 0; 
  ST8_CAL_CAL_FAIL_2_SFC_STEP= 0; 
  ST8_CAL_CAL_FAIL_2_TRAN_1 = 0; 
}
ST8_CAL_ENABLE_OR_OR = ST8_CAL_CAL_01_SFC_STEP || ST8_CAL_CAL_02_SFC_STEP || ST8_CAL_CAL_03_SFC_STEP || ST8_CAL_CAL_04_SFC_STEP || ST8_CAL_CAL_05_SFC_STEP || ST8_CAL_CAL_06_SFC_STEP || ST8_CAL_CAL_07_SFC_STEP || ST8_CAL_CAL_07A_SFC_STEP;
ST8_CAL_ENABLE_Z_ZMINUS1_B = ST8_CAL_ENABLE_OR_OR;
ST8_CAL_MASK_AUTO_AND = ST8_CAL_EQ_0_EQ && ST8_CAL_AUTO_NOT;
ST8_CAL_MASK_MAN_AND = ST8_CAL_EQ_0_EQ && ST8_CAL_AUTMAN_FF_T_FLIPFLOP;
ST8_CAL_NOT_START_NOT =! ST8_CAL_CALMODE_B_NAME;
ST8_CAL_NOT_STROKE_NOT =! ST8_CAL_CALMODE_B_NAME;
  bool ST8_CAL_NULL_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , ST8_CAL_NUL_SEL_B_NAME,&ST8_CAL_NULL_ONE_SHOT,&ST8_CAL_NULL_R_TIME,&ST8_CAL_NULL_LAST_TRIGGER);
ST8_CAL_NUL_SEL_B_NAME = OP_INTRFC_ST8_NULL_B_NAME;
  bool ST8_CAL_NV_WRITE_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , ST8_CAL_CAL_08_SFC_STEP,&ST8_CAL_NV_WRITE_ONE_SHOT,&ST8_CAL_NV_WRITE_R_TIME,&ST8_CAL_NV_WRITE_LAST_TRIGGER);
  bool ST8_CAL_PUCNHOUTOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , ST8_CAL_ABORT_B_NAME,&ST8_CAL_PUCNHOUTOS_ONE_SHOT,&ST8_CAL_PUCNHOUTOS_R_TIME,&ST8_CAL_PUCNHOUTOS_LAST_TRIGGER);
ST8_CAL_PUNCH_OR_OR = ST8_CAL_PUCNHOUTOS_ONE_SHOT || ST8_CAL_NOT_START_NOT;
if(ST8_CAL_CAL_01_TRAN_2 || ST8_CAL_CAL_11_TRAN_1 || ST8_CAL_CAL_12_TRAN_1 || ST8_CAL_CAL_13_TRAN_1 || ST8_CAL_CAL_14_TRAN_1 || ST8_CAL_CAL_15_TRAN_1 || ST8_CAL_CAL_16_TRAN_1 || ST8_CAL_CAL_16_TRAN_2 || ST8_CAL_CAL_FAIL_1_TRAN_1 || ST8_CAL_CAL_FAIL_2_TRAN_1 || ST8_CAL_CAL_07A_TRAN_1 || ST8_CAL_CAL_02_TRAN_2 || ST8_CAL_CAL_03_TRAN_3 || ST8_CAL_CAL_04_TRAN_2 || ST8_CAL_CAL_05_TRAN_2 || ST8_CAL_CAL_06_TRAN_3 || ST8_CAL_CAL_07_TRAN_2 || ST8_CAL_CAL_09_TRAN_2 || ST8_CAL_CAL_10_TRAN_1) { 
	if( ST8_CAL_EQ_0_EQ) {
		ST8_CAL_SFC_HOLD_TRAN_1 = ST8_CAL_EQ_0_EQ;
	} else 
		ST8_CAL_SFC_HOLD_SFC_STEP= 1
} else {
  ST8_CAL_SFC_HOLD_ACTIVETIME= 0; 
  ST8_CAL_SFC_HOLD_SFC_STEP= 0; 
  ST8_CAL_SFC_HOLD_TRAN_1 = 0; 
}
  bool ST8_CAL_STRKENOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , ST8_CAL_NOT_START_NOT , ST8_CAL_STROKE_B_NAME,&ST8_CAL_STRKENOS_ONE_SHOT,&ST8_CAL_STRKENOS_R_TIME,&ST8_CAL_STRKENOS_LAST_TRIGGER);
ST8_CAL_STROKE_B_NAME = OP_INTRFC_ST8_STROKE_B_NAME;
ST8_CAL_WAR_OR_OR = LOC_REM_DELAY_WAR_DELAY || ST8_CAL_CALENBL_B_NAME;
