IGV_CAL_ABORT_B_NAME = OP_INTRFC_IGV_ABORT_B_NAME;
IGV_CAL_AB_AUT_OR = IGV_CAL_CAL_AUT_NOT || IGV_CAL_PUNCH_OR_OR;
IGV_CAL_AT_0_B_NAME = IGV_CAL_AT_0_SW_B_SW;
IGV_CAL_AT_0_IN_B_NAME = OP_INTRFC_IGV_AT_0_B_NAME;
  bool IGV_CAL_AT_0_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , IGV_CAL_AT_0_IN_B_NAME,&IGV_CAL_AT_0_OS_ONE_SHOT,&IGV_CAL_AT_0_OS_R_TIME,&IGV_CAL_AT_0_OS_LAST_TRIGGER);
IGV_CAL_AT_0_SW_B_SW = B_SW_FUNCTION( IGV_CAL_AUTMAN_FF_T_FLIPFLOP , IGV_CAL_CAL_04_SFC_STEP , IGV_CAL_AT_0_OS_ONE_SHOT );
IGV_CAL_AT_100_B_NAME = IGV_CAL_AT_100_SW_B_SW;
IGV_CAL_AT_100_IN_B_NAME = OP_INTRFC_IGV_AT_100_B_NAME;
  bool IGV_CAL_AT_100_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , IGV_CAL_AT_100_IN_B_NAME,&IGV_CAL_AT_100_OS_ONE_SHOT,&IGV_CAL_AT_100_OS_R_TIME,&IGV_CAL_AT_100_OS_LAST_TRIGGER);
IGV_CAL_AT_100_SW_B_SW = B_SW_FUNCTION( IGV_CAL_AUTMAN_FF_T_FLIPFLOP , IGV_CAL_CAL_07_SFC_STEP , IGV_CAL_AT_100_OS_ONE_SHOT );
IGV_CAL_AUTMANSEL_B_NAME = OP_INTRFC_IGV_A_M_B_NAME;
  bool IGV_CAL_AUTMAN_FF_IN_1_LAST; 
  bool IGV_CAL_AUTMAN_FF_IN_2_LAST; 
T_FLIPFLOP_FUNCTION(1 , IGV_CAL_AUTMANSEL_B_NAME , *FALSE , LOC_REM_DELAY_WAR_DELAY,&IGV_CAL_AUTMAN_FF_T_FLIPFLOP,&IGV_CAL_AUTMAN_FF_IN_1_LAST, &IGV_CAL_AUTMAN_FF_IN_2_LAST); 
 IGV_CAL_AUTO_NOT =! IGV_CAL_AUTMAN_FF_T_FLIPFLOP;
IGV_CAL_AUTO_MAN_B_NAME = IGV_CAL_AUTMAN_FF_T_FLIPFLOP;
IGV_CAL_CALENBL_B_NAME = OP_INTRFC_IGVCALENBL_B_NAME;
  bool IGV_CAL_CALENBLOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , IGV_CAL_NOT_START_NOT , IGV_CAL_WAR_OR_OR,&IGV_CAL_CALENBLOS_ONE_SHOT,&IGV_CAL_CALENBLOS_R_TIME,&IGV_CAL_CALENBLOS_LAST_TRIGGER);
if(IGV_CAL_SFC_HOLD_TRAN_1 || IGV_CAL_CAL_01_TRAN_1 || IGV_CAL_CAL_02_TRAN_1 || IGV_CAL_CAL_03_TRAN_1 || IGV_CAL_CAL_04_TRAN_1 || IGV_CAL_CAL_05_TRAN_1 || IGV_CAL_CAL_06_TRAN_1 || IGV_CAL_CAL_07_TRAN_1 || IGV_CAL_CAL_09_TRAN_1) { 
	if( IGV_CAL_STRKENOS_ONE_SHOT) {
		IGV_CAL_CAL_00_TRAN_1 = IGV_CAL_STRKENOS_ONE_SHOT;
	} else if( IGV_CAL_NULL_ONE_SHOT) {
		IGV_CAL_CAL_00_TRAN_2 = IGV_CAL_NULL_ONE_SHOT;
	} else if( IGV_CAL_CALENBLOS_ONE_SHOT) {
		IGV_CAL_CAL_00_TRAN_3 = IGV_CAL_CALENBLOS_ONE_SHOT;
	} else 
		IGV_CAL_CAL_00_SFC_STEP= 1
} else {
  IGV_CAL_CAL_00_ACTIVETIME= 0; 
  IGV_CAL_CAL_00_SFC_STEP= 0; 
  IGV_CAL_CAL_00_TRAN_1= 0; 
  IGV_CAL_CAL_00_TRAN_2= 0; 
  IGV_CAL_CAL_00_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_00_TRAN_3) { 
	if( IGV_CAL_NOT_START_NOT) {
		IGV_CAL_CAL_01_TRAN_1 = IGV_CAL_NOT_START_NOT;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_01_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_EQ_1_EQ) {
		IGV_CAL_CAL_01_TRAN_3 = IGV_CAL_EQ_1_EQ;
	} else 
		IGV_CAL_CAL_01_SFC_STEP= 1
} else {
  IGV_CAL_CAL_01_ACTIVETIME= 0; 
  IGV_CAL_CAL_01_SFC_STEP= 0; 
  IGV_CAL_CAL_01_TRAN_1= 0; 
  IGV_CAL_CAL_01_TRAN_2= 0; 
  IGV_CAL_CAL_01_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_01_TRAN_3) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_02_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_02_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_NULLDVR_P_LIM_1) {
		IGV_CAL_CAL_02_TRAN_3 = IGV_CAL_NULLDVR_P_LIM_1;
	} else 
		IGV_CAL_CAL_02_SFC_STEP= 1
} else {
  IGV_CAL_CAL_02_ACTIVETIME= 0; 
  IGV_CAL_CAL_02_SFC_STEP= 0; 
  IGV_CAL_CAL_02_TRAN_1= 0; 
  IGV_CAL_CAL_02_TRAN_2= 0; 
  IGV_CAL_CAL_02_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_02_TRAN_3) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_03_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_DLYFAIL_1_DELAY) {
		IGV_CAL_CAL_03_TRAN_2 = IGV_CAL_DLYFAIL_1_DELAY;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_03_TRAN_3 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_LO_DELAY) {
		IGV_CAL_CAL_03_TRAN_4 = IGV_CAL_DLY_LO_DELAY;
	} else 
		IGV_CAL_CAL_03_SFC_STEP= 1
} else {
  IGV_CAL_CAL_03_ACTIVETIME= 0; 
  IGV_CAL_CAL_03_SFC_STEP= 0; 
  IGV_CAL_CAL_03_TRAN_1= 0; 
  IGV_CAL_CAL_03_TRAN_2= 0; 
  IGV_CAL_CAL_03_TRAN_3= 0; 
  IGV_CAL_CAL_03_TRAN_4 = 0; 
}
if(IGV_CAL_CAL_03_TRAN_4) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_04_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_04_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_EQ_2_EQ) {
		IGV_CAL_CAL_04_TRAN_3 = IGV_CAL_EQ_2_EQ;
	} else 
		IGV_CAL_CAL_04_SFC_STEP= 1
} else {
  IGV_CAL_CAL_04_ACTIVETIME= 0; 
  IGV_CAL_CAL_04_SFC_STEP= 0; 
  IGV_CAL_CAL_04_TRAN_1= 0; 
  IGV_CAL_CAL_04_TRAN_2= 0; 
  IGV_CAL_CAL_04_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_04_TRAN_3) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_05_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_05_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_NULLDVR_P_LIM_2) {
		IGV_CAL_CAL_05_TRAN_3 = IGV_CAL_NULLDVR_P_LIM_2;
	} else 
		IGV_CAL_CAL_05_SFC_STEP= 1
} else {
  IGV_CAL_CAL_05_ACTIVETIME= 0; 
  IGV_CAL_CAL_05_SFC_STEP= 0; 
  IGV_CAL_CAL_05_TRAN_1= 0; 
  IGV_CAL_CAL_05_TRAN_2= 0; 
  IGV_CAL_CAL_05_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_05_TRAN_3) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_06_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_DLYFAIL_2_DELAY) {
		IGV_CAL_CAL_06_TRAN_2 = IGV_CAL_DLYFAIL_2_DELAY;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_06_TRAN_3 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_HI_DELAY) {
		IGV_CAL_CAL_06_TRAN_4 = IGV_CAL_DLY_HI_DELAY;
	} else 
		IGV_CAL_CAL_06_SFC_STEP= 1
} else {
  IGV_CAL_CAL_06_ACTIVETIME= 0; 
  IGV_CAL_CAL_06_SFC_STEP= 0; 
  IGV_CAL_CAL_06_TRAN_1= 0; 
  IGV_CAL_CAL_06_TRAN_2= 0; 
  IGV_CAL_CAL_06_TRAN_3= 0; 
  IGV_CAL_CAL_06_TRAN_4 = 0; 
}
if(IGV_CAL_CAL_06_TRAN_4) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_CAL_07_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_07_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_EQ_3_NOSTR_AND) {
		IGV_CAL_CAL_07_TRAN_3 = IGV_CAL_EQ_3_NOSTR_AND;
	} else 
		IGV_CAL_CAL_07_SFC_STEP= 1
} else {
  IGV_CAL_CAL_07_ACTIVETIME= 0; 
  IGV_CAL_CAL_07_SFC_STEP= 0; 
  IGV_CAL_CAL_07_TRAN_1= 0; 
  IGV_CAL_CAL_07_TRAN_2= 0; 
  IGV_CAL_CAL_07_TRAN_3 = 0; 
}
if(IGV_CAL_CAL_07_TRAN_3) { 
	if( IGV_CAL_NOT_STROKE_NOT) {
		IGV_CAL_CAL_07A_TRAN_1 = IGV_CAL_NOT_STROKE_NOT;
	} else if( IGV_CAL_AB_AUT_OR) {
		IGV_CAL_CAL_07A_TRAN_2 = IGV_CAL_AB_AUT_OR;
	} else 
		IGV_CAL_CAL_07A_SFC_STEP= 1
} else {
  IGV_CAL_CAL_07A_ACTIVETIME= 0; 
  IGV_CAL_CAL_07A_SFC_STEP= 0; 
  IGV_CAL_CAL_07A_TRAN_1= 0; 
  IGV_CAL_CAL_07A_TRAN_2 = 0; 
}
if(IGV_CAL_CAL_07A_TRAN_2) { 
	if( IGV_CAL_NV_WRITE_ONE_SHOT) {
		IGV_CAL_CAL_08_TRAN_1 = IGV_CAL_NV_WRITE_ONE_SHOT;
	} else 
		IGV_CAL_CAL_08_SFC_STEP= 1
} else {
  IGV_CAL_CAL_08_ACTIVETIME= 0; 
  IGV_CAL_CAL_08_SFC_STEP= 0; 
  IGV_CAL_CAL_08_TRAN_1 = 0; 
}
if(IGV_CAL_CAL_08_TRAN_1) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_09_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_MASK_MAN_AND) {
		IGV_CAL_CAL_09_TRAN_2 = IGV_CAL_MASK_MAN_AND;
	} else if( IGV_CAL_MASK_AUTO_AND) {
		IGV_CAL_CAL_09_TRAN_3 = IGV_CAL_MASK_AUTO_AND;
	} else 
		IGV_CAL_CAL_09_SFC_STEP= 1
} else {
  IGV_CAL_CAL_09_ACTIVETIME= 0; 
  IGV_CAL_CAL_09_SFC_STEP= 0; 
  IGV_CAL_CAL_09_TRAN_1= 0; 
  IGV_CAL_CAL_09_TRAN_2= 0; 
  IGV_CAL_CAL_09_TRAN_3 = 0; 
}
IGV_CAL_CAL_AUT_NOT =! IGV_CAL_AUTMAN_FF_T_FLIPFLOP;
IGV_CAL_CAL_ENBL_B_NAME = IGV_CAL_ENABLE_Z_ZMINUS1_B;
if(IGV_CAL_CAL_03_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		IGV_CAL_CAL_FAIL_1_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		IGV_CAL_CAL_FAIL_1_SFC_STEP= 1
} else {
  IGV_CAL_CAL_FAIL_1_ACTIVETIME= 0; 
  IGV_CAL_CAL_FAIL_1_SFC_STEP= 0; 
  IGV_CAL_CAL_FAIL_1_TRAN_1 = 0; 
}
if(IGV_CAL_CAL_06_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		IGV_CAL_CAL_FAIL_2_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		IGV_CAL_CAL_FAIL_2_SFC_STEP= 1
} else {
  IGV_CAL_CAL_FAIL_2_ACTIVETIME= 0; 
  IGV_CAL_CAL_FAIL_2_SFC_STEP= 0; 
  IGV_CAL_CAL_FAIL_2_TRAN_1 = 0; 
}
IGV_CAL_ENABLE_OR_OR = IGV_CAL_CAL_01_SFC_STEP || IGV_CAL_CAL_02_SFC_STEP || IGV_CAL_CAL_03_SFC_STEP || IGV_CAL_CAL_04_SFC_STEP || IGV_CAL_CAL_05_SFC_STEP || IGV_CAL_CAL_06_SFC_STEP || IGV_CAL_CAL_07_SFC_STEP || IGV_CAL_CAL_07A_SFC_STEP;
IGV_CAL_ENABLE_Z_ZMINUS1_B = IGV_CAL_ENABLE_OR_OR;
IGV_CAL_MASK_AUTO_AND = IGV_CAL_EQ_0_EQ && IGV_CAL_AUTO_NOT;
IGV_CAL_MASK_MAN_AND = IGV_CAL_EQ_0_EQ && IGV_CAL_AUTMAN_FF_T_FLIPFLOP;
IGV_CAL_NOT_START_NOT =! IGV_CAL_CALMODE_B_NAME;
IGV_CAL_NOT_STROKE_NOT =! IGV_CAL_CALMODE_B_NAME;
  bool IGV_CAL_NULL_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , IGV_CAL_NUL_SEL_B_NAME,&IGV_CAL_NULL_ONE_SHOT,&IGV_CAL_NULL_R_TIME,&IGV_CAL_NULL_LAST_TRIGGER);
IGV_CAL_NUL_SEL_B_NAME = OP_INTRFC_IGV_NULL_B_NAME;
  bool IGV_CAL_NV_WRITE_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , IGV_CAL_CAL_08_SFC_STEP,&IGV_CAL_NV_WRITE_ONE_SHOT,&IGV_CAL_NV_WRITE_R_TIME,&IGV_CAL_NV_WRITE_LAST_TRIGGER);
  bool IGV_CAL_PUCNHOUTOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , IGV_CAL_ABORT_B_NAME,&IGV_CAL_PUCNHOUTOS_ONE_SHOT,&IGV_CAL_PUCNHOUTOS_R_TIME,&IGV_CAL_PUCNHOUTOS_LAST_TRIGGER);
IGV_CAL_PUNCH_OR_OR = IGV_CAL_PUCNHOUTOS_ONE_SHOT || IGV_CAL_NOT_START_NOT;
if(IGV_CAL_CAL_01_TRAN_2 || IGV_CAL_CAL_11_TRAN_1 || IGV_CAL_CAL_12_TRAN_1 || IGV_CAL_CAL_13_TRAN_1 || IGV_CAL_CAL_14_TRAN_1 || IGV_CAL_CAL_15_TRAN_1 || IGV_CAL_CAL_16_TRAN_1 || IGV_CAL_CAL_16_TRAN_2 || IGV_CAL_CAL_FAIL_1_TRAN_1 || IGV_CAL_CAL_FAIL_2_TRAN_1 || IGV_CAL_CAL_07A_TRAN_1 || IGV_CAL_CAL_02_TRAN_2 || IGV_CAL_CAL_03_TRAN_3 || IGV_CAL_CAL_04_TRAN_2 || IGV_CAL_CAL_05_TRAN_2 || IGV_CAL_CAL_06_TRAN_3 || IGV_CAL_CAL_07_TRAN_2 || IGV_CAL_CAL_09_TRAN_2 || IGV_CAL_CAL_10_TRAN_1) { 
	if( IGV_CAL_EQ_0_EQ) {
		IGV_CAL_SFC_HOLD_TRAN_1 = IGV_CAL_EQ_0_EQ;
	} else 
		IGV_CAL_SFC_HOLD_SFC_STEP= 1
} else {
  IGV_CAL_SFC_HOLD_ACTIVETIME= 0; 
  IGV_CAL_SFC_HOLD_SFC_STEP= 0; 
  IGV_CAL_SFC_HOLD_TRAN_1 = 0; 
}
  bool IGV_CAL_STRKENOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , IGV_CAL_NOT_START_NOT , IGV_CAL_STROKE_B_NAME,&IGV_CAL_STRKENOS_ONE_SHOT,&IGV_CAL_STRKENOS_R_TIME,&IGV_CAL_STRKENOS_LAST_TRIGGER);
IGV_CAL_STROKE_B_NAME = OP_INTRFC_IGV_STROKE_B_NAME;
IGV_CAL_WAR_OR_OR = LOC_REM_DELAY_WAR_DELAY || IGV_CAL_CALENBL_B_NAME;
