R_WF36MIN_AIMULT_A_NAME = R_WF36MIN_T_SIAITL_CURVES_2;
R_WF36MIN_SIMULT_A_NAME = R_WF36MIN_SIMULTTMP_SUBTRACT;
R_WF36MIN_SIMULTTMP_SUBTRACT = 1 - R_WF36MIN_T_SIAITL_CURVES_2;
CURVES_2_FUNCTION(1 , 0 , 0 , 0 , 5418-2587A_GE , I_N25_N25SEL_A_NAME , T_SIAITL,&R_WF36MIN_T_SIAITL_CURVES_2,&R_WF36MIN_T_SIAITL_REV_OUT);
R_WF36MIN_WFLBO_A_NAME = R_WF36MIN_WFLBOTMP_CALCULATE;
R_WF36MIN_WFLBOTMP_CALCULATE =  (W_WFTFDM_G_WFMN_A_NAME *R_WF36MIN_T_SIAITL_CURVES_2 ) + (E_WFSIDM_WFLBOSI_A_NAME *R_WF36MIN_SIMULTTMP_SUBTRACT ) ;
R_WF36MIN_WFLPRX_A_NAME = R_WF36MIN_WFLPRXTMP_CALCULATE;
R_WF36MIN_WFLPRXTMP_CALCULATE =  (R_WF36MIN_WFLBOTMP_CALCULATE /R_WF36DMD_PPHTOPCT_A_NAME ) ;
