GP1_CALC_ACFMLEGADD_ADD = GP1_CALC_ACFM_INR_DIVIDE + GP1_CALC_ACFM_OTR_DIVIDE + GP1_CALC_ACFM_PIL_DIVIDE;
GP1_CALC_ACFM_INR_DIVIDE = GP1_CALC_RHO_NG_INR_CALCULATE / CORE_ANALOG_WFGMVI;
GP1_CALC_ACFM_OTR_DIVIDE = GP1_CALC_RHO_NG_OTR_CALCULATE / CORE_ANALOG_WFGMVO;
GP1_CALC_ACFM_PIL_DIVIDE = GP1_CALC_RHO_NG_PIL_CALCULATE / CORE_ANALOG_WFGMVP;
switch(GP1_CALC_SELECT_FLO_I_NAME) { 
  case_1:
    GP1_CALC_FLOW_SEL_A_MUX_N_1 = GP1_CALC_ACFMLEGADD_ADD;
  break;
  case_2:
    GP1_CALC_FLOW_SEL_A_MUX_N_1 = GP1_CALC_SCFH_CNVT_CALCULATE;
  break;
  case_3:
    GP1_CALC_FLOW_SEL_A_MUX_N_1 = GP1_CALC_SCFM_CNVT_CALCULATE;
  break;
}
switch(GP1_CALC_SELECT_FLO_I_NAME) { 
  case_1:
    GP1_CALC_OUT_RANGE_A_MUX_N_1 = 10000;
  break;
  case_2:
    GP1_CALC_OUT_RANGE_A_MUX_N_1 = 500000;
  break;
  case_3:
    GP1_CALC_OUT_RANGE_A_MUX_N_1 = 10000;
  break;
}
GP1_CALC_RHO_NG_INR_CALCULATE =  (  (CORE_ANALOG_GP1ISEL *GP1_CALC_SG_I_RHO_MULTIPLY * 144 )  /  (CORE_ANALOG_ZSEL *1545.0 *  (CORE_ANALOG_TGSSEL + 459.67 )  )  ) ;
GP1_CALC_RHO_NG_OTR_CALCULATE =  (  (CORE_ANALOG_GP1ISEL *GP1_CALC_SG_O_RHO_MULTIPLY * 144 )  /  (CORE_ANALOG_ZSEL *1545.0 *  (CORE_ANALOG_TGSSEL + 459.67 )  )  ) ;
GP1_CALC_RHO_NG_PIL_CALCULATE =  (  (CORE_ANALOG_GP1ISEL *GP1_CALC_SG_P_RHO_MULTIPLY * 144 )  /  (CORE_ANALOG_ZSEL *1545.0 *  (CORE_ANALOG_TGSSEL + 459.67 )  )  ) ;
GP1_CALC_SCFH_CNVT_CALCULATE =  (  (GP1_CALC_WF36ACTFLO_ADD * 13.333 )  /CORE_ANALOG_SG ) ;
GP1_CALC_SCFM_CNVT_CALCULATE =  (  (GP1_CALC_WF36ACTFLO_ADD * 13.333 )  /CORE_ANALOG_SG )  / 60;
GP1_CALC_SELECT_FLO_I_NAME = 2;
GP1_CALC_SG_I_RHO_MULTIPLY = 28.97 * IFACE_HDWR_SG_A_NAME;
GP1_CALC_SG_O_RHO_MULTIPLY = 28.97 * IFACE_HDWR_SG_A_NAME;
GP1_CALC_SG_P_RHO_MULTIPLY = 28.97 * IFACE_HDWR_SG_A_NAME;
GP1_CALC_WF36ACTFLO_ADD = CORE_ANALOG_WFGMVI + CORE_ANALOG_WFGMVP + CORE_ANALOG_WFGMVO;
