TBV_CAL_ABORT_B_NAME = OP_INTRFC_TBV_ABORT_B_NAME;
TBV_CAL_AB_AUT_OR = TBV_CAL_CAL_AUT_NOT || TBV_CAL_PUNCH_OR_OR;
TBV_CAL_AT_0_B_NAME = TBV_CAL_AT_0_SW_B_SW;
TBV_CAL_AT_0_IN_B_NAME = OP_INTRFC_TBV_AT_0_B_NAME;
  bool TBV_CAL_AT_0_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , TBV_CAL_AT_0_IN_B_NAME,&TBV_CAL_AT_0_OS_ONE_SHOT,&TBV_CAL_AT_0_OS_R_TIME,&TBV_CAL_AT_0_OS_LAST_TRIGGER);
TBV_CAL_AT_0_SW_B_SW = B_SW_FUNCTION( TBV_CAL_AUTMAN_FF_T_FLIPFLOP , TBV_CAL_CAL_04_SFC_STEP , TBV_CAL_AT_0_OS_ONE_SHOT );
TBV_CAL_AT_100_B_NAME = TBV_CAL_AT_100_SW_B_SW;
TBV_CAL_AT_100_IN_B_NAME = OP_INTRFC_TBV_AT_100_B_NAME;
  bool TBV_CAL_AT_100_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , TBV_CAL_AT_100_IN_B_NAME,&TBV_CAL_AT_100_OS_ONE_SHOT,&TBV_CAL_AT_100_OS_R_TIME,&TBV_CAL_AT_100_OS_LAST_TRIGGER);
TBV_CAL_AT_100_SW_B_SW = B_SW_FUNCTION( TBV_CAL_AUTMAN_FF_T_FLIPFLOP , TBV_CAL_CAL_07_SFC_STEP , TBV_CAL_AT_100_OS_ONE_SHOT );
TBV_CAL_AUTMANSEL_B_NAME = OP_INTRFC_TBV_A_M_B_NAME;
  bool TBV_CAL_AUTMAN_FF_IN_1_LAST; 
  bool TBV_CAL_AUTMAN_FF_IN_2_LAST; 
T_FLIPFLOP_FUNCTION(1 , TBV_CAL_AUTMANSEL_B_NAME , *FALSE , LOC_REM_DELAY_WAR_DELAY,&TBV_CAL_AUTMAN_FF_T_FLIPFLOP,&TBV_CAL_AUTMAN_FF_IN_1_LAST, &TBV_CAL_AUTMAN_FF_IN_2_LAST); 
 TBV_CAL_AUTO_NOT =! TBV_CAL_AUTMAN_FF_T_FLIPFLOP;
TBV_CAL_AUTO_MAN_B_NAME = TBV_CAL_AUTMAN_FF_T_FLIPFLOP;
TBV_CAL_CALENBL_B_NAME = OP_INTRFC_TBVCALENBL_B_NAME;
  bool TBV_CAL_CALENBLOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , TBV_CAL_NOT_START_NOT , TBV_CAL_WAR_OR_OR,&TBV_CAL_CALENBLOS_ONE_SHOT,&TBV_CAL_CALENBLOS_R_TIME,&TBV_CAL_CALENBLOS_LAST_TRIGGER);
if(TBV_CAL_SFC_HOLD_TRAN_1 || TBV_CAL_CAL_01_TRAN_1 || TBV_CAL_CAL_02_TRAN_1 || TBV_CAL_CAL_03_TRAN_1 || TBV_CAL_CAL_04_TRAN_1 || TBV_CAL_CAL_05_TRAN_1 || TBV_CAL_CAL_06_TRAN_1 || TBV_CAL_CAL_07_TRAN_1 || TBV_CAL_CAL_09_TRAN_1) { 
	if( TBV_CAL_STRKENOS_ONE_SHOT) {
		TBV_CAL_CAL_00_TRAN_1 = TBV_CAL_STRKENOS_ONE_SHOT;
	} else if( TBV_CAL_NULL_ONE_SHOT) {
		TBV_CAL_CAL_00_TRAN_2 = TBV_CAL_NULL_ONE_SHOT;
	} else if( TBV_CAL_CALENBLOS_ONE_SHOT) {
		TBV_CAL_CAL_00_TRAN_3 = TBV_CAL_CALENBLOS_ONE_SHOT;
	} else 
		TBV_CAL_CAL_00_SFC_STEP= 1
} else {
  TBV_CAL_CAL_00_ACTIVETIME= 0; 
  TBV_CAL_CAL_00_SFC_STEP= 0; 
  TBV_CAL_CAL_00_TRAN_1= 0; 
  TBV_CAL_CAL_00_TRAN_2= 0; 
  TBV_CAL_CAL_00_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_00_TRAN_3) { 
	if( TBV_CAL_NOT_START_NOT) {
		TBV_CAL_CAL_01_TRAN_1 = TBV_CAL_NOT_START_NOT;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_01_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_EQ_1_EQ) {
		TBV_CAL_CAL_01_TRAN_3 = TBV_CAL_EQ_1_EQ;
	} else 
		TBV_CAL_CAL_01_SFC_STEP= 1
} else {
  TBV_CAL_CAL_01_ACTIVETIME= 0; 
  TBV_CAL_CAL_01_SFC_STEP= 0; 
  TBV_CAL_CAL_01_TRAN_1= 0; 
  TBV_CAL_CAL_01_TRAN_2= 0; 
  TBV_CAL_CAL_01_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_01_TRAN_3) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_02_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_02_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_NULLDVR_P_LIM_1) {
		TBV_CAL_CAL_02_TRAN_3 = TBV_CAL_NULLDVR_P_LIM_1;
	} else 
		TBV_CAL_CAL_02_SFC_STEP= 1
} else {
  TBV_CAL_CAL_02_ACTIVETIME= 0; 
  TBV_CAL_CAL_02_SFC_STEP= 0; 
  TBV_CAL_CAL_02_TRAN_1= 0; 
  TBV_CAL_CAL_02_TRAN_2= 0; 
  TBV_CAL_CAL_02_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_02_TRAN_3) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_03_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_DLYFAIL_1_DELAY) {
		TBV_CAL_CAL_03_TRAN_2 = TBV_CAL_DLYFAIL_1_DELAY;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_03_TRAN_3 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_LO_DELAY) {
		TBV_CAL_CAL_03_TRAN_4 = TBV_CAL_DLY_LO_DELAY;
	} else 
		TBV_CAL_CAL_03_SFC_STEP= 1
} else {
  TBV_CAL_CAL_03_ACTIVETIME= 0; 
  TBV_CAL_CAL_03_SFC_STEP= 0; 
  TBV_CAL_CAL_03_TRAN_1= 0; 
  TBV_CAL_CAL_03_TRAN_2= 0; 
  TBV_CAL_CAL_03_TRAN_3= 0; 
  TBV_CAL_CAL_03_TRAN_4 = 0; 
}
if(TBV_CAL_CAL_03_TRAN_4) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_04_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_04_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_EQ_2_EQ) {
		TBV_CAL_CAL_04_TRAN_3 = TBV_CAL_EQ_2_EQ;
	} else 
		TBV_CAL_CAL_04_SFC_STEP= 1
} else {
  TBV_CAL_CAL_04_ACTIVETIME= 0; 
  TBV_CAL_CAL_04_SFC_STEP= 0; 
  TBV_CAL_CAL_04_TRAN_1= 0; 
  TBV_CAL_CAL_04_TRAN_2= 0; 
  TBV_CAL_CAL_04_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_04_TRAN_3) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_05_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_05_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_NULLDVR_P_LIM_2) {
		TBV_CAL_CAL_05_TRAN_3 = TBV_CAL_NULLDVR_P_LIM_2;
	} else 
		TBV_CAL_CAL_05_SFC_STEP= 1
} else {
  TBV_CAL_CAL_05_ACTIVETIME= 0; 
  TBV_CAL_CAL_05_SFC_STEP= 0; 
  TBV_CAL_CAL_05_TRAN_1= 0; 
  TBV_CAL_CAL_05_TRAN_2= 0; 
  TBV_CAL_CAL_05_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_05_TRAN_3) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_06_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_DLYFAIL_2_DELAY) {
		TBV_CAL_CAL_06_TRAN_2 = TBV_CAL_DLYFAIL_2_DELAY;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_06_TRAN_3 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_HI_DELAY) {
		TBV_CAL_CAL_06_TRAN_4 = TBV_CAL_DLY_HI_DELAY;
	} else 
		TBV_CAL_CAL_06_SFC_STEP= 1
} else {
  TBV_CAL_CAL_06_ACTIVETIME= 0; 
  TBV_CAL_CAL_06_SFC_STEP= 0; 
  TBV_CAL_CAL_06_TRAN_1= 0; 
  TBV_CAL_CAL_06_TRAN_2= 0; 
  TBV_CAL_CAL_06_TRAN_3= 0; 
  TBV_CAL_CAL_06_TRAN_4 = 0; 
}
if(TBV_CAL_CAL_06_TRAN_4) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_CAL_07_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_07_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_EQ_3_NOSTR_AND) {
		TBV_CAL_CAL_07_TRAN_3 = TBV_CAL_EQ_3_NOSTR_AND;
	} else 
		TBV_CAL_CAL_07_SFC_STEP= 1
} else {
  TBV_CAL_CAL_07_ACTIVETIME= 0; 
  TBV_CAL_CAL_07_SFC_STEP= 0; 
  TBV_CAL_CAL_07_TRAN_1= 0; 
  TBV_CAL_CAL_07_TRAN_2= 0; 
  TBV_CAL_CAL_07_TRAN_3 = 0; 
}
if(TBV_CAL_CAL_07_TRAN_3) { 
	if( TBV_CAL_NOT_STROKE_NOT) {
		TBV_CAL_CAL_07A_TRAN_1 = TBV_CAL_NOT_STROKE_NOT;
	} else if( TBV_CAL_AB_AUT_OR) {
		TBV_CAL_CAL_07A_TRAN_2 = TBV_CAL_AB_AUT_OR;
	} else 
		TBV_CAL_CAL_07A_SFC_STEP= 1
} else {
  TBV_CAL_CAL_07A_ACTIVETIME= 0; 
  TBV_CAL_CAL_07A_SFC_STEP= 0; 
  TBV_CAL_CAL_07A_TRAN_1= 0; 
  TBV_CAL_CAL_07A_TRAN_2 = 0; 
}
if(TBV_CAL_CAL_07A_TRAN_2) { 
	if( TBV_CAL_NV_WRITE_ONE_SHOT) {
		TBV_CAL_CAL_08_TRAN_1 = TBV_CAL_NV_WRITE_ONE_SHOT;
	} else 
		TBV_CAL_CAL_08_SFC_STEP= 1
} else {
  TBV_CAL_CAL_08_ACTIVETIME= 0; 
  TBV_CAL_CAL_08_SFC_STEP= 0; 
  TBV_CAL_CAL_08_TRAN_1 = 0; 
}
if(TBV_CAL_CAL_08_TRAN_1) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_09_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_MASK_MAN_AND) {
		TBV_CAL_CAL_09_TRAN_2 = TBV_CAL_MASK_MAN_AND;
	} else if( TBV_CAL_MASK_AUTO_AND) {
		TBV_CAL_CAL_09_TRAN_3 = TBV_CAL_MASK_AUTO_AND;
	} else 
		TBV_CAL_CAL_09_SFC_STEP= 1
} else {
  TBV_CAL_CAL_09_ACTIVETIME= 0; 
  TBV_CAL_CAL_09_SFC_STEP= 0; 
  TBV_CAL_CAL_09_TRAN_1= 0; 
  TBV_CAL_CAL_09_TRAN_2= 0; 
  TBV_CAL_CAL_09_TRAN_3 = 0; 
}
TBV_CAL_CAL_AUT_NOT =! TBV_CAL_AUTMAN_FF_T_FLIPFLOP;
TBV_CAL_CAL_ENBL_B_NAME = TBV_CAL_ENABLE_Z_ZMINUS1_B;
if(TBV_CAL_CAL_03_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		TBV_CAL_CAL_FAIL_1_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		TBV_CAL_CAL_FAIL_1_SFC_STEP= 1
} else {
  TBV_CAL_CAL_FAIL_1_ACTIVETIME= 0; 
  TBV_CAL_CAL_FAIL_1_SFC_STEP= 0; 
  TBV_CAL_CAL_FAIL_1_TRAN_1 = 0; 
}
if(TBV_CAL_CAL_06_TRAN_2) { 
	if( ALARM_RESET_B_NAME) {
		TBV_CAL_CAL_FAIL_2_TRAN_1 = ALARM_RESET_B_NAME;
	} else 
		TBV_CAL_CAL_FAIL_2_SFC_STEP= 1
} else {
  TBV_CAL_CAL_FAIL_2_ACTIVETIME= 0; 
  TBV_CAL_CAL_FAIL_2_SFC_STEP= 0; 
  TBV_CAL_CAL_FAIL_2_TRAN_1 = 0; 
}
TBV_CAL_ENABLE_OR_OR = TBV_CAL_CAL_01_SFC_STEP || TBV_CAL_CAL_02_SFC_STEP || TBV_CAL_CAL_03_SFC_STEP || TBV_CAL_CAL_04_SFC_STEP || TBV_CAL_CAL_05_SFC_STEP || TBV_CAL_CAL_06_SFC_STEP || TBV_CAL_CAL_07_SFC_STEP || TBV_CAL_CAL_07A_SFC_STEP;
TBV_CAL_ENABLE_Z_ZMINUS1_B = TBV_CAL_ENABLE_OR_OR;
TBV_CAL_MASK_AUTO_AND = TBV_CAL_EQ_0_EQ && TBV_CAL_AUTO_NOT;
TBV_CAL_MASK_MAN_AND = TBV_CAL_EQ_0_EQ && TBV_CAL_AUTMAN_FF_T_FLIPFLOP;
TBV_CAL_NOT_START_NOT =! TBV_CAL_CALMODE_B_NAME;
TBV_CAL_NOT_STROKE_NOT =! TBV_CAL_CALMODE_B_NAME;
  bool TBV_CAL_NULL_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , TBV_CAL_NUL_SEL_B_NAME,&TBV_CAL_NULL_ONE_SHOT,&TBV_CAL_NULL_R_TIME,&TBV_CAL_NULL_LAST_TRIGGER);
TBV_CAL_NUL_SEL_B_NAME = OP_INTRFC_TBV_NULL_B_NAME;
  bool TBV_CAL_NV_WRITE_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , TBV_CAL_CAL_08_SFC_STEP,&TBV_CAL_NV_WRITE_ONE_SHOT,&TBV_CAL_NV_WRITE_R_TIME,&TBV_CAL_NV_WRITE_LAST_TRIGGER);
  bool TBV_CAL_PUCNHOUTOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , TBV_CAL_ABORT_B_NAME,&TBV_CAL_PUCNHOUTOS_ONE_SHOT,&TBV_CAL_PUCNHOUTOS_R_TIME,&TBV_CAL_PUCNHOUTOS_LAST_TRIGGER);
TBV_CAL_PUNCH_OR_OR = TBV_CAL_PUCNHOUTOS_ONE_SHOT || TBV_CAL_NOT_START_NOT;
if(TBV_CAL_CAL_01_TRAN_2 || TBV_CAL_CAL_11_TRAN_1 || TBV_CAL_CAL_12_TRAN_1 || TBV_CAL_CAL_13_TRAN_1 || TBV_CAL_CAL_14_TRAN_1 || TBV_CAL_CAL_15_TRAN_1 || TBV_CAL_CAL_16_TRAN_1 || TBV_CAL_CAL_16_TRAN_2 || TBV_CAL_CAL_FAIL_1_TRAN_1 || TBV_CAL_CAL_FAIL_2_TRAN_1 || TBV_CAL_CAL_07A_TRAN_1 || TBV_CAL_CAL_02_TRAN_2 || TBV_CAL_CAL_03_TRAN_3 || TBV_CAL_CAL_04_TRAN_2 || TBV_CAL_CAL_05_TRAN_2 || TBV_CAL_CAL_06_TRAN_3 || TBV_CAL_CAL_07_TRAN_2 || TBV_CAL_CAL_09_TRAN_2 || TBV_CAL_CAL_10_TRAN_1) { 
	if( TBV_CAL_EQ_0_EQ) {
		TBV_CAL_SFC_HOLD_TRAN_1 = TBV_CAL_EQ_0_EQ;
	} else 
		TBV_CAL_SFC_HOLD_SFC_STEP= 1
} else {
  TBV_CAL_SFC_HOLD_ACTIVETIME= 0; 
  TBV_CAL_SFC_HOLD_SFC_STEP= 0; 
  TBV_CAL_SFC_HOLD_TRAN_1 = 0; 
}
  bool TBV_CAL_STRKENOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , TBV_CAL_NOT_START_NOT , TBV_CAL_STROKE_B_NAME,&TBV_CAL_STRKENOS_ONE_SHOT,&TBV_CAL_STRKENOS_R_TIME,&TBV_CAL_STRKENOS_LAST_TRIGGER);
TBV_CAL_STROKE_B_NAME = OP_INTRFC_TBV_STROKE_B_NAME;
TBV_CAL_WAR_OR_OR = LOC_REM_DELAY_WAR_DELAY || TBV_CAL_CALENBL_B_NAME;
