TBV_CAL_AVERAGE_CALCULATE =  (-20.0 )  -  (  (TBV_CAL_AVG1_A_OUT_7 +TBV_CAL_AVG2_A_OUT_7 +TBV_CAL_AVG3_A_OUT_7 +TBV_CAL_AVG4_A_OUT_7 +TBV_CAL_AVG5_A_OUT_7 )  / 5 ) ;
if (TBV_CAL_MIN_AND== TRUE){   TBV_CAL_AVG1_A_OUT_6 = TBV_CAL_AVG1_A_OUT_5;   TBV_CAL_AVG1_A_OUT_5 = TBV_CAL_AVG1_A_OUT_4;   TBV_CAL_AVG1_A_OUT_4 = TBV_CAL_AVG1_A_OUT_3;   TBV_CAL_AVG1_A_OUT_3 = TBV_CAL_AVG1_A_OUT_2;   TBV_CAL_AVG1_A_OUT_2 = TBV_CAL_AVG1_A_OUT_1;   TBV_CAL_AVG1_A_OUT_1 = TBV_CAL_CURRENT_A_NAME;   TBV_CAL_AVG1_A_OUT_7 = (TBV_CAL_AVG1_A_OUT_1+TBV_CAL_AVG1_A_OUT_2+TBV_CAL_AVG1_A_OUT_3+   TBV_CAL_AVG1_A_OUT_4+TBV_CAL_AVG1_A_OUT_5+TBV_CAL_AVG1_A_OUT_6)/6;}   else {   TBV_CAL_AVG1_A_OUT_6 = TBV_CAL_AVG1_A_OUT_6;   TBV_CAL_AVG1_A_OUT_5 = TBV_CAL_AVG1_A_OUT_5;   TBV_CAL_AVG1_A_OUT_4 = TBV_CAL_AVG1_A_OUT_4;   TBV_CAL_AVG1_A_OUT_3 = TBV_CAL_AVG1_A_OUT_3;   TBV_CAL_AVG1_A_OUT_2 = TBV_CAL_AVG1_A_OUT_2;   TBV_CAL_AVG1_A_OUT_1 = TBV_CAL_AVG1_A_OUT_1;   TBV_CAL_AVG1_A_OUT_7 = TBV_CAL_AVG1_A_OUT_7;};
if (TBV_CAL_LO_MID_AND== TRUE){   TBV_CAL_AVG2_A_OUT_6 = TBV_CAL_AVG2_A_OUT_5;   TBV_CAL_AVG2_A_OUT_5 = TBV_CAL_AVG2_A_OUT_4;   TBV_CAL_AVG2_A_OUT_4 = TBV_CAL_AVG2_A_OUT_3;   TBV_CAL_AVG2_A_OUT_3 = TBV_CAL_AVG2_A_OUT_2;   TBV_CAL_AVG2_A_OUT_2 = TBV_CAL_AVG2_A_OUT_1;   TBV_CAL_AVG2_A_OUT_1 = TBV_CAL_CURRENT_A_NAME;   TBV_CAL_AVG2_A_OUT_7 = (TBV_CAL_AVG2_A_OUT_1+TBV_CAL_AVG2_A_OUT_2+TBV_CAL_AVG2_A_OUT_3+   TBV_CAL_AVG2_A_OUT_4+TBV_CAL_AVG2_A_OUT_5+TBV_CAL_AVG2_A_OUT_6)/6;}   else {   TBV_CAL_AVG2_A_OUT_6 = TBV_CAL_AVG2_A_OUT_6;   TBV_CAL_AVG2_A_OUT_5 = TBV_CAL_AVG2_A_OUT_5;   TBV_CAL_AVG2_A_OUT_4 = TBV_CAL_AVG2_A_OUT_4;   TBV_CAL_AVG2_A_OUT_3 = TBV_CAL_AVG2_A_OUT_3;   TBV_CAL_AVG2_A_OUT_2 = TBV_CAL_AVG2_A_OUT_2;   TBV_CAL_AVG2_A_OUT_1 = TBV_CAL_AVG2_A_OUT_1;   TBV_CAL_AVG2_A_OUT_7 = TBV_CAL_AVG2_A_OUT_7;};
if (TBV_CAL_MID_AND== TRUE){   TBV_CAL_AVG3_A_OUT_6 = TBV_CAL_AVG3_A_OUT_5;   TBV_CAL_AVG3_A_OUT_5 = TBV_CAL_AVG3_A_OUT_4;   TBV_CAL_AVG3_A_OUT_4 = TBV_CAL_AVG3_A_OUT_3;   TBV_CAL_AVG3_A_OUT_3 = TBV_CAL_AVG3_A_OUT_2;   TBV_CAL_AVG3_A_OUT_2 = TBV_CAL_AVG3_A_OUT_1;   TBV_CAL_AVG3_A_OUT_1 = TBV_CAL_CURRENT_A_NAME;   TBV_CAL_AVG3_A_OUT_7 = (TBV_CAL_AVG3_A_OUT_1+TBV_CAL_AVG3_A_OUT_2+TBV_CAL_AVG3_A_OUT_3+   TBV_CAL_AVG3_A_OUT_4+TBV_CAL_AVG3_A_OUT_5+TBV_CAL_AVG3_A_OUT_6)/6;}   else {   TBV_CAL_AVG3_A_OUT_6 = TBV_CAL_AVG3_A_OUT_6;   TBV_CAL_AVG3_A_OUT_5 = TBV_CAL_AVG3_A_OUT_5;   TBV_CAL_AVG3_A_OUT_4 = TBV_CAL_AVG3_A_OUT_4;   TBV_CAL_AVG3_A_OUT_3 = TBV_CAL_AVG3_A_OUT_3;   TBV_CAL_AVG3_A_OUT_2 = TBV_CAL_AVG3_A_OUT_2;   TBV_CAL_AVG3_A_OUT_1 = TBV_CAL_AVG3_A_OUT_1;   TBV_CAL_AVG3_A_OUT_7 = TBV_CAL_AVG3_A_OUT_7;};
if (TBV_CAL_HI_MID_AND== TRUE){   TBV_CAL_AVG4_A_OUT_6 = TBV_CAL_AVG4_A_OUT_5;   TBV_CAL_AVG4_A_OUT_5 = TBV_CAL_AVG4_A_OUT_4;   TBV_CAL_AVG4_A_OUT_4 = TBV_CAL_AVG4_A_OUT_3;   TBV_CAL_AVG4_A_OUT_3 = TBV_CAL_AVG4_A_OUT_2;   TBV_CAL_AVG4_A_OUT_2 = TBV_CAL_AVG4_A_OUT_1;   TBV_CAL_AVG4_A_OUT_1 = TBV_CAL_CURRENT_A_NAME;   TBV_CAL_AVG4_A_OUT_7 = (TBV_CAL_AVG4_A_OUT_1+TBV_CAL_AVG4_A_OUT_2+TBV_CAL_AVG4_A_OUT_3+   TBV_CAL_AVG4_A_OUT_4+TBV_CAL_AVG4_A_OUT_5+TBV_CAL_AVG4_A_OUT_6)/6;}   else {   TBV_CAL_AVG4_A_OUT_6 = TBV_CAL_AVG4_A_OUT_6;   TBV_CAL_AVG4_A_OUT_5 = TBV_CAL_AVG4_A_OUT_5;   TBV_CAL_AVG4_A_OUT_4 = TBV_CAL_AVG4_A_OUT_4;   TBV_CAL_AVG4_A_OUT_3 = TBV_CAL_AVG4_A_OUT_3;   TBV_CAL_AVG4_A_OUT_2 = TBV_CAL_AVG4_A_OUT_2;   TBV_CAL_AVG4_A_OUT_1 = TBV_CAL_AVG4_A_OUT_1;   TBV_CAL_AVG4_A_OUT_7 = TBV_CAL_AVG4_A_OUT_7;};
if (TBV_CAL_MAX_AND== TRUE){   TBV_CAL_AVG5_A_OUT_6 = TBV_CAL_AVG5_A_OUT_5;   TBV_CAL_AVG5_A_OUT_5 = TBV_CAL_AVG5_A_OUT_4;   TBV_CAL_AVG5_A_OUT_4 = TBV_CAL_AVG5_A_OUT_3;   TBV_CAL_AVG5_A_OUT_3 = TBV_CAL_AVG5_A_OUT_2;   TBV_CAL_AVG5_A_OUT_2 = TBV_CAL_AVG5_A_OUT_1;   TBV_CAL_AVG5_A_OUT_1 = TBV_CAL_CURRENT_A_NAME;   TBV_CAL_AVG5_A_OUT_7 = (TBV_CAL_AVG5_A_OUT_1+TBV_CAL_AVG5_A_OUT_2+TBV_CAL_AVG5_A_OUT_3+   TBV_CAL_AVG5_A_OUT_4+TBV_CAL_AVG5_A_OUT_5+TBV_CAL_AVG5_A_OUT_6)/6;}   else {   TBV_CAL_AVG5_A_OUT_6 = TBV_CAL_AVG5_A_OUT_6;   TBV_CAL_AVG5_A_OUT_5 = TBV_CAL_AVG5_A_OUT_5;   TBV_CAL_AVG5_A_OUT_4 = TBV_CAL_AVG5_A_OUT_4;   TBV_CAL_AVG5_A_OUT_3 = TBV_CAL_AVG5_A_OUT_3;   TBV_CAL_AVG5_A_OUT_2 = TBV_CAL_AVG5_A_OUT_2;   TBV_CAL_AVG5_A_OUT_1 = TBV_CAL_AVG5_A_OUT_1;   TBV_CAL_AVG5_A_OUT_7 = TBV_CAL_AVG5_A_OUT_7;};
TBV_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 1 , TBV_CAL_AVERAGE_CALCULATE );
if(TBV_CAL_CAL_09_TRAN_3 || TBV_CAL_CAL_00_TRAN_2) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_10_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_TRAN_1_DELAY) {
		TBV_CAL_CAL_10_TRAN_2 = TBV_CAL_DLY_TRAN_1_DELAY;
	} else 
		TBV_CAL_CAL_10_SFC_STEP= 1
} else {
  TBV_CAL_CAL_10_ACTIVETIME= 0; 
  TBV_CAL_CAL_10_SFC_STEP= 0; 
  TBV_CAL_CAL_10_TRAN_1= 0; 
  TBV_CAL_CAL_10_TRAN_2 = 0; 
}
if(TBV_CAL_CAL_10_TRAN_2) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_11_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_TRAN_2_DELAY) {
		TBV_CAL_CAL_11_TRAN_2 = TBV_CAL_DLY_TRAN_2_DELAY;
	} else 
		TBV_CAL_CAL_11_SFC_STEP= 1
} else {
  TBV_CAL_CAL_11_ACTIVETIME= 0; 
  TBV_CAL_CAL_11_SFC_STEP= 0; 
  TBV_CAL_CAL_11_TRAN_1= 0; 
  TBV_CAL_CAL_11_TRAN_2 = 0; 
}
if(TBV_CAL_CAL_11_TRAN_2) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_12_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_TRAN_3_DELAY) {
		TBV_CAL_CAL_12_TRAN_2 = TBV_CAL_DLY_TRAN_3_DELAY;
	} else 
		TBV_CAL_CAL_12_SFC_STEP= 1
} else {
  TBV_CAL_CAL_12_ACTIVETIME= 0; 
  TBV_CAL_CAL_12_SFC_STEP= 0; 
  TBV_CAL_CAL_12_TRAN_1= 0; 
  TBV_CAL_CAL_12_TRAN_2 = 0; 
}
if(TBV_CAL_CAL_12_TRAN_2) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_13_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_TRAN_4_DELAY) {
		TBV_CAL_CAL_13_TRAN_2 = TBV_CAL_DLY_TRAN_4_DELAY;
	} else 
		TBV_CAL_CAL_13_SFC_STEP= 1
} else {
  TBV_CAL_CAL_13_ACTIVETIME= 0; 
  TBV_CAL_CAL_13_SFC_STEP= 0; 
  TBV_CAL_CAL_13_TRAN_1= 0; 
  TBV_CAL_CAL_13_TRAN_2 = 0; 
}
if(TBV_CAL_CAL_13_TRAN_2) { 
	if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_14_TRAN_1 = TBV_CAL_PUNCH_OR_OR;
	} else if( TBV_CAL_DLY_TRAN_5_DELAY) {
		TBV_CAL_CAL_14_TRAN_2 = TBV_CAL_DLY_TRAN_5_DELAY;
	} else 
		TBV_CAL_CAL_14_SFC_STEP= 1
} else {
  TBV_CAL_CAL_14_ACTIVETIME= 0; 
  TBV_CAL_CAL_14_SFC_STEP= 0; 
  TBV_CAL_CAL_14_TRAN_1= 0; 
  TBV_CAL_CAL_14_TRAN_2 = 0; 
}
  bool TBV_CAL_CAL_14_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , TBV_CAL_CAL_15_SFC_STEP,&TBV_CAL_CAL_14_OS_ONE_SHOT,&TBV_CAL_CAL_14_OS_R_TIME,&TBV_CAL_CAL_14_OS_LAST_TRIGGER);
if(TBV_CAL_CAL_14_TRAN_2) { 
	if( TBV_CAL_CAL_14_OS_ONE_SHOT) {
		TBV_CAL_CAL_15_TRAN_1 = TBV_CAL_CAL_14_OS_ONE_SHOT;
	} else 
		TBV_CAL_CAL_15_SFC_STEP= 1
} else {
  TBV_CAL_CAL_15_ACTIVETIME= 0; 
  TBV_CAL_CAL_15_SFC_STEP= 0; 
  TBV_CAL_CAL_15_TRAN_1 = 0; 
}
if(TBV_CAL_CAL_00_TRAN_1) { 
	if( TBV_CAL_NOTSTROKE_NOT) {
		TBV_CAL_CAL_16_TRAN_1 = TBV_CAL_NOTSTROKE_NOT;
	} else if( TBV_CAL_PUNCH_OR_OR) {
		TBV_CAL_CAL_16_TRAN_2 = TBV_CAL_PUNCH_OR_OR;
	} else 
		TBV_CAL_CAL_16_SFC_STEP= 1
} else {
  TBV_CAL_CAL_16_ACTIVETIME= 0; 
  TBV_CAL_CAL_16_SFC_STEP= 0; 
  TBV_CAL_CAL_16_TRAN_1= 0; 
  TBV_CAL_CAL_16_TRAN_2 = 0; 
}
DELAY_FUNCTION(1 , 5 , 0 , TBV_CAL_DMDVSFDBK_B_OUT_1,&TBV_CAL_DLY_DFCMP_DELAY,&TBV_CAL_DLY_DFCMP_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , TBV_CAL_TRAN_1_AND,&TBV_CAL_DLY_TRAN_1_DELAY,&TBV_CAL_DLY_TRAN_1_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , TBV_CAL_TRAN_2_AND,&TBV_CAL_DLY_TRAN_2_DELAY,&TBV_CAL_DLY_TRAN_2_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , TBV_CAL_TRAN_3_AND,&TBV_CAL_DLY_TRAN_3_DELAY,&TBV_CAL_DLY_TRAN_3_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , TBV_CAL_TRAN_4_AND,&TBV_CAL_DLY_TRAN_4_DELAY,&TBV_CAL_DLY_TRAN_4_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , TBV_CAL_TRAN_5_AND,&TBV_CAL_DLY_TRAN_5_DELAY,&TBV_CAL_DLY_TRAN_5_R_TIME);
if (fabs(TBV_CAL_DEMAND_A_NAME-TBV_CAL_AVG_POS_A_NAME) < TBV_CAL_ERROR_A_NAME)   { TBV_CAL_DMDVSFDBK_B_OUT_1 = true; }   else   { TBV_CAL_DMDVSFDBK_B_OUT_1 = false; };
TBV_CAL_HI_MID_AND = TBV_CAL_CAL_13_SFC_STEP && TBV_CAL_I_CNT_ONE_DELAY && TBV_CAL_DLY_DFCMP_DELAY;
TBV_CAL_I_CNT_NOT =! TBV_CAL_I_CNT_ONE_DELAY;
TBV_CAL_I_CNTPV_ZMINUS1_B = TBV_CAL_I_CNT_NOT;
DELAY_FUNCTION(1 , 0.32 , 0 , TBV_CAL_I_CNTPV_ZMINUS1_B,&TBV_CAL_I_CNT_ONE_DELAY,&TBV_CAL_I_CNT_ONE_R_TIME);
TBV_CAL_LO_MID_AND = TBV_CAL_CAL_11_SFC_STEP && TBV_CAL_I_CNT_ONE_DELAY && TBV_CAL_DLY_DFCMP_DELAY;
TBV_CAL_MAX_AND = TBV_CAL_CAL_14_SFC_STEP && TBV_CAL_I_CNT_ONE_DELAY && TBV_CAL_DLY_DFCMP_DELAY;
TBV_CAL_MID_AND = TBV_CAL_CAL_12_SFC_STEP && TBV_CAL_I_CNT_ONE_DELAY && TBV_CAL_DLY_DFCMP_DELAY;
TBV_CAL_MIN_AND = TBV_CAL_CAL_10_SFC_STEP && TBV_CAL_I_CNT_ONE_DELAY && TBV_CAL_DLY_DFCMP_DELAY;
TBV_CAL_NOTSTROKE_NOT =! TBV_CAL_CALMODE_B_NAME;
TBV_CAL_NULJA_A_NAME = TBV_CAL_NULLBIAS_NO;
A_SW_REV_FUNCTION(TBV_CAL_CAL_14_OS_ONE_SHOT , TBV_CAL_NULLBIAS_NC , TBV_CAL_AVG_NEGATE_NEGATE,&TBV_CAL_NULLBIAS_NC,&TBV_CAL_NULLBIAS_NO);
TBV_CAL_TRAN_1_AND = TBV_CAL_DLY_DFCMP_DELAY && TBV_CAL_CAL_10_SFC_STEP;
TBV_CAL_TRAN_2_AND = TBV_CAL_DLY_DFCMP_DELAY && TBV_CAL_CAL_11_SFC_STEP;
TBV_CAL_TRAN_3_AND = TBV_CAL_DLY_DFCMP_DELAY && TBV_CAL_CAL_12_SFC_STEP;
TBV_CAL_TRAN_4_AND = TBV_CAL_DLY_DFCMP_DELAY && TBV_CAL_CAL_13_SFC_STEP;
TBV_CAL_TRAN_5_AND = TBV_CAL_DLY_DFCMP_DELAY && TBV_CAL_CAL_14_SFC_STEP;
