OP_INTRFC_ACKN_B_NAME = OP_INTRFC_ACKN_MX_B_MUX_N_1;
OP_INTRFC_ACKN_H_B_NAME = N3N40_BI_ACKN_BI_L;
OP_INTRFC_ACKN_MB_B_NAME = DATA_IO_DCS_BW_V_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_1;
  break;
  case 3:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_1;
  break;
  case 4:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = OP_INTRFC_ACKN_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_ACKN_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_AUTOSYNC_B_NAME = OP_INTRFC_AUTOSYNCMX_B_MUX_N_1;
OP_INTRFC_AUTOSYNCMB_B_NAME = DATA_IO_DCS_BW_V_2;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = OP_INTRFC_SP_90_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = DATA_IO_LL2_BW_V_2;
  break;
  case 3:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = DATA_IO_RL2_BW_V_2;
  break;
  case 4:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = OP_INTRFC_AUTOSYNCMB_B_NAME;
  break;
  case 6:
    OP_INTRFC_AUTOSYNCMX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_BASELD_H_B_NAME = FALSE;
OP_INTRFC_BASELD_MB_B_NAME = DATA_IO_DCS_BW_V_3;
OP_INTRFC_BASELOAD_B_NAME = OP_INTRFC_BASE_LOAD_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = OP_INTRFC_BASELD_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = DATA_IO_LL2_BW_V_3;
  break;
  case 3:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = DATA_IO_RL2_BW_V_3;
  break;
  case 4:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = OP_INTRFC_BASELD_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_BASE_LOAD_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_CALMODE_B_NAME = OP_INTRFC_CALMODE_MX_B_MUX_N_1;
OP_INTRFC_CALMODE_M_B_NAME = *FALSE;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_4;
  break;
  case 3:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_4;
  break;
  case 4:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = OP_INTRFC_CALMODE_M_B_NAME;
  break;
  case 6:
    OP_INTRFC_CALMODE_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_DMSEL_H_B_NAME = FALSE;
OP_INTRFC_DMSEL_MB_B_NAME = DATA_IO_DCS_BW_V_9;
OP_INTRFC_DM_RELEASE_B_NAME = OP_INTRFC_DM_RELSE_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = OP_INTRFC_DM_RELSE_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = DATA_IO_LL2_BW_V_8;
  break;
  case 3:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = DATA_IO_RL2_BW_V_8;
  break;
  case 4:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = OP_INTRFC_DM_RELS_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_DM_RELSE_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_DM_RELSE_H_B_NAME = *FALSE;
OP_INTRFC_DM_RELS_MB_B_NAME = DATA_IO_DCS_BW_V_8;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = OP_INTRFC_DMSEL_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = DATA_IO_LL2_BW_V_9;
  break;
  case 3:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = DATA_IO_RL2_BW_V_9;
  break;
  case 4:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = OP_INTRFC_DMSEL_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_DM_SEL_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_DM_SELECT_B_NAME = OP_INTRFC_DM_SEL_B_MUX_N_1;
OP_INTRFC_DRYCRANK_B_NAME = OP_INTRFC_DRYCRNK_MX_B_MUX_N_1;
OP_INTRFC_DRYCRNKOFF_B_NAME = OP_INTRFC_DRYCRNK_OF_B_MUX_N_1;
OP_INTRFC_DRYCRNK_MB_B_NAME = DATA_IO_DCS_BW_V_5;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_5;
  break;
  case 3:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_5;
  break;
  case 4:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = OP_INTRFC_DRYCRNK_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_DRYCRNK_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = DATA_IO_LL2_BW_V_6;
  break;
  case 3:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = DATA_IO_RL2_BW_V_6;
  break;
  case 4:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = OP_INTRFC_D_CNKOFFMB_B_NAME;
  break;
  case 6:
    OP_INTRFC_DRYCRNK_OF_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_DSBLOLWCMB_B_NAME = DATA_IO_DCS_BW_V_10;
OP_INTRFC_D_CNKOFFMB_B_NAME = DATA_IO_DCS_BW_V_6;
OP_INTRFC_ENBONL_MB_B_NAME = DATA_IO_DCS_BW_V_11;
OP_INTRFC_OLWWOFF_H_B_NAME = FALSE;
OP_INTRFC_OLWWON_H_B_NAME = FALSE;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = OP_INTRFC_OLWWOFF_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = DATA_IO_LL2_BW_V_10;
  break;
  case 3:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = DATA_IO_RL2_BW_V_10;
  break;
  case 4:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = OP_INTRFC_DSBLOLWCMB_B_NAME;
  break;
  case 6:
    OP_INTRFC_OLWW_OFF_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = OP_INTRFC_OLWWON_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = DATA_IO_LL2_BW_V_11;
  break;
  case 3:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = DATA_IO_RL2_BW_V_11;
  break;
  case 4:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = OP_INTRFC_ENBONL_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_OLWW_ON_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_OL_WW_OFF_B_NAME = OP_INTRFC_OLWW_OFF_B_MUX_N_1;
OP_INTRFC_OL_WW_ON_B_NAME = OP_INTRFC_OLWW_ON_B_MUX_N_1;
OP_INTRFC_SP_90_H_B_NAME = FALSE;
