MLO_HOLD_Z_ZMINUS1_B = HYD_STRT_NOTSTART_NOT;
SFC_STEP_BACK_OP_OR = SFC_STEP_NORM_NS_AND || SFC_STEP_MNT_NSD_AND;
SFC_STEP_CNK_STPOR1_OR = FALSE || SFC_STEP_WWCRANK_0_TRAN_1 || SFC_STEP_WWCRANK_1_TRAN_1 || SFC_STEP_WWCRANK_2_TRAN_1 || SFC_STEP_WWCRANK_2_TRAN_1 || SFC_STEP_WWCRANK_3_TRAN_1 || SFC_STEP_WWCRANK_6_TRAN_1 || SFC_STEP_WWCRANK_7_TRAN_1 || SFC_STEP_WWCRANK_4_TRAN_1 || SFC_STEP_WWCRANK_5_TRAN_1 || SFC_STEP_WWCRANK_8_TRAN_1 || SFC_STEP_LOCRANK_1_TRAN_1 || SFC_STEP_WWCRANK_10_TRAN_1 || SFC_STEP_WWCRANK_11_TRAN_1 || SFC_STEP_CNK_STPOR2_OR || SFC_STEP_LOCRANK_2_TRAN_1 || SFC_STEP_LOCRANK_3_TRAN_1 || SFC_STEP_LOCRANK_4_TRAN_1 || SFC_STEP_HICRANK_1_TRAN_1 || SFC_STEP_HICRANK_2_TRAN_1 || SFC_STEP_HICRANK_3_TRAN_1 || SFC_STEP_HICRANK_4_TRAN_1;
SFC_STEP_CNK_STPOR2_OR = SFC_STEP_SEQ_TO_ESN_OR || SFC_STEP_MTR_TO_ESN_OR || SFC_STEP_NS_TO_ESN_OR || SFC_STEP_OUTOFOP_TRAN_1 || SFC_STEP_ES_1_TRAN_1 || SFC_STEP_STITOESN_TRAN_1 || SFC_STEP_SITOESNOR_OR;
SFC_STEP_CRANKING_OR = SFC_STEP_LOCRANK_1_SFC_STEP || SFC_STEP_LOCRANK_2_SFC_STEP || SFC_STEP_LOCRANK_3_SFC_STEP || SFC_STEP_LOCRANK_4_SFC_STEP || SFC_STEP_HICRANK_1_SFC_STEP || SFC_STEP_HICRANK_2_SFC_STEP || SFC_STEP_HICRANK_3_SFC_STEP || SFC_STEP_HICRANK_4_SFC_STEP || WTR_WASH_WW_ACTIVE_B_NAME;
if(SFC_STEP_CNK_STPOR1_OR) { 
	if( MLO_HOLD_Z_ZMINUS1_B) {
		SFC_STEP_CRANKSTOP_TRAN_1 = MLO_HOLD_Z_ZMINUS1_B;
	} else 
		SFC_STEP_CRANKSTOP_SFC_STEP= 1
} else {
  SFC_STEP_CRANKSTOP_ACTIVETIME= 0; 
  SFC_STEP_CRANKSTOP_SFC_STEP= 0; 
  SFC_STEP_CRANKSTOP_TRAN_1 = 0; 
}
SFC_STEP_CRNKSTPLTC_LATCH = LATCH_FUNCTION(1,GLUB_JCKPMPOFF_OR,SFC_STEP_CRANKSTOP_SFC_STEP,SFC_STEP_CRNKSTPLTC_LATCH);
if(SFC_STEP_CRANKSTOP_TRAN_1) { 
	if( SFC_STEP_BACK_OP_OR) {
		SFC_STEP_ESN_TRAN_1 = SFC_STEP_BACK_OP_OR;
	} else 
		SFC_STEP_ESN_SFC_STEP= 1
} else {
  SFC_STEP_ESN_ACTIVETIME= 0; 
  SFC_STEP_ESN_SFC_STEP= 0; 
  SFC_STEP_ESN_TRAN_1 = 0; 
}
if(SFC_STEP_OUTOFOP_TRAN_3) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_HICRANK_1_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( GLUB_ABORT_SFC_STEP) {
		SFC_STEP_HICRANK_1_TRAN_2 = GLUB_ABORT_SFC_STEP;
	} else if( GLUB_JCKPMPSTRT_LATCH) {
		SFC_STEP_HICRANK_1_TRAN_3 = GLUB_JCKPMPSTRT_LATCH;
	} else 
		SFC_STEP_HICRANK_1_SFC_STEP= 1
} else {
  SFC_STEP_HICRANK_1_ACTIVETIME= 0; 
  SFC_STEP_HICRANK_1_SFC_STEP= 0; 
  SFC_STEP_HICRANK_1_TRAN_1= 0; 
  SFC_STEP_HICRANK_1_TRAN_2= 0; 
  SFC_STEP_HICRANK_1_TRAN_3 = 0; 
}
if(SFC_STEP_HICRANK_1_TRAN_3) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_HICRANK_2_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( HYD_STRT_PUMPONDLY_DELAY) {
		SFC_STEP_HICRANK_2_TRAN_2 = HYD_STRT_PUMPONDLY_DELAY;
	} else 
		SFC_STEP_HICRANK_2_SFC_STEP= 1
} else {
  SFC_STEP_HICRANK_2_ACTIVETIME= 0; 
  SFC_STEP_HICRANK_2_SFC_STEP= 0; 
  SFC_STEP_HICRANK_2_TRAN_1= 0; 
  SFC_STEP_HICRANK_2_TRAN_2 = 0; 
}
if(SFC_STEP_HICRANK_2_TRAN_2) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_HICRANK_3_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( GLUB_MOT6031_B_NAME) {
		SFC_STEP_HICRANK_3_TRAN_2 = GLUB_MOT6031_B_NAME;
	} else 
		SFC_STEP_HICRANK_3_SFC_STEP= 1
} else {
  SFC_STEP_HICRANK_3_ACTIVETIME= 0; 
  SFC_STEP_HICRANK_3_SFC_STEP= 0; 
  SFC_STEP_HICRANK_3_TRAN_1= 0; 
  SFC_STEP_HICRANK_3_TRAN_2 = 0; 
}
if(SFC_STEP_HICRANK_3_TRAN_2) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_HICRANK_4_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( SFC_TIMER_HISPD_DN_B_NAME) {
		SFC_STEP_HICRANK_4_TRAN_2 = SFC_TIMER_HISPD_DN_B_NAME;
	} else 
		SFC_STEP_HICRANK_4_SFC_STEP= 1
} else {
  SFC_STEP_HICRANK_4_ACTIVETIME= 0; 
  SFC_STEP_HICRANK_4_SFC_STEP= 0; 
  SFC_STEP_HICRANK_4_TRAN_1= 0; 
  SFC_STEP_HICRANK_4_TRAN_2 = 0; 
}
if(SFC_STEP_OUTOFOP_TRAN_4) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_LOCRANK_1_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( GLUB_ABORT_SFC_STEP) {
		SFC_STEP_LOCRANK_1_TRAN_2 = GLUB_ABORT_SFC_STEP;
	} else if( GLUB_JCKPMPSTRT_LATCH) {
		SFC_STEP_LOCRANK_1_TRAN_3 = GLUB_JCKPMPSTRT_LATCH;
	} else 
		SFC_STEP_LOCRANK_1_SFC_STEP= 1
} else {
  SFC_STEP_LOCRANK_1_ACTIVETIME= 0; 
  SFC_STEP_LOCRANK_1_SFC_STEP= 0; 
  SFC_STEP_LOCRANK_1_TRAN_1= 0; 
  SFC_STEP_LOCRANK_1_TRAN_2= 0; 
  SFC_STEP_LOCRANK_1_TRAN_3 = 0; 
}
if(SFC_STEP_LOCRANK_1_TRAN_3) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_LOCRANK_2_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( HYD_STRT_PUMPONDLY_DELAY) {
		SFC_STEP_LOCRANK_2_TRAN_2 = HYD_STRT_PUMPONDLY_DELAY;
	} else 
		SFC_STEP_LOCRANK_2_SFC_STEP= 1
} else {
  SFC_STEP_LOCRANK_2_ACTIVETIME= 0; 
  SFC_STEP_LOCRANK_2_SFC_STEP= 0; 
  SFC_STEP_LOCRANK_2_TRAN_1= 0; 
  SFC_STEP_LOCRANK_2_TRAN_2 = 0; 
}
if(SFC_STEP_LOCRANK_2_TRAN_2) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_LOCRANK_3_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( GLUB_MOT6031_B_NAME) {
		SFC_STEP_LOCRANK_3_TRAN_2 = GLUB_MOT6031_B_NAME;
	} else 
		SFC_STEP_LOCRANK_3_SFC_STEP= 1
} else {
  SFC_STEP_LOCRANK_3_ACTIVETIME= 0; 
  SFC_STEP_LOCRANK_3_SFC_STEP= 0; 
  SFC_STEP_LOCRANK_3_TRAN_1= 0; 
  SFC_STEP_LOCRANK_3_TRAN_2 = 0; 
}
if(SFC_STEP_LOCRANK_3_TRAN_2) { 
	if( SFC_STEP_STPCNKOR_OR) {
		SFC_STEP_LOCRANK_4_TRAN_1 = SFC_STEP_STPCNKOR_OR;
	} else if( SFC_TIMER_LOSPD_DN_B_NAME) {
		SFC_STEP_LOCRANK_4_TRAN_2 = SFC_TIMER_LOSPD_DN_B_NAME;
	} else 
		SFC_STEP_LOCRANK_4_SFC_STEP= 1
} else {
  SFC_STEP_LOCRANK_4_ACTIVETIME= 0; 
  SFC_STEP_LOCRANK_4_SFC_STEP= 0; 
  SFC_STEP_LOCRANK_4_TRAN_1= 0; 
  SFC_STEP_LOCRANK_4_TRAN_2 = 0; 
}
SFC_STEP_MNT_NSD_AND = FALSE && SFC_STEP_NOT_SDN_NOT && SFC_STEP_NOT_NS_NOT;
SFC_STEP_NORM_NS_AND = SHUTDOWN_NO_SHTDNS_B_NAME && TRUE;
SFC_STEP_NOT_NS_NOT =! SFC_STEP_STPCNKOR_OR;
SFC_STEP_NOT_SDN_NOT =! SHUTDOWN_SDN_CORE_B_NAME;
SFC_STEP_OP_INI_NS_OR = SHUTDOWN_NS_LAT_SEL_1 || SHUTDOWN_NS_LAT_SEL_1;
SFC_STEP_STPCNKOR_OR = SFC_STEP_SD_COND_OR_OR || SFC_STEP_OP_INI_NS_OR;
