SPRINT_BACK_TO_LP_OR = SPRINT_LP_OFF_2_TRAN_2 || SPRINT_LP_OFF_3_TRAN_2 || SPRINT_LP_OFF_4_TRAN_2 || SPRINT_LP_OFF_5_TRAN_2 || SPRINT_HP_OFF_2_TRAN_2 || SPRINT_OFF_1_TRAN_2 || SPRINT_OFF_2_TRAN_2 || SPRINT_OFF_3_TRAN_2 || SPRINT_OFF_4_TRAN_2;
SPRINT_C_LPSPRTEN_B_NAME = IFACE_SPRINT_C_LPSPRTEN;
SPRINT_H2OXFRDONE_B_NAME = IFACE_SPRINT_H2OXFRDONE;
if(SPRINT_STRT_ESPRT_OR) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_2_LP_1_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_N_LPSPRTEN_NOT) {
		SPRINT_HP_2_LP_1_TRAN_2 = SPRINT_N_LPSPRTEN_NOT;
	} else if( SPRINT_H2OXFRDONE_B_NAME) {
		SPRINT_HP_2_LP_1_TRAN_3 = SPRINT_H2OXFRDONE_B_NAME;
	} else 
		SPRINT_HP_2_LP_1_SFC_STEP= 1
} else {
  SPRINT_HP_2_LP_1_ACTIVETIME= 0; 
  SPRINT_HP_2_LP_1_SFC_STEP= 0; 
  SPRINT_HP_2_LP_1_TRAN_1= 0; 
  SPRINT_HP_2_LP_1_TRAN_2= 0; 
  SPRINT_HP_2_LP_1_TRAN_3 = 0; 
}
if(SPRINT_HP_2_LP_1_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_2_LP_2_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_N_LPSPRTEN_NOT) {
		SPRINT_HP_2_LP_2_TRAN_2 = SPRINT_N_LPSPRTEN_NOT;
	} else if( SPRINT_DLY_HPHLD_DELAY) {
		SPRINT_HP_2_LP_2_TRAN_3 = SPRINT_DLY_HPHLD_DELAY;
	} else 
		SPRINT_HP_2_LP_2_SFC_STEP= 1
} else {
  SPRINT_HP_2_LP_2_ACTIVETIME= 0; 
  SPRINT_HP_2_LP_2_SFC_STEP= 0; 
  SPRINT_HP_2_LP_2_TRAN_1= 0; 
  SPRINT_HP_2_LP_2_TRAN_2= 0; 
  SPRINT_HP_2_LP_2_TRAN_3 = 0; 
}
if(SPRINT_HP_2_LP_2_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_2_LP_3_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_N_LPSPRTEN_NOT) {
		SPRINT_HP_2_LP_3_TRAN_2 = SPRINT_N_LPSPRTEN_NOT;
	} else if( SPRINT_DRAINHP_TM_DELAY) {
		SPRINT_HP_2_LP_3_TRAN_3 = SPRINT_DRAINHP_TM_DELAY;
	} else 
		SPRINT_HP_2_LP_3_SFC_STEP= 1
} else {
  SPRINT_HP_2_LP_3_ACTIVETIME= 0; 
  SPRINT_HP_2_LP_3_SFC_STEP= 0; 
  SPRINT_HP_2_LP_3_TRAN_1= 0; 
  SPRINT_HP_2_LP_3_TRAN_2= 0; 
  SPRINT_HP_2_LP_3_TRAN_3 = 0; 
}
if(SPRINT_SPRT_READY_TRAN_3 || SPRINT_BACK_TO_LP_OR || SPRINT_SPRT_READY_TRAN_5) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_ON_1_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_PSL_OK_B_NAME) {
		SPRINT_LP_ON_1_TRAN_2 = SPRINT_PSL_OK_B_NAME;
	} else 
		SPRINT_LP_ON_1_SFC_STEP= 1
} else {
  SPRINT_LP_ON_1_ACTIVETIME= 0; 
  SPRINT_LP_ON_1_SFC_STEP= 0; 
  SPRINT_LP_ON_1_TRAN_1= 0; 
  SPRINT_LP_ON_1_TRAN_2 = 0; 
}
if(SPRINT_LP_ON_1_TRAN_2 || SPRINT_HP_ON_2_TRAN_2) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_ON_2_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_N_LPSPRTEN_NOT) {
		SPRINT_LP_ON_2_TRAN_2 = SPRINT_N_LPSPRTEN_NOT;
	} else if( SPRINT_FILL_DN_OR) {
		SPRINT_LP_ON_2_TRAN_3 = SPRINT_FILL_DN_OR;
	} else 
		SPRINT_LP_ON_2_SFC_STEP= 1
} else {
  SPRINT_LP_ON_2_ACTIVETIME= 0; 
  SPRINT_LP_ON_2_SFC_STEP= 0; 
  SPRINT_LP_ON_2_TRAN_1= 0; 
  SPRINT_LP_ON_2_TRAN_2= 0; 
  SPRINT_LP_ON_2_TRAN_3 = 0; 
}
if(SPRINT_LP_ON_2_TRAN_3 || SPRINT_HP_2_LP_3_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_ON_3_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_N_LPSPRTEN_NOT) {
		SPRINT_LP_ON_3_TRAN_2 = SPRINT_N_LPSPRTEN_NOT;
	} else 
		SPRINT_LP_ON_3_SFC_STEP= 1
} else {
  SPRINT_LP_ON_3_ACTIVETIME= 0; 
  SPRINT_LP_ON_3_SFC_STEP= 0; 
  SPRINT_LP_ON_3_TRAN_1= 0; 
  SPRINT_LP_ON_3_TRAN_2 = 0; 
}
SPRINT_N_LPSPRTEN_NOT =! SPRINT_C_LPSPRTEN_B_NAME;
SPRINT_PSL_OK_B_NAME = *TRUE;
SPRINT_SEL_SPRAY_AND = SPRINT_C_LPSPRTEN_B_NAME && SPRINT_SPRINTENBL_B_NAME;
SPRINT_SEL_SPRINT_AND = SPRINT_N_LPSPRTEN_NOT && SPRINT_SPRINTENBL_B_NAME && SPRINT_HP_SPRNTOK_B_NAME;
if(SPRINT_NOTREADY_TRAN_1) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_SPRT_READY_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_SEL_SPRINT_AND) {
		SPRINT_SPRT_READY_TRAN_2 = SPRINT_SEL_SPRINT_AND;
	} else if( SPRINT_SEL_SPRAY_AND) {
		SPRINT_SPRT_READY_TRAN_3 = SPRINT_SEL_SPRAY_AND;
	} else if( SPRINT_SIM_SPRT_AND) {
		SPRINT_SPRT_READY_TRAN_4 = SPRINT_SIM_SPRT_AND;
	} else if( SPRINT_SIM_SPRAY_AND) {
		SPRINT_SPRT_READY_TRAN_5 = SPRINT_SIM_SPRAY_AND;
	} else 
		SPRINT_SPRT_READY_SFC_STEP= 1
} else {
  SPRINT_SPRT_READY_ACTIVETIME= 0; 
  SPRINT_SPRT_READY_SFC_STEP= 0; 
  SPRINT_SPRT_READY_TRAN_1= 0; 
  SPRINT_SPRT_READY_TRAN_2= 0; 
  SPRINT_SPRT_READY_TRAN_3= 0; 
  SPRINT_SPRT_READY_TRAN_4= 0; 
  SPRINT_SPRT_READY_TRAN_5 = 0; 
}
SPRINT_STRT_ESPRT_OR = SPRINT_LP_2_HP_1_TRAN_2 || SPRINT_LP_2_HP_2_TRAN_2 || SPRINT_LP_2_HP_3_TRAN_2 || SPRINT_LP_2_HP_4_TRAN_2 || SPRINT_LP_2_HP_5_TRAN_2 || SPRINT_HP_ON_3_TRAN_2 || SPRINT_LP_OFF_1_TRAN_2 || SPRINT_HP_OFF_1_TRAN_2;
SPRINT_TNK_VACSW_B_NAME = *FALSE;
SPRINT_TRANSOFF_AND = SPRINT_TRANS_OFF_OR && SPRINT_NOTTEST_NOT;
SPRINT_TRANS_OFF_OR = SPRINT_SDLATCHLP_ZMINUS1_B || CORE_DIGITAL_FUELOFF || SPRINT_SPRT_OFF_NOT || SPRINT_OFF_MASK_AND || SPRINT_TNK_VACSW_B_NAME || CORE_ALM_SPRT1_SPRSDALM1 || CORE_ALM_SPRT2_SPRSDALM2 || CORE_ALM_SPRT3_SPRSDALM3;
