I_GP1_GMVDPALM_B_NAME = I_GP1_GP1DP_OR;
I_GP1_GP1DP_OR = I_GP1I_GMVIDPALM_B_NAME || I_GP1O_GMVODPALM_B_NAME || I_GP1P_GMVPDPALM_B_NAME;
I_GP1_GP1HI_OR = I_GP1I_GP1IHIALM_B_NAME || I_GP1O_GP1OHIALM_B_NAME || I_GP1P_GP1PHIALM_B_NAME;
I_GP1_GP1HIALM_B_NAME = I_GP1_GP1HI_OR;
I_GP1_GP1LOW1_OR = I_GP1I_GP1ILOWALM_B_NAME || I_GP1O_GP1OLOWALM_B_NAME || I_GP1P_GP1PLOWALM_B_NAME;
I_GP1_GP1LOW2_OR = I_GP1I_GP1ILOWDM_B_NAME || I_GP1O_GP1OLOWDM_B_NAME || I_GP1P_GP1PLOWDM_B_NAME;
I_GP1_GP1LOWALM_B_NAME = I_GP1_GP1LOW1_OR;
I_GP1_GP1LOWDM_B_NAME = I_GP1_GP1LOW2_OR;
