R_NCAREG_NCAERR_A_NAME = R_NCAREG_NCAERRTMP_SUBTRACT;
R_NCAREG_NCAERRTMP_SUBTRACT = C_N25B_N25DOT_A_NAME - R_N25RAT_G_N25ACC_A_NAME;
R_NCAREG_NCAGN1_A_NAME = 1.519;
R_NCAREG_NCAPRX_A_NAME = R_NCAREG_NCAPRXTMP_PID_2;
R_NCAREG_NCAPRXTMP_PID_2 = PID_2_FUNCTION( 1 , 50 , 100 , 0 , 0 , 0 , 0 , 0 , 0.01 , R_ISSL_LSS_2_SEL_2 , R_ISSL_LSS_3_LSS_BUS , R_NCAREG_NCA_KP_CALCULATE , R_NCAREG_NCA_WB_DIVIDE , R_NCAREG_NCAERRTMP_SUBTRACT );
R_NCAREG_NCAWB_A_NAME = 0.05;
R_NCAREG_NCA_KP_CALCULATE =  ( (R_NCAREG_NCAGN1_A_NAME *R_NCAREG_NCAGN1_A_NAMEjm ) /R_WF36DMD_PPHTOPCT_A_NAME ) /     ( 1 +R_NCAREG_NCAWB_A_NAME ) ;
R_NCAREG_NCA_WB_DIVIDE = 0.01 / R_NCAREG_NCAWB_A_NAME;
