HMI_BO_BW_24_113L_OR = DATA_IO_LL2_BW_V_24 || DATA_IO_LL2_BW_V_113;
LOC_REM_PRTLOG__B_NAME = DATA_IO_DCS_BW_V_22;
LOC_REM_PRTLOG_H_B_NAME = FALSE;
LOC_REM_R_N25R_H_B_NAME = FALSE;
LOC_REM_R_N25R_MB_B_NAME = DATA_IO_DCS_BW_V_23;
LOC_REM_START_H_B_NAME = N3N41_BI_LOC_START_BI_L;
LOC_REM_START_MB_B_NAME = DATA_IO_DCS_BW_V_31;
LOC_REM_START_RH_B_NAME = N3N40_BI_REM_START_BI_L;
OP_INTRFC_BW_24_113R_OR = DATA_IO_RL2_BW_V_24 || DATA_IO_RL2_BW_V_113;
OP_INTRFC_DCS_STRTOR_OR = LOC_REM_START_MB_B_NAME || LOC_REM_START_RH_B_NAME;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = OP_INTRFC_SP_83_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_27;
  break;
  case 3:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_27;
  break;
  case 4:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = OP_INTRFC_SI_RELSEMB_B_NAME;
  break;
  case 6:
    OP_INTRFC_MANSTIR_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_MANSTI_RST_B_NAME = OP_INTRFC_MANSTIR_MX_B_MUX_N_1;
OP_INTRFC_MAN_ENDSBL_B_NAME = OP_INTRFC_MWENDS_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_28;
  break;
  case 3:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_28;
  break;
  case 4:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = OP_INTRFC_MW_ENBL_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_MWENDS_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_MW_ENBL_MB_B_NAME = DATA_IO_DCS_BW_V_28;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = LOC_REM_R_N25R_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_23;
  break;
  case 3:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_23;
  break;
  case 4:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = LOC_REM_R_N25R_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_N25RSE_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = LOC_REM_PRTLOG_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_22;
  break;
  case 3:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_22;
  break;
  case 4:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = LOC_REM_PRTLOG__B_NAME;
  break;
  case 6:
    OP_INTRFC_PLOG_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_PRINT_LOG_B_NAME = OP_INTRFC_PLOG_MX_B_MUX_N_1;
OP_INTRFC_RESET_B_NAME = OP_INTRFC_RESET_MX_B_MUX_N_1;
OP_INTRFC_RESET_MB_B_NAME = DATA_IO_DCS_BW_V_24;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = HMI_BO_BW_24_113L_OR;
  break;
  case 3:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = OP_INTRFC_BW_24_113R_OR;
  break;
  case 4:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = OP_INTRFC_RESET_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_RESET_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_RSEVLTS_H_B_NAME = DATA_IO_DCS_BW_V_25;
OP_INTRFC_RSEVLTS_MB_B_NAME = *FALSE;
OP_INTRFC_SI_RELSEMB_B_NAME = DATA_IO_DCS_BW_V_27;
OP_INTRFC_SPARE_26_B_NAME = OP_INTRFC_SPR26_MX_B_MUX_N_1;
OP_INTRFC_SPARE_E_B_NAME = FALSE;
OP_INTRFC_SPARE_MB_B_NAME = DATA_IO_DCS_BW_V_26;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = OP_INTRFC_SPARE_E_B_NAME;
  break;
  case 2:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_25;
  break;
  case 3:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_25;
  break;
  case 4:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = OP_INTRFC_SPARE_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_SPR26_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_SP_83_H_B_NAME = FALSE;
OP_INTRFC_SSAUT_H_B_NAME = FALSE;
OP_INTRFC_SSAUT_MB_B_NAME = DATA_IO_DCS_BW_V_29;
OP_INTRFC_SSMAN_H_B_NAME = FALSE;
OP_INTRFC_SSMAN_MB_B_NAME = DATA_IO_DCS_BW_V_30;
OP_INTRFC_START_B_NAME = OP_INTRFC_START_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_START_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_START_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_31;
  break;
  case 3:
    OP_INTRFC_START_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_31;
  break;
  case 4:
    OP_INTRFC_START_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_START_MX_B_MUX_N_1 = OP_INTRFC_DCS_STRTOR_OR;
  break;
  case 6:
    OP_INTRFC_START_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = OP_INTRFC_SSAUT_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_29;
  break;
  case 3:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_29;
  break;
  case 4:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = OP_INTRFC_SSAUT_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_STRAUTO_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = OP_INTRFC_SSMAN_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_30;
  break;
  case 3:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_30;
  break;
  case 4:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = OP_INTRFC_SSMAN_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_STRMAN_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_STR_SKDAUT_B_NAME = OP_INTRFC_STRAUTO_MX_B_MUX_N_1;
OP_INTRFC_STR_SKDMAN_B_NAME = OP_INTRFC_STRMAN_MX_B_MUX_N_1;
OP_INTRFC_VOLT_RSE_B_NAME = OP_INTRFC_VRSE_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = OP_INTRFC_RSEVLTS_MB_B_NAME;
  break;
  case 2:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_25;
  break;
  case 3:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_25;
  break;
  case 4:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = OP_INTRFC_RSEVLTS_H_B_NAME;
  break;
  case 6:
    OP_INTRFC_VRSE_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_XN25RSE_B_NAME = OP_INTRFC_N25RSE_MX_B_MUX_N_1;
