SPRINT_ACTIVE_OR = SPRINT_SPRT_READY_SFC_STEP || SPRINT_HP_ON_3_SFC_STEP || SPRINT_LP_2_HP_1_SFC_STEP || SPRINT_LP_2_HP_2_SFC_STEP || SPRINT_LP_2_HP_3_SFC_STEP || SPRINT_LP_2_HP_4_SFC_STEP || SPRINT_LP_2_HP_5_SFC_STEP || SPRINT_LP_ON_1_SFC_STEP || SPRINT_LP_ON_2_SFC_STEP || SPRINT_LP_ON_3_SFC_STEP || SPRINT_HP_2_LP_1_SFC_STEP || SPRINT_HP_2_LP_2_SFC_STEP || SPRINT_HP_2_LP_3_SFC_STEP || SPRINT_HP_ON_1_SFC_STEP || SPRINT_HP_ON_2_SFC_STEP;
SPRINT_BACK_TO_HP_OR = SPRINT_LP_OFF_2_TRAN_1 || SPRINT_LP_OFF_3_TRAN_1 || SPRINT_LP_OFF_4_TRAN_1 || SPRINT_LP_OFF_5_TRAN_1 || SPRINT_HP_OFF_2_TRAN_1 || SPRINT_OFF_1_TRAN_1 || SPRINT_OFF_2_TRAN_1 || SPRINT_OFF_3_TRAN_1 || SPRINT_OFF_4_TRAN_1;
SPRINT_EVAC_SW1_B_SW = B_SW_FUNCTION( SPRINT_JIMMY_SPRT_B_NAME , TRUE , SPRINT_EVAC_TMR_DELAY );
if(SPRINT_SPRT_READY_TRAN_2 || SPRINT_SPRT_READY_TRAN_4 || SPRINT_BACK_TO_HP_OR || SPRINT_BACK_TO_HP_OR) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_ON_1_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_PSL_OK_B_NAME) {
		SPRINT_HP_ON_1_TRAN_2 = SPRINT_PSL_OK_B_NAME;
	} else 
		SPRINT_HP_ON_1_SFC_STEP= 1
} else {
  SPRINT_HP_ON_1_ACTIVETIME= 0; 
  SPRINT_HP_ON_1_SFC_STEP= 0; 
  SPRINT_HP_ON_1_TRAN_1= 0; 
  SPRINT_HP_ON_1_TRAN_2 = 0; 
}
if(SPRINT_HP_ON_1_TRAN_2 || SPRINT_LP_ON_2_TRAN_2) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_ON_2_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_HP_ON_2_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_FILL_DN_OR) {
		SPRINT_HP_ON_2_TRAN_3 = SPRINT_FILL_DN_OR;
	} else 
		SPRINT_HP_ON_2_SFC_STEP= 1
} else {
  SPRINT_HP_ON_2_ACTIVETIME= 0; 
  SPRINT_HP_ON_2_SFC_STEP= 0; 
  SPRINT_HP_ON_2_TRAN_1= 0; 
  SPRINT_HP_ON_2_TRAN_2= 0; 
  SPRINT_HP_ON_2_TRAN_3 = 0; 
}
if(SPRINT_HP_ON_2_TRAN_3 || SPRINT_LP_2_HP_5_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_HP_ON_3_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_HP_ON_3_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else 
		SPRINT_HP_ON_3_SFC_STEP= 1
} else {
  SPRINT_HP_ON_3_ACTIVETIME= 0; 
  SPRINT_HP_ON_3_SFC_STEP= 0; 
  SPRINT_HP_ON_3_TRAN_1= 0; 
  SPRINT_HP_ON_3_TRAN_2 = 0; 
}
SPRINT_HP_SPRNTOK_B_NAME = *FALSE;
if(SPRINT_STRT_SPRT_OR) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_2_HP_1_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_LP_2_HP_1_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_H2OXFRDONE_B_NAME) {
		SPRINT_LP_2_HP_1_TRAN_3 = SPRINT_H2OXFRDONE_B_NAME;
	} else 
		SPRINT_LP_2_HP_1_SFC_STEP= 1
} else {
  SPRINT_LP_2_HP_1_ACTIVETIME= 0; 
  SPRINT_LP_2_HP_1_SFC_STEP= 0; 
  SPRINT_LP_2_HP_1_TRAN_1= 0; 
  SPRINT_LP_2_HP_1_TRAN_2= 0; 
  SPRINT_LP_2_HP_1_TRAN_3 = 0; 
}
if(SPRINT_LP_2_HP_1_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_2_HP_2_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_LP_2_HP_2_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_DLY_LPEHLD_DELAY) {
		SPRINT_LP_2_HP_2_TRAN_3 = SPRINT_DLY_LPEHLD_DELAY;
	} else 
		SPRINT_LP_2_HP_2_SFC_STEP= 1
} else {
  SPRINT_LP_2_HP_2_ACTIVETIME= 0; 
  SPRINT_LP_2_HP_2_SFC_STEP= 0; 
  SPRINT_LP_2_HP_2_TRAN_1= 0; 
  SPRINT_LP_2_HP_2_TRAN_2= 0; 
  SPRINT_LP_2_HP_2_TRAN_3 = 0; 
}
if(SPRINT_LP_2_HP_2_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_2_HP_3_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_LP_2_HP_3_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_EVAC_SW1_B_SW) {
		SPRINT_LP_2_HP_3_TRAN_3 = SPRINT_EVAC_SW1_B_SW;
	} else 
		SPRINT_LP_2_HP_3_SFC_STEP= 1
} else {
  SPRINT_LP_2_HP_3_ACTIVETIME= 0; 
  SPRINT_LP_2_HP_3_SFC_STEP= 0; 
  SPRINT_LP_2_HP_3_TRAN_1= 0; 
  SPRINT_LP_2_HP_3_TRAN_2= 0; 
  SPRINT_LP_2_HP_3_TRAN_3 = 0; 
}
if(SPRINT_LP_2_HP_3_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_2_HP_4_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_LP_2_HP_4_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_DLY_LPPHLD_DELAY) {
		SPRINT_LP_2_HP_4_TRAN_3 = SPRINT_DLY_LPPHLD_DELAY;
	} else 
		SPRINT_LP_2_HP_4_SFC_STEP= 1
} else {
  SPRINT_LP_2_HP_4_ACTIVETIME= 0; 
  SPRINT_LP_2_HP_4_SFC_STEP= 0; 
  SPRINT_LP_2_HP_4_TRAN_1= 0; 
  SPRINT_LP_2_HP_4_TRAN_2= 0; 
  SPRINT_LP_2_HP_4_TRAN_3 = 0; 
}
if(SPRINT_LP_2_HP_4_TRAN_3) { 
	if( SPRINT_TRANSOFF_AND) {
		SPRINT_LP_2_HP_5_TRAN_1 = SPRINT_TRANSOFF_AND;
	} else if( SPRINT_C_LPSPRTEN_B_NAME) {
		SPRINT_LP_2_HP_5_TRAN_2 = SPRINT_C_LPSPRTEN_B_NAME;
	} else if( SPRINT_LP_PRG_TMR_DELAY) {
		SPRINT_LP_2_HP_5_TRAN_3 = SPRINT_LP_PRG_TMR_DELAY;
	} else 
		SPRINT_LP_2_HP_5_SFC_STEP= 1
} else {
  SPRINT_LP_2_HP_5_ACTIVETIME= 0; 
  SPRINT_LP_2_HP_5_SFC_STEP= 0; 
  SPRINT_LP_2_HP_5_TRAN_1= 0; 
  SPRINT_LP_2_HP_5_TRAN_2= 0; 
  SPRINT_LP_2_HP_5_TRAN_3 = 0; 
}
SPRINT_NO_HPSPRNT_NOT =! SPRINT_HP_SPRNTOK_B_NAME;
SPRINT_OFF_MASK_AND = SPRINT_N_LPSPRTEN_NOT && SPRINT_NO_HPSPRNT_NOT;
SPRINT_STRT_SPRT_OR = SPRINT_LP_ON_3_TRAN_2 || SPRINT_HP_2_LP_1_TRAN_2 || SPRINT_HP_2_LP_2_TRAN_2 || SPRINT_HP_2_LP_3_TRAN_2 || SPRINT_LP_OFF_1_TRAN_1 || SPRINT_HP_OFF_1_TRAN_1;
