B_BDBURNES_B_FAR4_DIVIDE = B_BDCOMPES_B_WA36_A_NAME / F_BURNERES_F_WFC_A_NAME;
B_BDBURNES_B_H4_A_NAME = B_BDBURNES_B_H4TMP_CALCULATE;
B_BDBURNES_B_H4TMP_CALCULATE =  (B_BODINPUT_B_H3_A_NAME + (19000 * 0.995 + 283.575 ) *    b_far4 ) / ( 1.0 +B_BDBURNES_B_FAR4_DIVIDE ) ;
B_BDBURNES_B_P4_A_NAME = B_BDBURNES_B_P4TMP_CALCULATE;
B_BDBURNES_B_P4TMP_CALCULATE = b_p3 - ( 0.000133244 *B_BDCOMPES_B_WA36_A_NAME *B_BDCOMPES_B_WA36_A_NAME *B_BODINPUT_B_T3_A_NAME ) /    b_p3;
B_BDBURNES_B_W4_A_NAME = B_BDBURNES_B_W4TMP_CALCULATE;
B_BDBURNES_B_W4TMP_CALCULATE = b_wa36 * ( 1.0 +B_BDBURNES_B_FAR4_DIVIDE +F_CMPBLDES_F_WAR36_A_NAME ) ;
