CDP_CAL_AVERAGE_CALCULATE =  (-20.0 )  -  (  (CDP_CAL_AVG1_A_OUT_7 +CDP_CAL_AVG2_A_OUT_7 +CDP_CAL_AVG3_A_OUT_7 +CDP_CAL_AVG4_A_OUT_7 +CDP_CAL_AVG5_A_OUT_7 )  / 5 ) ;
if (CDP_CAL_MIN_AND== TRUE){   CDP_CAL_AVG1_A_OUT_6 = CDP_CAL_AVG1_A_OUT_5;   CDP_CAL_AVG1_A_OUT_5 = CDP_CAL_AVG1_A_OUT_4;   CDP_CAL_AVG1_A_OUT_4 = CDP_CAL_AVG1_A_OUT_3;   CDP_CAL_AVG1_A_OUT_3 = CDP_CAL_AVG1_A_OUT_2;   CDP_CAL_AVG1_A_OUT_2 = CDP_CAL_AVG1_A_OUT_1;   CDP_CAL_AVG1_A_OUT_1 = CDP_CAL_CURRENT_A_NAME;   CDP_CAL_AVG1_A_OUT_7 = (CDP_CAL_AVG1_A_OUT_1+CDP_CAL_AVG1_A_OUT_2+CDP_CAL_AVG1_A_OUT_3+   CDP_CAL_AVG1_A_OUT_4+CDP_CAL_AVG1_A_OUT_5+CDP_CAL_AVG1_A_OUT_6)/6;}   else {   CDP_CAL_AVG1_A_OUT_6 = CDP_CAL_AVG1_A_OUT_6;   CDP_CAL_AVG1_A_OUT_5 = CDP_CAL_AVG1_A_OUT_5;   CDP_CAL_AVG1_A_OUT_4 = CDP_CAL_AVG1_A_OUT_4;   CDP_CAL_AVG1_A_OUT_3 = CDP_CAL_AVG1_A_OUT_3;   CDP_CAL_AVG1_A_OUT_2 = CDP_CAL_AVG1_A_OUT_2;   CDP_CAL_AVG1_A_OUT_1 = CDP_CAL_AVG1_A_OUT_1;   CDP_CAL_AVG1_A_OUT_7 = CDP_CAL_AVG1_A_OUT_7;};
if (CDP_CAL_LO_MID_AND== TRUE){   CDP_CAL_AVG2_A_OUT_6 = CDP_CAL_AVG2_A_OUT_5;   CDP_CAL_AVG2_A_OUT_5 = CDP_CAL_AVG2_A_OUT_4;   CDP_CAL_AVG2_A_OUT_4 = CDP_CAL_AVG2_A_OUT_3;   CDP_CAL_AVG2_A_OUT_3 = CDP_CAL_AVG2_A_OUT_2;   CDP_CAL_AVG2_A_OUT_2 = CDP_CAL_AVG2_A_OUT_1;   CDP_CAL_AVG2_A_OUT_1 = CDP_CAL_CURRENT_A_NAME;   CDP_CAL_AVG2_A_OUT_7 = (CDP_CAL_AVG2_A_OUT_1+CDP_CAL_AVG2_A_OUT_2+CDP_CAL_AVG2_A_OUT_3+   CDP_CAL_AVG2_A_OUT_4+CDP_CAL_AVG2_A_OUT_5+CDP_CAL_AVG2_A_OUT_6)/6;}   else {   CDP_CAL_AVG2_A_OUT_6 = CDP_CAL_AVG2_A_OUT_6;   CDP_CAL_AVG2_A_OUT_5 = CDP_CAL_AVG2_A_OUT_5;   CDP_CAL_AVG2_A_OUT_4 = CDP_CAL_AVG2_A_OUT_4;   CDP_CAL_AVG2_A_OUT_3 = CDP_CAL_AVG2_A_OUT_3;   CDP_CAL_AVG2_A_OUT_2 = CDP_CAL_AVG2_A_OUT_2;   CDP_CAL_AVG2_A_OUT_1 = CDP_CAL_AVG2_A_OUT_1;   CDP_CAL_AVG2_A_OUT_7 = CDP_CAL_AVG2_A_OUT_7;};
if (CDP_CAL_MID_AND== TRUE){   CDP_CAL_AVG3_A_OUT_6 = CDP_CAL_AVG3_A_OUT_5;   CDP_CAL_AVG3_A_OUT_5 = CDP_CAL_AVG3_A_OUT_4;   CDP_CAL_AVG3_A_OUT_4 = CDP_CAL_AVG3_A_OUT_3;   CDP_CAL_AVG3_A_OUT_3 = CDP_CAL_AVG3_A_OUT_2;   CDP_CAL_AVG3_A_OUT_2 = CDP_CAL_AVG3_A_OUT_1;   CDP_CAL_AVG3_A_OUT_1 = CDP_CAL_CURRENT_A_NAME;   CDP_CAL_AVG3_A_OUT_7 = (CDP_CAL_AVG3_A_OUT_1+CDP_CAL_AVG3_A_OUT_2+CDP_CAL_AVG3_A_OUT_3+   CDP_CAL_AVG3_A_OUT_4+CDP_CAL_AVG3_A_OUT_5+CDP_CAL_AVG3_A_OUT_6)/6;}   else {   CDP_CAL_AVG3_A_OUT_6 = CDP_CAL_AVG3_A_OUT_6;   CDP_CAL_AVG3_A_OUT_5 = CDP_CAL_AVG3_A_OUT_5;   CDP_CAL_AVG3_A_OUT_4 = CDP_CAL_AVG3_A_OUT_4;   CDP_CAL_AVG3_A_OUT_3 = CDP_CAL_AVG3_A_OUT_3;   CDP_CAL_AVG3_A_OUT_2 = CDP_CAL_AVG3_A_OUT_2;   CDP_CAL_AVG3_A_OUT_1 = CDP_CAL_AVG3_A_OUT_1;   CDP_CAL_AVG3_A_OUT_7 = CDP_CAL_AVG3_A_OUT_7;};
if (CDP_CAL_HI_MID_AND== TRUE){   CDP_CAL_AVG4_A_OUT_6 = CDP_CAL_AVG4_A_OUT_5;   CDP_CAL_AVG4_A_OUT_5 = CDP_CAL_AVG4_A_OUT_4;   CDP_CAL_AVG4_A_OUT_4 = CDP_CAL_AVG4_A_OUT_3;   CDP_CAL_AVG4_A_OUT_3 = CDP_CAL_AVG4_A_OUT_2;   CDP_CAL_AVG4_A_OUT_2 = CDP_CAL_AVG4_A_OUT_1;   CDP_CAL_AVG4_A_OUT_1 = CDP_CAL_CURRENT_A_NAME;   CDP_CAL_AVG4_A_OUT_7 = (CDP_CAL_AVG4_A_OUT_1+CDP_CAL_AVG4_A_OUT_2+CDP_CAL_AVG4_A_OUT_3+   CDP_CAL_AVG4_A_OUT_4+CDP_CAL_AVG4_A_OUT_5+CDP_CAL_AVG4_A_OUT_6)/6;}   else {   CDP_CAL_AVG4_A_OUT_6 = CDP_CAL_AVG4_A_OUT_6;   CDP_CAL_AVG4_A_OUT_5 = CDP_CAL_AVG4_A_OUT_5;   CDP_CAL_AVG4_A_OUT_4 = CDP_CAL_AVG4_A_OUT_4;   CDP_CAL_AVG4_A_OUT_3 = CDP_CAL_AVG4_A_OUT_3;   CDP_CAL_AVG4_A_OUT_2 = CDP_CAL_AVG4_A_OUT_2;   CDP_CAL_AVG4_A_OUT_1 = CDP_CAL_AVG4_A_OUT_1;   CDP_CAL_AVG4_A_OUT_7 = CDP_CAL_AVG4_A_OUT_7;};
if (CDP_CAL_MAX_AND== TRUE){   CDP_CAL_AVG5_A_OUT_6 = CDP_CAL_AVG5_A_OUT_5;   CDP_CAL_AVG5_A_OUT_5 = CDP_CAL_AVG5_A_OUT_4;   CDP_CAL_AVG5_A_OUT_4 = CDP_CAL_AVG5_A_OUT_3;   CDP_CAL_AVG5_A_OUT_3 = CDP_CAL_AVG5_A_OUT_2;   CDP_CAL_AVG5_A_OUT_2 = CDP_CAL_AVG5_A_OUT_1;   CDP_CAL_AVG5_A_OUT_1 = CDP_CAL_CURRENT_A_NAME;   CDP_CAL_AVG5_A_OUT_7 = (CDP_CAL_AVG5_A_OUT_1+CDP_CAL_AVG5_A_OUT_2+CDP_CAL_AVG5_A_OUT_3+   CDP_CAL_AVG5_A_OUT_4+CDP_CAL_AVG5_A_OUT_5+CDP_CAL_AVG5_A_OUT_6)/6;}   else {   CDP_CAL_AVG5_A_OUT_6 = CDP_CAL_AVG5_A_OUT_6;   CDP_CAL_AVG5_A_OUT_5 = CDP_CAL_AVG5_A_OUT_5;   CDP_CAL_AVG5_A_OUT_4 = CDP_CAL_AVG5_A_OUT_4;   CDP_CAL_AVG5_A_OUT_3 = CDP_CAL_AVG5_A_OUT_3;   CDP_CAL_AVG5_A_OUT_2 = CDP_CAL_AVG5_A_OUT_2;   CDP_CAL_AVG5_A_OUT_1 = CDP_CAL_AVG5_A_OUT_1;   CDP_CAL_AVG5_A_OUT_7 = CDP_CAL_AVG5_A_OUT_7;};
CDP_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 1 , CDP_CAL_AVERAGE_CALCULATE );
if(CDP_CAL_CAL_09_TRAN_3 || CDP_CAL_CAL_00_TRAN_2) { 
	if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_10_TRAN_1 = CDP_CAL_PUNCH_OR_OR;
	} else if( CDP_CAL_DLY_TRAN_1_DELAY) {
		CDP_CAL_CAL_10_TRAN_2 = CDP_CAL_DLY_TRAN_1_DELAY;
	} else 
		CDP_CAL_CAL_10_SFC_STEP= 1
} else {
  CDP_CAL_CAL_10_ACTIVETIME= 0; 
  CDP_CAL_CAL_10_SFC_STEP= 0; 
  CDP_CAL_CAL_10_TRAN_1= 0; 
  CDP_CAL_CAL_10_TRAN_2 = 0; 
}
if(CDP_CAL_CAL_10_TRAN_2) { 
	if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_11_TRAN_1 = CDP_CAL_PUNCH_OR_OR;
	} else if( CDP_CAL_DLY_TRAN_2_DELAY) {
		CDP_CAL_CAL_11_TRAN_2 = CDP_CAL_DLY_TRAN_2_DELAY;
	} else 
		CDP_CAL_CAL_11_SFC_STEP= 1
} else {
  CDP_CAL_CAL_11_ACTIVETIME= 0; 
  CDP_CAL_CAL_11_SFC_STEP= 0; 
  CDP_CAL_CAL_11_TRAN_1= 0; 
  CDP_CAL_CAL_11_TRAN_2 = 0; 
}
if(CDP_CAL_CAL_11_TRAN_2) { 
	if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_12_TRAN_1 = CDP_CAL_PUNCH_OR_OR;
	} else if( CDP_CAL_DLY_TRAN_3_DELAY) {
		CDP_CAL_CAL_12_TRAN_2 = CDP_CAL_DLY_TRAN_3_DELAY;
	} else 
		CDP_CAL_CAL_12_SFC_STEP= 1
} else {
  CDP_CAL_CAL_12_ACTIVETIME= 0; 
  CDP_CAL_CAL_12_SFC_STEP= 0; 
  CDP_CAL_CAL_12_TRAN_1= 0; 
  CDP_CAL_CAL_12_TRAN_2 = 0; 
}
if(CDP_CAL_CAL_12_TRAN_2) { 
	if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_13_TRAN_1 = CDP_CAL_PUNCH_OR_OR;
	} else if( CDP_CAL_DLY_TRAN_4_DELAY) {
		CDP_CAL_CAL_13_TRAN_2 = CDP_CAL_DLY_TRAN_4_DELAY;
	} else 
		CDP_CAL_CAL_13_SFC_STEP= 1
} else {
  CDP_CAL_CAL_13_ACTIVETIME= 0; 
  CDP_CAL_CAL_13_SFC_STEP= 0; 
  CDP_CAL_CAL_13_TRAN_1= 0; 
  CDP_CAL_CAL_13_TRAN_2 = 0; 
}
if(CDP_CAL_CAL_13_TRAN_2) { 
	if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_14_TRAN_1 = CDP_CAL_PUNCH_OR_OR;
	} else if( CDP_CAL_DLY_TRAN_5_DELAY) {
		CDP_CAL_CAL_14_TRAN_2 = CDP_CAL_DLY_TRAN_5_DELAY;
	} else 
		CDP_CAL_CAL_14_SFC_STEP= 1
} else {
  CDP_CAL_CAL_14_ACTIVETIME= 0; 
  CDP_CAL_CAL_14_SFC_STEP= 0; 
  CDP_CAL_CAL_14_TRAN_1= 0; 
  CDP_CAL_CAL_14_TRAN_2 = 0; 
}
  bool CDP_CAL_CAL_14_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , CDP_CAL_CAL_15_SFC_STEP,&CDP_CAL_CAL_14_OS_ONE_SHOT,&CDP_CAL_CAL_14_OS_R_TIME,&CDP_CAL_CAL_14_OS_LAST_TRIGGER);
if(CDP_CAL_CAL_14_TRAN_2) { 
	if( CDP_CAL_CAL_14_OS_ONE_SHOT) {
		CDP_CAL_CAL_15_TRAN_1 = CDP_CAL_CAL_14_OS_ONE_SHOT;
	} else 
		CDP_CAL_CAL_15_SFC_STEP= 1
} else {
  CDP_CAL_CAL_15_ACTIVETIME= 0; 
  CDP_CAL_CAL_15_SFC_STEP= 0; 
  CDP_CAL_CAL_15_TRAN_1 = 0; 
}
if(CDP_CAL_CAL_00_TRAN_1) { 
	if( CDP_CAL_NOTSTROKE_NOT) {
		CDP_CAL_CAL_16_TRAN_1 = CDP_CAL_NOTSTROKE_NOT;
	} else if( CDP_CAL_PUNCH_OR_OR) {
		CDP_CAL_CAL_16_TRAN_2 = CDP_CAL_PUNCH_OR_OR;
	} else 
		CDP_CAL_CAL_16_SFC_STEP= 1
} else {
  CDP_CAL_CAL_16_ACTIVETIME= 0; 
  CDP_CAL_CAL_16_SFC_STEP= 0; 
  CDP_CAL_CAL_16_TRAN_1= 0; 
  CDP_CAL_CAL_16_TRAN_2 = 0; 
}
DELAY_FUNCTION(1 , 5 , 0 , CDP_CAL_DMDVSFDBK_B_OUT_1,&CDP_CAL_DLY_DFCMP_DELAY,&CDP_CAL_DLY_DFCMP_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , CDP_CAL_TRAN_1_AND,&CDP_CAL_DLY_TRAN_1_DELAY,&CDP_CAL_DLY_TRAN_1_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , CDP_CAL_TRAN_2_AND,&CDP_CAL_DLY_TRAN_2_DELAY,&CDP_CAL_DLY_TRAN_2_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , CDP_CAL_TRAN_3_AND,&CDP_CAL_DLY_TRAN_3_DELAY,&CDP_CAL_DLY_TRAN_3_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , CDP_CAL_TRAN_4_AND,&CDP_CAL_DLY_TRAN_4_DELAY,&CDP_CAL_DLY_TRAN_4_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , CDP_CAL_TRAN_5_AND,&CDP_CAL_DLY_TRAN_5_DELAY,&CDP_CAL_DLY_TRAN_5_R_TIME);
if (fabs(CDP_CAL_DEMAND_A_NAME-CDP_CAL_AVG_POS_A_NAME) < CDP_CAL_ERROR_A_NAME)   { CDP_CAL_DMDVSFDBK_B_OUT_1 = true; }   else   { CDP_CAL_DMDVSFDBK_B_OUT_1 = false; };
CDP_CAL_HI_MID_AND = CDP_CAL_CAL_13_SFC_STEP && CDP_CAL_I_CNT_ONE_DELAY && CDP_CAL_DLY_DFCMP_DELAY;
CDP_CAL_I_CNT_NOT =! CDP_CAL_I_CNT_ONE_DELAY;
CDP_CAL_I_CNTPV_ZMINUS1_B = CDP_CAL_I_CNT_NOT;
DELAY_FUNCTION(1 , 0.32 , 0 , CDP_CAL_I_CNTPV_ZMINUS1_B,&CDP_CAL_I_CNT_ONE_DELAY,&CDP_CAL_I_CNT_ONE_R_TIME);
CDP_CAL_LO_MID_AND = CDP_CAL_CAL_11_SFC_STEP && CDP_CAL_I_CNT_ONE_DELAY && CDP_CAL_DLY_DFCMP_DELAY;
CDP_CAL_MAX_AND = CDP_CAL_CAL_14_SFC_STEP && CDP_CAL_I_CNT_ONE_DELAY && CDP_CAL_DLY_DFCMP_DELAY;
CDP_CAL_MID_AND = CDP_CAL_CAL_12_SFC_STEP && CDP_CAL_I_CNT_ONE_DELAY && CDP_CAL_DLY_DFCMP_DELAY;
CDP_CAL_MIN_AND = CDP_CAL_CAL_10_SFC_STEP && CDP_CAL_I_CNT_ONE_DELAY && CDP_CAL_DLY_DFCMP_DELAY;
CDP_CAL_NOTSTROKE_NOT =! CDP_CAL_CALMODE_B_NAME;
CDP_CAL_NULJA_A_NAME = CDP_CAL_NULLBIAS_NO;
A_SW_REV_FUNCTION(CDP_CAL_CAL_14_OS_ONE_SHOT , CDP_CAL_NULLBIAS_NC , CDP_CAL_AVG_NEGATE_NEGATE,&CDP_CAL_NULLBIAS_NC,&CDP_CAL_NULLBIAS_NO);
CDP_CAL_TRAN_1_AND = CDP_CAL_DLY_DFCMP_DELAY && CDP_CAL_CAL_10_SFC_STEP;
CDP_CAL_TRAN_2_AND = CDP_CAL_DLY_DFCMP_DELAY && CDP_CAL_CAL_11_SFC_STEP;
CDP_CAL_TRAN_3_AND = CDP_CAL_DLY_DFCMP_DELAY && CDP_CAL_CAL_12_SFC_STEP;
CDP_CAL_TRAN_4_AND = CDP_CAL_DLY_DFCMP_DELAY && CDP_CAL_CAL_13_SFC_STEP;
CDP_CAL_TRAN_5_AND = CDP_CAL_DLY_DFCMP_DELAY && CDP_CAL_CAL_14_SFC_STEP;
