IGV_CAL_AVERAGE_CALCULATE = CALCULATE_FUNCTION( 0 , 0 , IGV_CAL_AVG1_A_OUT_7 , in1 , IGV_CAL_AVG2_A_OUT_7 , in2 , IGV_CAL_AVG3_A_OUT_7 , in3 , IGV_CAL_AVG4_A_OUT_7 , in4 , IGV_CAL_AVG5_A_OUT_7 , in5 , 20_0 , null , (null)-((in1+in2+in3+in4+in5)/5) );
IGV_CAL_AVG1_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , IGV_CAL_AVG1_A_OUT_1 , in1 , IGV_CAL_AVG1_A_OUT_2 , in2 , IGV_CAL_AVG1_A_OUT_3 , in3 , IGV_CAL_AVG1_A_OUT_4 , in4 , IGV_CAL_AVG1_A_OUT_5 , in5 , IGV_CAL_AVG1_A_OUT_6 , in6 , IGV_CAL_AVG1_A_OUT_7 , pvavg , IGV_CAL_CURRENT_A_NAME , xin , 1 , I_in , IGV_CAL_MIN_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
IGV_CAL_AVG2_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , IGV_CAL_AVG2_A_OUT_1 , in1 , IGV_CAL_AVG2_A_OUT_2 , in2 , IGV_CAL_AVG2_A_OUT_3 , in3 , IGV_CAL_AVG2_A_OUT_4 , in4 , IGV_CAL_AVG2_A_OUT_5 , in5 , IGV_CAL_AVG2_A_OUT_6 , in6 , IGV_CAL_AVG2_A_OUT_7 , pvavg , IGV_CAL_CURRENT_A_NAME , xin , 1 , I_in , IGV_CAL_LO_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
IGV_CAL_AVG3_CALC_PLUS = CALC_PLUS_FUNCTION( IGV_CAL_AVG3_A_OUT_5 , in5 , IGV_CAL_AVG3_A_OUT_6 , in6 , IGV_CAL_AVG3_A_OUT_7 , pvavg , IGV_CAL_CURRENT_A_NAME , xin , 1 , I_in , IGV_CAL_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} , 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , IGV_CAL_AVG3_A_OUT_1 , in1 , IGV_CAL_AVG3_A_OUT_2 , in2 , IGV_CAL_AVG3_A_OUT_3 , in3 , IGV_CAL_AVG3_A_OUT_4 , in4 );
IGV_CAL_AVG4_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , IGV_CAL_AVG4_A_OUT_1 , in1 , IGV_CAL_AVG4_A_OUT_2 , in2 , IGV_CAL_AVG4_A_OUT_3 , in3 , IGV_CAL_AVG4_A_OUT_4 , in4 , IGV_CAL_AVG4_A_OUT_5 , in5 , IGV_CAL_AVG4_A_OUT_6 , in6 , IGV_CAL_AVG4_A_OUT_7 , pvavg , IGV_CAL_CURRENT_A_NAME , xin , 1 , I_in , IGV_CAL_HI_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
IGV_CAL_AVG5_CALC_PLUS = CALC_PLUS_FUNCTION( I_in , IGV_CAL_MAX_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} , 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , IGV_CAL_AVG5_A_OUT_1 , in1 , IGV_CAL_AVG5_A_OUT_2 , in2 , IGV_CAL_AVG5_A_OUT_3 , in3 , IGV_CAL_AVG5_A_OUT_4 , in4 , IGV_CAL_AVG5_A_OUT_5 , in5 , IGV_CAL_AVG5_A_OUT_6 , in6 , IGV_CAL_AVG5_A_OUT_7 , pvavg , IGV_CAL_CURRENT_A_NAME , xin , 1 );
IGV_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 0 , IGV_CAL_AVERAGE_CALCULATE );
IGV_CAL_CAL_10_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_09_TRAN_3 , IGV_CAL_CAL_00_TRAN_2 , IGV_CAL_PUNCH_OR_OR , IGV_CAL_DLY_TRAN_1_DELAY );
IGV_CAL_CAL_11_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_10_TRAN_2 , IGV_CAL_PUNCH_OR_OR , IGV_CAL_DLY_TRAN_2_DELAY );
IGV_CAL_CAL_12_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_11_TRAN_2 , IGV_CAL_PUNCH_OR_OR , IGV_CAL_DLY_TRAN_3_DELAY );
IGV_CAL_CAL_13_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_12_TRAN_2 , IGV_CAL_PUNCH_OR_OR , IGV_CAL_DLY_TRAN_4_DELAY );
IGV_CAL_CAL_14_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_13_TRAN_2 , IGV_CAL_PUNCH_OR_OR , IGV_CAL_DLY_TRAN_5_DELAY );
IGV_CAL_CAL_14_OS_ONE_SHOT = ONE_SHOT_FUNCTION( 0 , IGV_CAL_CAL_15_SFC_STEP , 1_0 , 0 );
IGV_CAL_CAL_15_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_14_TRAN_2 , IGV_CAL_CAL_14_OS_ONE_SHOT );
IGV_CAL_CAL_16_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , IGV_CAL_CAL_00_TRAN_1 , IGV_CAL_NOTSTROKE_NOT , IGV_CAL_PUNCH_OR_OR );
IGV_CAL_DLY_DFCMP_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_DMDVSFDBK_B_OUT_1 , 0 , *5_0 (0_0, 20_0) );
IGV_CAL_DLY_TRAN_1_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_TRAN_1_AND , 0 , *15_0 (6_0, 50_0) );
IGV_CAL_DLY_TRAN_2_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_TRAN_2_AND , 0 , *15_0 (6_0, 50_0) );
IGV_CAL_DLY_TRAN_3_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_TRAN_3_AND , 0 , *15_0 (6_0, 50_0) );
IGV_CAL_DLY_TRAN_4_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_TRAN_4_AND , 0 , *15_0 (6_0, 50_0) );
IGV_CAL_DLY_TRAN_5_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_TRAN_5_AND , 0 , *15_0 (6_0, 50_0) );
IGV_CAL_DMDVSFDBK_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , out , IGV_CAL_DEMAND_A_NAME , dmd , IGV_CAL_AVG_POS_A_NAME , fdbk , IGV_CAL_ERROR_A_NAME , err , 1 , iin_1 , TRUE , enable2 , if (fabs(dmd-fdbk) < err) , { out = true; } , else , { out = false; } );
IGV_CAL_HI_MID_AND = AND_FUNCTION( IGV_CAL_CAL_13_SFC_STEP , IGV_CAL_I_CNT_ONE_DELAY , IGV_CAL_DLY_DFCMP_DELAY );
IGV_CAL_I_CNT_NOT = NOT_FUNCTION( IGV_CAL_I_CNT_ONE_DELAY );
IGV_CAL_I_CNTPV_ZMINUS1_B = ZMINUS1_B_FUNCTION( IGV_CAL_I_CNT_NOT );
IGV_CAL_I_CNT_ONE_DELAY = DELAY_FUNCTION( 0 , IGV_CAL_I_CNTPV_ZMINUS1_B , 0_32 , 0 );
IGV_CAL_LO_MID_AND = AND_FUNCTION( IGV_CAL_CAL_11_SFC_STEP , IGV_CAL_I_CNT_ONE_DELAY , IGV_CAL_DLY_DFCMP_DELAY );
IGV_CAL_MAX_AND = AND_FUNCTION( IGV_CAL_I_CNT_ONE_DELAY , IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_14_SFC_STEP );
IGV_CAL_MID_AND = AND_FUNCTION( IGV_CAL_CAL_12_SFC_STEP , IGV_CAL_I_CNT_ONE_DELAY , IGV_CAL_DLY_DFCMP_DELAY );
IGV_CAL_MIN_AND = AND_FUNCTION( IGV_CAL_CAL_10_SFC_STEP , IGV_CAL_I_CNT_ONE_DELAY , IGV_CAL_DLY_DFCMP_DELAY );
IGV_CAL_NOTSTROKE_NOT = NOT_FUNCTION( IGV_CAL_CALMODE_B_NAME );
IGV_CAL_NULJA_A_NAME = A_NAME_FUNCTION( IGV_CAL_NULLBIAS_NO );
IGV_CAL_NULLBIAS_A_SW_REV = A_SW_REV_FUNCTION( IGV_CAL_CAL_14_OS_ONE_SHOT , IGV_CAL_NULLBIAS_NC , IGV_CAL_AVG_NEGATE_NEGATE );
IGV_CAL_TRAN_1_AND = AND_FUNCTION( IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_10_SFC_STEP );
IGV_CAL_TRAN_2_AND = AND_FUNCTION( IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_11_SFC_STEP );
IGV_CAL_TRAN_3_AND = AND_FUNCTION( IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_12_SFC_STEP );
IGV_CAL_TRAN_4_AND = AND_FUNCTION( IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_13_SFC_STEP );
IGV_CAL_TRAN_5_AND = AND_FUNCTION( IGV_CAL_DLY_DFCMP_DELAY , IGV_CAL_CAL_14_SFC_STEP );
