switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_38;
  break;
  case 3:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_38;
  break;
  case 4:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = OP_INTRFC_WARMODE_M_B_NAME;
  break;
  case 6:
    OP_INTRFC_CALALL_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_CAL_ALL_B_NAME = OP_INTRFC_CALALL_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_37;
  break;
  case 3:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_37;
  break;
  case 4:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = OP_INTRFC_DCSCLKSYNC_OR;
  break;
  case 6:
    OP_INTRFC_CLCKSNC_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_DCSCLKSYNC_OR = OP_INTRFC_SYNCCLK_H_B_NAME || OP_INTRFC_SYNCCLK_MB_B_NAME;
OP_INTRFC_DCSSTOP_OR_OR = OP_INTRFC_STOP_MB_B_NAME || OP_INTRFC_STOP_RH_B_NAME;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = OP_INTRFC_STISEL_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_32;
  break;
  case 3:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_32;
  break;
  case 4:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = OP_INTRFC_STISEL_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_MANSTI_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_MANUAL_STI_B_NAME = OP_INTRFC_MANSTI_MX_B_MUX_N_1;
OP_INTRFC_START_LOG_B_NAME = OP_INTRFC_STRTLOG_MX_B_MUX_N_1;
OP_INTRFC_STISEL_H_B_NAME = FALSE;
OP_INTRFC_STISEL_MB_B_NAME = DATA_IO_DCS_BW_V_32;
OP_INTRFC_STOP_B_NAME = OP_INTRFC_STOP_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = OP_INTRFC_STPLOG_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_34;
  break;
  case 3:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_34;
  break;
  case 4:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = OP_INTRFC_STPLOG_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_STOPLOG_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = OP_INTRFC_STPPRT_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_35;
  break;
  case 3:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_35;
  break;
  case 4:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = OP_INTRFC_STPPRT_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_STOPPRN_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_STOP_H_B_NAME = N3N41_BI_LOC_STOP_BI_L;
OP_INTRFC_STOP_LOG_B_NAME = OP_INTRFC_STOPLOG_MX_B_MUX_N_1;
OP_INTRFC_STOP_MB_B_NAME = DATA_IO_DCS_BW_V_33;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = *FALSE;
  break;
  case 2:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_33;
  break;
  case 3:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_33;
  break;
  case 4:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = OP_INTRFC_DCSSTOP_OR_OR;
  break;
  case 6:
    OP_INTRFC_STOP_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_STOP_PRINT_B_NAME = OP_INTRFC_STOPPRN_MX_B_MUX_N_1;
OP_INTRFC_STOP_RH_B_NAME = N3N40_BI_REM_STOP_BI_L;
OP_INTRFC_STPLOG_H_B_NAME = FALSE;
OP_INTRFC_STPLOG_MB_B_NAME = DATA_IO_DCS_BW_V_34;
OP_INTRFC_STPPRT_H_B_NAME = FALSE;
OP_INTRFC_STPPRT_MB_B_NAME = DATA_IO_DCS_BW_V_35;
OP_INTRFC_STRTLOG_H_B_NAME = FALSE;
OP_INTRFC_STRTLOG_MB_B_NAME = DATA_IO_DCS_BW_V_36;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = OP_INTRFC_STRTLOG_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_36;
  break;
  case 3:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_36;
  break;
  case 4:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = OP_INTRFC_STRTLOG_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_STRTLOG_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_SYNCCLK_H_B_NAME = N3N40_BI_NET_CLOCK_BI_L;
OP_INTRFC_SYNCCLK_MB_B_NAME = DATA_IO_DCS_BW_V_37;
OP_INTRFC_SYNC_CLOCK_B_NAME = OP_INTRFC_CLCKSNC_MX_B_MUX_N_1;
OP_INTRFC_WARMODE_M_B_NAME = DATA_IO_DCS_BW_V_38;
OP_INTRFC_WWENBL_MB_B_NAME = DATA_IO_DCS_BW_V_39;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case 1:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = OP_INTRFC_WWENB_H_B_NAME;
  break;
  case 2:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_39;
  break;
  case 3:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_39;
  break;
  case 4:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = *FALSE;
  break;
  case 5:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = OP_INTRFC_WWENBL_MB_B_NAME;
  break;
  case 6:
    OP_INTRFC_WWENBL_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_WWENB_H_B_NAME = FALSE;
OP_INTRFC_WW_ENABLE_B_NAME = OP_INTRFC_WWENBL_MX_B_MUX_N_1;
