// RTC 
// PIPE_P 
// PIPE_P 
// PIPE_P 
// PIPE_P 
// UDP_P 
// UDP_P 
// UDP_P 
// UDP_P 
// UDP_P 
// UDP_P 
// UDP_P 
// UDP_P 
// SIO232PORT 
// SIO232PORT 
// TCP_P 
CPU_DAYS_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_3 , *16 (1, 31) );
CPU_HOURS_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_4 , *2 (0, 23) );
A_TO_INT_FUNCTION(1 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0 , 0.0);
CPU_MB_VALUES_OUT_1 = output1;
CPU_MB_VALUES_OUT_2 = output2;
CPU_MB_VALUES_OUT_3 = output3;
CPU_MB_VALUES_OUT_4 = output4;
CPU_MB_VALUES_OUT_5 = output5;
CPU_MB_VALUES_OUT_6 = output6;
CPU_MINUTES_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_5 , *0 (0, 59) );
CPU_MONTHS_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_2 , *4 (1, 12) );
CPU_SECONDS_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_6 , *0 (0, 59) );
CPU_SYNC_CLOCK_OR = OP_INTRFC_SYNC_CLOCK_B_NAME;
CPU_SYNC_INPUT_B_NAME = *TRUE;
CPU_TOD_T_TO_AN = T_TO_AN_FUNCTION( 1 , A1_A01_CPU_CLOCK_TOD );
I_TO_AN_FUNCTION(1 , A1_A01_CPU_CLOCK_YEARS , A1_A01_CPU_CLOCK_MONTHS , A1_A01_CPU_CLOCK_DAYS , A1_A01_CPU_CLOCK_HOURS , A1_A01_CPU_CLOCK_MINUTES , A1_A01_CPU_CLOCK_SECONDS);
CPU_TO_MODBUS_OUT_1 = output1;
CPU_TO_MODBUS_OUT_2 = output2;
CPU_TO_MODBUS_OUT_3 = output3;
CPU_TO_MODBUS_OUT_4 = output4;
CPU_TO_MODBUS_OUT_5 = output5;
CPU_TO_MODBUS_OUT_6 = output6;
CPU_YEAR_I_SW = I_SW_FUNCTION( CPU_SYNC_INPUT_B_NAME , CPU_MB_VALUES_OUT_1 , *97 (0, 99) );
// TUNE_VAR 
// NT_CPU 
// INTERFACE 
