GENERATOR_CDLO_GENR_B_NAME = FALSE;
GENERATOR_FSWM_GENR_B_NAME = FALSE;
GENERATOR_GEN_EARTH_B_NAME = FALSE;
GENERATOR_GS124_CLSD_B_NAME = FALSE;
GENERATOR_PSS_ON_B_NAME = GENERATOR_PSS_ONENBL_AND;
GENERATOR_PSS_ONENBL_AND = GENERATOR_GEN_BKRCLS_B_NAME && GENERATOR_UTIL_SW_B_SW;
GENERATOR_SML_GENR_B_NAME = FALSE;
GENERATOR_UTIL_SW_B_SW = B_SW_FUNCTION( *FALSE , TRUE , GENERATOR_UTIL_BKRCL_B_NAME );
