VENT_GENCL_C_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , out , DUMMY_IO , DUMMY_BO , VENT_HSS_G_TMP_A_MAX , english , 1 , DUMMY_I , HMI_INTER_ENG_SI_B_NAME , SI , if ( SI ) , { out = ( english - 32 ) * 5/9; } , else , { out = english; } );
VENT_G_ENCL_TMP_A_NAME = A_NAME_FUNCTION( VENT_GENCL_C_A_OUT_1 );
VENT_HSS_G_TMP_A_MAX = A_MAX_FUNCTION( VENT_TE6402_A_NAME , VENT_TE6430_A_NAME );
VENT_HSS_T_TMP_A_MAX = A_MAX_FUNCTION( VENT_TE6401_A_NAME , VENT_TE6454_A_NAME );
VENT_TE6401_A_NAME = A_NAME_FUNCTION( N1N6_RTD_TE6401_AI_RTD_L );
VENT_TE6401ALM_B_NAME = B_NAME_FUNCTION( VENT_TE6401LOG_B_OUT_1 );
VENT_TE6401LOG_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , alarm , shutdown , VENT_TE6401_A_NAME , input , 200_0 , alm_sp , shtdn_sp , 1 , iin_1 , TRUE , enable1 , FALSE , enable2 , if (input > alm_sp && enable1) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable2) , { shutdown = true; } , else , { shutdown = false; } , *290_0 (125_0, 300_0) );
VENT_TE6402_A_NAME = A_NAME_FUNCTION( N2N3_RTD_TE6402_AI_RTD_L );
VENT_TE6402LOG_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , alarm , shutdown , VENT_TE6402_A_NAME , input , 125_0 , alm_sp , 150_0 , shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , if (input > alm_sp && enable1) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable2) , { shutdown = true; } , else , { shutdown = false; } );
VENT_TE6430_A_NAME = A_NAME_FUNCTION( N2N4_RTD_TE6430_AI_RTD_L );
VENT_TE6430LOG_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , alarm , shutdown , VENT_TE6430_A_NAME , input , 200_0 , alm_sp , 220_0 , shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , if (input > alm_sp && enable1) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable2) , { shutdown = true; } , else , { shutdown = false; } );
VENT_TE6431_A_NAME = A_NAME_FUNCTION( N2N4_RTD_TE6431_AI_RTD_L );
VENT_TE6431LOG_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , alarm , shutdown , VENT_TE6431_A_NAME , input , 200_0 , alm_sp , 220_0 , shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , if (input > alm_sp && enable1) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable2) , { shutdown = true; } , else , { shutdown = false; } );
VENT_TE6454_A_NAME = A_NAME_FUNCTION( N1N6_RTD_TE6454_AI_RTD_L );
VENT_TE6454ALM_B_NAME = B_NAME_FUNCTION( VENT_TE6454LOG_B_OUT_1 );
VENT_TE6454DM_B_NAME = B_NAME_FUNCTION( VENT_TE6454LTC2_LATCH );
VENT_TE6454LOG_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , alarm , shutdown , VENT_TE6454_A_NAME , input , 140_0 , alm_sp , 150_0 , shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , if (input > alm_sp && enable1) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable2) , { shutdown = true; } , else , { shutdown = false; } );
VENT_TE6454LTC2_LATCH = LATCH_FUNCTION( 0 , VENT_TE6454LOG_B_OUT_2 , ALARM_RESET_B_NAME );
VENT_TENCL_C_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , out , DUMMY_IO , DUMMY_BO , VENT_HSS_T_TMP_A_MAX , english , 1 , DUMMY_I , HMI_INTER_ENG_SI_B_NAME , SI , if ( SI ) , { out = ( english - 32 ) * 5/9; } , else , { out = english; } );
VENT_TE_6402ALM_B_NAME = B_NAME_FUNCTION( VENT_TE6402LOG_B_OUT_1 );
VENT_TE_6402DM_B_NAME = B_NAME_FUNCTION( VENT_TE6402LOG_B_OUT_2 );
VENT_TE_6430ALM_B_NAME = B_NAME_FUNCTION( VENT_TE6430LOG_B_OUT_1 );
VENT_TE_6430DM_B_NAME = B_NAME_FUNCTION( VENT_TE6430LOG_B_OUT_2 );
VENT_TE_6431ALM_B_NAME = B_NAME_FUNCTION( VENT_TE6431LOG_B_OUT_1 );
VENT_TE_6431DM_B_NAME = B_NAME_FUNCTION( VENT_TE6431LOG_B_OUT_2 );
VENT_T_ENCL_TMP_A_NAME = A_NAME_FUNCTION( VENT_TENCL_C_A_OUT_1 );
