FUEL_SYS_BLKS_OPN_AND = FUEL_SYS_ZS6204OPEN_NOT && FUEL_SYS_ZS6249OPEN_NOT;
FUEL_SYS_DACTGAS_OR = FUEL_SYS_FUEL_RDY_TRAN_1 || FUEL_SYS_GASSTRT_01_TRAN_1 || FUEL_SYS_GASSTRT_02_TRAN_1 || FUEL_SYS_GASSTRT_03_TRAN_1 || FUEL_SYS_GASSTRT_04_TRAN_1 || FUEL_SYS_GASSTRT_05_TRAN_1 || FUEL_SYS_GASSTRT_06_TRAN_1;
if(FUEL_SYS_HOLD_TRAN_1 || FUEL_SYS_GASSTRT_06_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_FUEL_RDY_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( FUEL_SYS_GAS_STRTOS_ONE_SHOT) {
		FUEL_SYS_FUEL_RDY_TRAN_2 = FUEL_SYS_GAS_STRTOS_ONE_SHOT;
	} else 
		FUEL_SYS_FUEL_RDY_SFC_STEP= 1
} else {
  FUEL_SYS_FUEL_RDY_ACTIVETIME= 0; 
  FUEL_SYS_FUEL_RDY_SFC_STEP= 0; 
  FUEL_SYS_FUEL_RDY_TRAN_1= 0; 
  FUEL_SYS_FUEL_RDY_TRAN_2 = 0; 
}
FUEL_SYS_GASNOT_ON_NOT =! FUEL_SYS_SOV6249_B_NAME;
if(FUEL_SYS_FUEL_RDY_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_01_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( SFC_STEP_HI_SPDSEL2_SFC_STEP) {
		FUEL_SYS_GASSTRT_01_TRAN_2 = SFC_STEP_HI_SPDSEL2_SFC_STEP;
	} else 
		FUEL_SYS_GASSTRT_01_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_01_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_01_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_01_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_01_TRAN_2 = 0; 
}
if(FUEL_SYS_GASSTRT_01_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_02_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( TRUE) {
		FUEL_SYS_GASSTRT_02_TRAN_2 = TRUE;
	} else 
		FUEL_SYS_GASSTRT_02_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_02_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_02_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_02_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_02_TRAN_2 = 0; 
}
if(FUEL_SYS_GASSTRT_02_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_03_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( START_PERM_VMIN_STOP_B_NAME) {
		FUEL_SYS_GASSTRT_03_TRAN_2 = START_PERM_VMIN_STOP_B_NAME;
	} else 
		FUEL_SYS_GASSTRT_03_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_03_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_03_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_03_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_03_TRAN_2 = 0; 
}
if(FUEL_SYS_GASSTRT_03_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_04_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( FUEL_SYS_IGNITORDLY_DELAY) {
		FUEL_SYS_GASSTRT_04_TRAN_2 = FUEL_SYS_IGNITORDLY_DELAY;
	} else 
		FUEL_SYS_GASSTRT_04_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_04_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_04_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_04_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_04_TRAN_2 = 0; 
}
if(FUEL_SYS_GASSTRT_04_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_05_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( FUEL_SYS_BLKS_OPN_AND) {
		FUEL_SYS_GASSTRT_05_TRAN_2 = FUEL_SYS_BLKS_OPN_AND;
	} else 
		FUEL_SYS_GASSTRT_05_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_05_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_05_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_05_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_05_TRAN_2 = 0; 
}
if(FUEL_SYS_GASSTRT_05_TRAN_2) { 
	if( FUEL_SYS_CHOPFUEL_B_NAME) {
		FUEL_SYS_GASSTRT_06_TRAN_1 = FUEL_SYS_CHOPFUEL_B_NAME;
	} else if( CORE_DIGITAL_LITEOFF) {
		FUEL_SYS_GASSTRT_06_TRAN_2 = CORE_DIGITAL_LITEOFF;
	} else 
		FUEL_SYS_GASSTRT_06_SFC_STEP= 1
} else {
  FUEL_SYS_GASSTRT_06_ACTIVETIME= 0; 
  FUEL_SYS_GASSTRT_06_SFC_STEP= 0; 
  FUEL_SYS_GASSTRT_06_TRAN_1= 0; 
  FUEL_SYS_GASSTRT_06_TRAN_2 = 0; 
}
FUEL_SYS_GAS_START_AND = FUEL_SYS_START_OR_OR && FUEL_SYS_UNITREADY_B_NAME;
  bool FUEL_SYS_GAS_STRTOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.1 , 0 , FUEL_SYS_GAS_START_AND,&FUEL_SYS_GAS_STRTOS_ONE_SHOT,&FUEL_SYS_GAS_STRTOS_R_TIME,&FUEL_SYS_GAS_STRTOS_LAST_TRIGGER);
FUEL_SYS_G_MASKOFF2_AND = FUEL_SYS_GASNOT_ON_NOT && FUEL_SYS_N_CHOPFUEL_NOT;
if(FUEL_SYS_DACTGAS_OR) { 
	if( FUEL_SYS_G_MASKOFF2_AND) {
		FUEL_SYS_HOLD_TRAN_1 = FUEL_SYS_G_MASKOFF2_AND;
	} else 
		FUEL_SYS_HOLD_SFC_STEP= 1
} else {
  FUEL_SYS_HOLD_ACTIVETIME= 0; 
  FUEL_SYS_HOLD_SFC_STEP= 0; 
  FUEL_SYS_HOLD_TRAN_1 = 0; 
}
FUEL_SYS_HOT_START_B_NAME = SFC_STEP_MOTOR_6_SFC_STEP;
DELAY_FUNCTION(1 , FUEL_SYS_IGN_DLY_A_NAME , 0 , FUEL_SYS_IGNITORS_B_NAME,&FUEL_SYS_IGNITORDLY_DELAY,&FUEL_SYS_IGNITORDLY_R_TIME);
FUEL_SYS_IGN_DLY_A_NAME = 2;
FUEL_SYS_START_INI_B_NAME = SFC_STEP_START_INIT_B_NAME;
FUEL_SYS_START_OR_OR = FUEL_SYS_START_INI_B_NAME || FUEL_SYS_HOT_START_B_NAME;
FUEL_SYS_UNITREADY_B_NAME = SHUTDOWN_NO_SHTDNS_B_NAME;
