IFACE_CNFG_CHDRIVE_I_NAME = 0;
IFACE_CNFG_CHPDET_OPT_B_NAME = *TRUE;
DELAY_FUNCTION(1 , 10 , 60 , FALSE,&IFACE_CNFG_COND_DLY_DELAY,&IFACE_CNFG_COND_DLY_R_TIME);
IFACE_CNFG_CON_REF_A_SW = A_SW_FUNCTION( IFACE_CNFG_COND_DLY_DELAY , IFACE_CNFG_CON_REFSW1_A_SW , IFACE_CNFG_CON_REFSW2_A_SW );
IFACE_CNFG_CON_REFSW1_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3610 , 3637 );
IFACE_CNFG_CON_REFSW2_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3625 , 3652 );
IFACE_CNFG_FLMDTMODEJ_I_NAME = 2;
IFACE_CNFG_FLMDT_MODE_OUT_1 = (double)IFACE_CNFG_FLMDTMODEJ_I_NAME;
IFACE_CNFG_FREQ_50_HZ_B_NAME = FALSE;
IFACE_CNFG_GMVI_SN_I_NAME = 60000001;
IFACE_CNFG_GMVO_SN_I_NAME = 60000002;
IFACE_CNFG_GMVP_SN_I_NAME = 60000000;
IFACE_CNFG_KVOLOEMI_A_NAME = 358.7;
IFACE_CNFG_KVOLOEMO_A_NAME = 373.1;
IFACE_CNFG_KVOLOEMP_A_NAME = 363.2;
IFACE_CNFG_LUBFLT_OPT_B_NAME = *FALSE;
IFACE_CNFG_LUBPRS_OPT_B_NAME = *FALSE;
IFACE_CNFG_LUBTMP_OPT_B_NAME = *TRUE;
IFACE_CNFG_MAX_REF_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3780 , 3807 );
IFACE_CNFG_MIN_REF_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3600 , 3627 );
IFACE_CNFG_MX_LD_NWTR_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3780 , 3807 );
IFACE_CNFG_NPTMECHMN_A_NAME = 1800;
IFACE_CNFG_NPTPWRMN_A_NAME = IFACE_CNFG_REF_SW_DRP_A_SW;
switch(IFACE_CNFG_SWMW_I_NAME) { 
  case 1:
    IFACE_CNFG_NSD_MN_A_MUX_N_1 = IFACE_CNFG_SYNC_SPD_A_SW;
  break;
  case 2:
    IFACE_CNFG_NSD_MN_A_MUX_N_1 = IFACE_CNFG_NPTMECHMN_A_NAME;
  break;
  case 3:
    IFACE_CNFG_NSD_MN_A_MUX_N_1 = IFACE_CNFG_NPTPWRMN_A_NAME;
  break;
}
IFACE_CNFG_NSD_MN_OP_A_NAME = IFACE_CNFG_NSD_MN_A_MUX_N_1;
IFACE_CNFG_PRESYNCSPD_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3602 , 3629 );
IFACE_CNFG_REF_SW_DRP_A_SW = A_SW_FUNCTION( IFACE_CORE_Z_SWGRID_B_NAME , IFACE_CNFG_REF_SW_ISO_A_SW , IFACE_CNFG_CON_REF_A_SW );
IFACE_CNFG_REF_SW_ISO_A_SW = A_SW_FUNCTION( IFACE_CORE_Z_BREAKER_B_NAME , 3500 , IFACE_CNFG_SYNC_SPD_A_SW );
IFACE_CNFG_SWMW_I_NAME = 3;
IFACE_CNFG_SYNC_SPD_A_SW = A_SW_FUNCTION( IFACE_CNFG_FREQ_50_HZ_B_NAME , 3600.0 , 3627.0 );
IFACE_CNFG_Z_DMP_UNIT_B_NAME = FALSE;
IFACE_CNFG_Z_DROOP_A_NAME = 5;
IFACE_CNFG_Z_NSDOSLIM_A_NAME = 4300;
IFACE_CNFG_Z_RT25_UNT_B_NAME = FALSE;
IFACE_CNFG_Z_RT2_UNIT_B_NAME = FALSE;
IFACE_CNFG_Z_SPR_UNIT_B_NAME = FALSE;
IFACE_CNFG_Z_TBV_UNIT_B_NAME = *TRUE;
IFACE_CNFG_Z_VT48_UNT_B_NAME = *FALSE;
