if(GLUB_LUBE_ABRT_OR) { 
	if( GLUB_ABRT_Z_ZMINUS1_B) {
		GLUB_ABORT_TRAN_1 = GLUB_ABRT_Z_ZMINUS1_B;
	} else 
		GLUB_ABORT_SFC_STEP= 1
} else {
  GLUB_ABORT_ACTIVETIME= 0; 
  GLUB_ABORT_SFC_STEP= 0; 
  GLUB_ABORT_TRAN_1 = 0; 
}
GLUB_ABRT_Z_ZMINUS1_B = GLUB_DLY_ABRT_DELAY;
GLUB_ACT_RUNDWN_OR = GLUB_FAST_START_AND || GLUB_STARTING_AND;
DELAY_FUNCTION(1 , 420 , 0 , GLUB_RUN_AUXTMR_OR,&GLUB_AUXTMR_DELAY,&GLUB_AUXTMR_R_TIME);
DELAY_FUNCTION(1 , 10 , 0 , GLUB_GLUBBRG_OK_AND,&GLUB_BRGTEMPDLY_DELAY,&GLUB_BRGTEMPDLY_R_TIME);
GLUB_BRG_TMP_OP_B_NAME = *TRUE;
DELAY_FUNCTION(1 , 1.0 , 0 , GLUB_ABORT_SFC_STEP,&GLUB_DLY_ABRT_DELAY,&GLUB_DLY_ABRT_R_TIME);
GLUB_EHERACON_OR = GLUB_MOT6075A_B_NAME || GLUB_MOT6075B_B_NAME;
GLUB_FAST_START_AND = SFC_STEP_GLUB_SFC_STEP && TIMERS_DO_F_START_B_NAME && GLUB_EHERACON_OR;
GLUB_GLUBBRG_OK_AND = GLUB_TE6021PERM_B_NAME && GLUB_TE6023PERM_B_NAME;
if(GLUB_GLUB_RNDN_TRAN_2) { 
	if( SHUTDOWN_ANY_SD_B_NAME) {
		GLUB_GLUBGBRNDN_TRAN_1 = SHUTDOWN_ANY_SD_B_NAME;
	} else if( GLUB_GBRNDN_OK_B_NAME) {
		GLUB_GLUBGBRNDN_TRAN_2 = GLUB_GBRNDN_OK_B_NAME;
	} else 
		GLUB_GLUBGBRNDN_SFC_STEP= 1
} else {
  GLUB_GLUBGBRNDN_ACTIVETIME= 0; 
  GLUB_GLUBGBRNDN_SFC_STEP= 0; 
  GLUB_GLUBGBRNDN_TRAN_1= 0; 
  GLUB_GLUBGBRNDN_TRAN_2 = 0; 
}
if(GLUB_OUTOFOP2_TRAN_2) { 
	if( SHUTDOWN_ANY_SD_B_NAME) {
		GLUB_GLUB_RNDN_TRAN_1 = SHUTDOWN_ANY_SD_B_NAME;
	} else if( GLUB_GNRNDN_OK_B_NAME) {
		GLUB_GLUB_RNDN_TRAN_2 = GLUB_GNRNDN_OK_B_NAME;
	} else 
		GLUB_GLUB_RNDN_SFC_STEP= 1
} else {
  GLUB_GLUB_RNDN_ACTIVETIME= 0; 
  GLUB_GLUB_RNDN_SFC_STEP= 0; 
  GLUB_GLUB_RNDN_TRAN_1= 0; 
  GLUB_GLUB_RNDN_TRAN_2 = 0; 
}
GLUB_HICNKACTIV_B_NAME = SFC_STEP_HICNKACTIV_OR;
if(GLUB_TEMP_CHCK_TRAN_3) { 
	if( GLUB_MOT6031DLY_DELAY) {
		GLUB_JACKPMP_ON_TRAN_1 = GLUB_MOT6031DLY_DELAY;
	} else 
		GLUB_JACKPMP_ON_SFC_STEP= 1
} else {
  GLUB_JACKPMP_ON_ACTIVETIME= 0; 
  GLUB_JACKPMP_ON_SFC_STEP= 0; 
  GLUB_JACKPMP_ON_TRAN_1 = 0; 
}
GLUB_LOCNKACTIV_B_NAME = SFC_STEP_LOSPD_OR_OR;
GLUB_LUBE_ABRT_OR = GLUB_GLUB_DC_TRAN_1 || GLUB_GLUB_DC_TRAN_2 || GLUB_AC_1_1_TRAN_2 || GLUB_AC_1_2_TRAN_2 || GLUB_AC_1_3_TRAN_2 || GLUB_AC_1_4_TRAN_2 || GLUB_AC_2_1_TRAN_2 || GLUB_AC_2_2_TRAN_2 || GLUB_AC_2_3_TRAN_2 || GLUB_AC_2_4_TRAN_2 || GLUB_TEMP_CHCK_TRAN_1 || GLUB_AC_1_1_TRAN_1 || GLUB_AC_60_VER_TRAN_1 || GLUB_AC_60_VER_TRAN_2 || GLUB_AC_1_2_TRAN_1 || GLUB_AC_1_3_TRAN_1 || GLUB_AC_1_4_TRAN_1 || GLUB_AC_2_1_TRAN_1 || GLUB_AC_2_2_TRAN_1 || GLUB_AC_2_3_TRAN_1 || GLUB_AC_2_4_TRAN_1;
DELAY_FUNCTION(1 , 0.25 , 0 , GLUB_MOT6031ON_OR,&GLUB_MOT6031DLY_DELAY,&GLUB_MOT6031DLY_R_TIME);
GLUB_MOT6031ON_OR = GLUB_MOT6031_B_NAME || SHUTDOWN_ANY_SD_B_NAME;
GLUB_NEEDTORUN_OR = GLUB_WW_ACTIVE_B_NAME || GLUB_START_INIT_B_NAME || GLUB_HICNKACTIV_B_NAME || GLUB_LOCNKACTIV_B_NAME;
if(GLUB_JACKPMP_ON_TRAN_1 || GLUB_OUTOFOP2_TRAN_1 || GLUB_STOP_OR) { 
	if( GLUB_RDY_OR_OR) {
		GLUB_NOT_OPERAT_TRAN_1 = GLUB_RDY_OR_OR;
	} else 
		GLUB_NOT_OPERAT_SFC_STEP= 1
} else {
  GLUB_NOT_OPERAT_ACTIVETIME= 0; 
  GLUB_NOT_OPERAT_SFC_STEP= 0; 
  GLUB_NOT_OPERAT_TRAN_1 = 0; 
}
if(GLUB_NOT_OPERAT_TRAN_1) { 
	if( SHUTDOWN_ANY_SD_B_NAME) {
		GLUB_OUTOFOP2_TRAN_1 = SHUTDOWN_ANY_SD_B_NAME;
	} else if( GLUB_ACT_RUNDWN_OR) {
		GLUB_OUTOFOP2_TRAN_2 = GLUB_ACT_RUNDWN_OR;
	} else 
		GLUB_OUTOFOP2_SFC_STEP= 1
} else {
  GLUB_OUTOFOP2_ACTIVETIME= 0; 
  GLUB_OUTOFOP2_SFC_STEP= 0; 
  GLUB_OUTOFOP2_TRAN_1= 0; 
  GLUB_OUTOFOP2_TRAN_2 = 0; 
}
GLUB_RDY_OR_OR = START_PERM_T_STARTPM_AND || START_PERM_C_PERM_AND;
GLUB_RUN_AUXTMR_OR = GLUB_GLUB_DC_SFC_STEP || GLUB_GLUB_RNDN_SFC_STEP || GLUB_GLUBGBRNDN_SFC_STEP || GLUB_AC_1_1_SFC_STEP || GLUB_AC_1_2_SFC_STEP || GLUB_AC_1_3_SFC_STEP || GLUB_AC_1_4_SFC_STEP || GLUB_AC_2_1_SFC_STEP || GLUB_AC_2_2_SFC_STEP || GLUB_AC_2_3_SFC_STEP || GLUB_AC_2_4_SFC_STEP;
DELAY_FUNCTION(1 , 1800 , 0 , GLUB_TEMP_CHCK_SFC_STEP,&GLUB_SPLYTMPDLY_DELAY,&GLUB_SPLYTMPDLY_R_TIME);
GLUB_STARTING_AND = GLUB_ACTIVE_LATCH1 && GLUB_NEEDTORUN_OR;
GLUB_START_INIT_B_NAME = SFC_STEP_START_INIT_B_NAME;
GLUB_STOP_OR = GLUB_OUTOFOP2_TRAN_1 || GLUB_GLUB_RNDN_TRAN_1 || GLUB_GLUBGBRNDN_TRAN_1 || GLUB_TEMP_CHCK_TRAN_2;
if(GLUB_GLUBGBRNDN_TRAN_2) { 
	if( GLUB_TMPDLYMASK_AND) {
		GLUB_TEMP_CHCK_TRAN_1 = GLUB_TMPDLYMASK_AND;
	} else if( SHUTDOWN_ANY_SD_B_NAME) {
		GLUB_TEMP_CHCK_TRAN_2 = SHUTDOWN_ANY_SD_B_NAME;
	} else if( GLUB_BRGTEMPDLY_DELAY) {
		GLUB_TEMP_CHCK_TRAN_3 = GLUB_BRGTEMPDLY_DELAY;
	} else 
		GLUB_TEMP_CHCK_SFC_STEP= 1
} else {
  GLUB_TEMP_CHCK_ACTIVETIME= 0; 
  GLUB_TEMP_CHCK_SFC_STEP= 0; 
  GLUB_TEMP_CHCK_TRAN_1= 0; 
  GLUB_TEMP_CHCK_TRAN_2= 0; 
  GLUB_TEMP_CHCK_TRAN_3 = 0; 
}
GLUB_TMPDLYMASK_AND = GLUB_SPLYTMPDLY_DELAY && GLUB_BRG_TMP_OP_B_NAME;
GLUB_WW_ACTIVE_B_NAME = WTR_WASH_WW_ACTIVE_B_NAME;
