LOC_REM_DELTAABC_S_A_SW = A_SW_FUNCTION( LOC_REM_MAPDLY_DELAY , LOC_REM_DELTAABC_Z_ZMINUS1 , 0.0 );
LOC_REM_DELTAABC_Z_ZMINUS1 = LOC_REM_DELTA_ABC_A_MUX_N_1;
LOC_REM_DELTAAB_SW_A_SW = A_SW_FUNCTION( LOC_REM_MAPDLY_DELAY , LOC_REM_DELTAAB_Z_ZMINUS1 , 0.0 );
LOC_REM_DELTAAB_Z_ZMINUS1 = LOC_REM_DELTA_AB_A_MUX_N_1;
LOC_REM_DELTAA_SW_A_SW = A_SW_FUNCTION( LOC_REM_MAPDLY_DELAY , LOC_REM_DELTAA_Z_ZMINUS1 , 0.0 );
LOC_REM_DELTAA_Z_ZMINUS1 = LOC_REM_DELTA_A_A_MUX_N_1;
switch(LOC_REM_LOC_REM_I_I_SW) { 
  case 1:
    LOC_REM_DELTA_A_A_MUX_N_1 = LOC_REM_DELTAA_SW_A_SW;
  break;
  case 2:
    LOC_REM_DELTA_A_A_MUX_N_1 = 10;
  break;
}
switch(LOC_REM_LOC_REM_I_I_SW) { 
  case 1:
    LOC_REM_DELTA_AB_A_MUX_N_1 = LOC_REM_DELTAAB_SW_A_SW;
  break;
  case 2:
    LOC_REM_DELTA_AB_A_MUX_N_1 = 20;
  break;
}
switch(LOC_REM_LOC_REM_I_I_SW) { 
  case 1:
    LOC_REM_DELTA_ABC_A_MUX_N_1 = LOC_REM_DELTAABC_S_A_SW;
  break;
  case 2:
    LOC_REM_DELTA_ABC_A_MUX_N_1 = 30;
  break;
}
LOC_REM_LOC_REM_I_I_SW = I_SW_FUNCTION( *FALSE , 1 , 2 );
