DELAY_FUNCTION(1 , 5 , 0 , SFC_STEP_HYDPMPON_OR,&SFC_STEP_AUXFAN_DLY_DELAY,&SFC_STEP_AUXFAN_DLY_R_TIME);
SFC_STEP_HIEST_SEL_OR = SFC_STEP_HIEST_SW_NO || SFC_STEP_HI_SPDSEL3_SFC_STEP || SFC_STEP_HISPDPURGE_OR || SFC_STEP_HI_SPDSEL2_SFC_STEP || SFC_STEP_MOTOR_3_SFC_STEP || SFC_STEP_HICRANK_4_SFC_STEP;
B_SW_REV_FUNCTION(SFC_STEP_HIGHER_SPD_B_NAME , FALSE , SFC_STEP_WWCRANK_3_SFC_STEP,&SFC_STEP_HIEST_SW_NC,&SFC_STEP_HIEST_SW_NO);
SFC_STEP_HIGHER_SPD_B_NAME = *TRUE;
SFC_STEP_HI_SPD_OR_OR = SFC_STEP_HIEST_SW_NC;
SFC_STEP_HYDPMPON_OR = SFC_STEP_HYD_STRT_SFC_STEP || SFC_STEP_LOCRANK_2_SFC_STEP || SFC_STEP_HICRANK_2_SFC_STEP || SFC_STEP_WWCRANK_2_SFC_STEP || SFC_STEP_MOTOR_2_SFC_STEP;
A_COMPARE_FUNCTION(0 , IFACE_HDWR_IGVSEL_A_NAME , 90.0,&SFC_STEP_IGV_CLSD_A_COMPARE,&SFC_STEP_IGV_CLSD_A_EQUAL);
SFC_STEP_SW_SELS_B_SW = B_SW_FUNCTION( SFC_STEP_HIGHER_SPD_B_NAME , HYD_STRT_SOV1619RMP_P_LIM_3 , HYD_STRT_SOV1619RMP_P_LIM_4 );
DELAY_FUNCTION(1 , 300 , 0 , TEMP_SW_T48LT200_NOT,&SFC_STEP_T48LOTMR_DELAY,&SFC_STEP_T48LOTMR_R_TIME);
A_COMPARE_FUNCTION(0 , 5.0 , IFACE_HDWR_VBVSEL_A_NAME,&SFC_STEP_VBV_CLSD_A_COMPARE,&SFC_STEP_VBV_CLSD_A_EQUAL);
SFC_STEP_WWACTIVE2_OR = SFC_STEP_WWCRANK_6_SFC_STEP || SFC_STEP_WWCRANK_7_SFC_STEP || SFC_STEP_WWCRANK_8_SFC_STEP || SFC_STEP_WWCRANK_9_SFC_STEP || SFC_STEP_WWCRANK_10_SFC_STEP;
if(SFC_STEP_OUTOFOP_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_0_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WW_FAN_ON_DELAY) {
		SFC_STEP_WWCRANK_0_TRAN_2 = SFC_STEP_WW_FAN_ON_DELAY;
	} else 
		SFC_STEP_WWCRANK_0_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_0_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_0_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_0_TRAN_1= 0; 
  SFC_STEP_WWCRANK_0_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_0_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_1_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( GLUB_MOT6031_B_NAME) {
		SFC_STEP_WWCRANK_1_TRAN_2 = GLUB_MOT6031_B_NAME;
	} else 
		SFC_STEP_WWCRANK_1_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_1_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_1_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_1_TRAN_1= 0; 
  SFC_STEP_WWCRANK_1_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_9_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_10_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( WTR_WASH_WW_DONE1_B_NAME) {
		SFC_STEP_WWCRANK_10_TRAN_2 = WTR_WASH_WW_DONE1_B_NAME;
	} else 
		SFC_STEP_WWCRANK_10_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_10_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_10_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_10_TRAN_1= 0; 
  SFC_STEP_WWCRANK_10_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_10_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_11_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( WTR_WASH_SOAK_DONE_B_NAME) {
		SFC_STEP_WWCRANK_11_TRAN_2 = WTR_WASH_SOAK_DONE_B_NAME;
	} else 
		SFC_STEP_WWCRANK_11_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_11_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_11_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_11_TRAN_1= 0; 
  SFC_STEP_WWCRANK_11_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_1_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_2_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( HYD_STRT_PUMPONDLY_DELAY) {
		SFC_STEP_WWCRANK_2_TRAN_2 = HYD_STRT_PUMPONDLY_DELAY;
	} else 
		SFC_STEP_WWCRANK_2_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_2_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_2_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_2_TRAN_1= 0; 
  SFC_STEP_WWCRANK_2_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_2_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_3_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_SW_SELS_B_SW) {
		SFC_STEP_WWCRANK_3_TRAN_2 = SFC_STEP_SW_SELS_B_SW;
	} else 
		SFC_STEP_WWCRANK_3_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_3_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_3_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_3_TRAN_1= 0; 
  SFC_STEP_WWCRANK_3_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_3_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_4_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP4AND_AND) {
		SFC_STEP_WWCRANK_4_TRAN_2 = SFC_STEP_WWSTEP4AND_AND;
	} else 
		SFC_STEP_WWCRANK_4_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_4_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_4_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_4_TRAN_1= 0; 
  SFC_STEP_WWCRANK_4_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_4_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_5_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP5AND_AND) {
		SFC_STEP_WWCRANK_5_TRAN_2 = SFC_STEP_WWSTEP5AND_AND;
	} else 
		SFC_STEP_WWCRANK_5_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_5_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_5_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_5_TRAN_1= 0; 
  SFC_STEP_WWCRANK_5_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_5_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_6_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP6AND_AND) {
		SFC_STEP_WWCRANK_6_TRAN_2 = SFC_STEP_WWSTEP6AND_AND;
	} else 
		SFC_STEP_WWCRANK_6_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_6_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_6_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_6_TRAN_1= 0; 
  SFC_STEP_WWCRANK_6_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_6_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_7_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP7AND_AND) {
		SFC_STEP_WWCRANK_7_TRAN_2 = SFC_STEP_WWSTEP7AND_AND;
	} else 
		SFC_STEP_WWCRANK_7_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_7_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_7_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_7_TRAN_1= 0; 
  SFC_STEP_WWCRANK_7_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_7_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_8_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP8AND_AND) {
		SFC_STEP_WWCRANK_8_TRAN_2 = SFC_STEP_WWSTEP8AND_AND;
	} else 
		SFC_STEP_WWCRANK_8_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_8_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_8_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_8_TRAN_1= 0; 
  SFC_STEP_WWCRANK_8_TRAN_2 = 0; 
}
if(SFC_STEP_WWCRANK_8_TRAN_2) { 
	if( SFC_STEP_WW_ABORT_LATCH1) {
		SFC_STEP_WWCRANK_9_TRAN_1 = SFC_STEP_WW_ABORT_LATCH1;
	} else if( SFC_STEP_WWSTEP9AND_AND) {
		SFC_STEP_WWCRANK_9_TRAN_2 = SFC_STEP_WWSTEP9AND_AND;
	} else 
		SFC_STEP_WWCRANK_9_SFC_STEP= 1
} else {
  SFC_STEP_WWCRANK_9_ACTIVETIME= 0; 
  SFC_STEP_WWCRANK_9_SFC_STEP= 0; 
  SFC_STEP_WWCRANK_9_TRAN_1= 0; 
  SFC_STEP_WWCRANK_9_TRAN_2 = 0; 
}
SFC_STEP_WWSTEP4AND_AND = SFC_STEP_WWSTEP4DLY_DELAY && SPEED_SW_N25GT2000_A_COMPARE;
DELAY_FUNCTION(1 , 2.0 , 0 , SFC_STEP_WWCRANK_4_SFC_STEP,&SFC_STEP_WWSTEP4DLY_DELAY,&SFC_STEP_WWSTEP4DLY_R_TIME);
SFC_STEP_WWSTEP5AND_AND = SFC_STEP_WWSTEP5DLY_DELAY && SPEED_SW_NSDGT200_A_COMPARE;
DELAY_FUNCTION(1 , 2.0 , 0 , SFC_STEP_WWCRANK_5_SFC_STEP,&SFC_STEP_WWSTEP5DLY_DELAY,&SFC_STEP_WWSTEP5DLY_R_TIME);
SFC_STEP_WWSTEP6AND_AND = SFC_STEP_WWSTEP6DLY_DELAY && SFC_STEP_T48LOTMR_DELAY;
DELAY_FUNCTION(1 , 30 , 0 , SFC_STEP_WWCRANK_6_SFC_STEP,&SFC_STEP_WWSTEP6DLY_DELAY,&SFC_STEP_WWSTEP6DLY_R_TIME);
SFC_STEP_WWSTEP7AND_AND = SFC_STEP_WWSTEP7DLY_DELAY && TEMP_SW_T3LT200_NOT;
DELAY_FUNCTION(1 , 30 , 0 , SFC_STEP_WWCRANK_7_SFC_STEP,&SFC_STEP_WWSTEP7DLY_DELAY,&SFC_STEP_WWSTEP7DLY_R_TIME);
SFC_STEP_WWSTEP8AND_AND = SFC_STEP_WWSTEP8DLY_DELAY && SFC_STEP_VBV_CLSD_A_COMPARE;
DELAY_FUNCTION(1 , 2.0 , 0 , SFC_STEP_WWCRANK_8_SFC_STEP,&SFC_STEP_WWSTEP8DLY_DELAY,&SFC_STEP_WWSTEP8DLY_R_TIME);
SFC_STEP_WWSTEP9AND_AND = SFC_STEP_WWSTEP9DLY_DELAY && SFC_STEP_IGV_CLSD_A_COMPARE;
DELAY_FUNCTION(1 , 2.0 , 0 , SFC_STEP_WWCRANK_9_SFC_STEP,&SFC_STEP_WWSTEP9DLY_DELAY,&SFC_STEP_WWSTEP9DLY_R_TIME);
DELAY_FUNCTION(1 , 30 , 0 , SFC_STEP_WWCRANK_0_SFC_STEP,&SFC_STEP_WW_FAN_ON_DELAY,&SFC_STEP_WW_FAN_ON_R_TIME);
DELAY_FUNCTION(1 , 10 , 0 , SFC_STEP_WWACTIVE2_OR,&SFC_STEP_WW_SPD_DLY_DELAY,&SFC_STEP_WW_SPD_DLY_R_TIME);
WTR_INJ_WWNACTVAND_AND = WTR_WASH_WWACTIVE1_OR && ONLINE_WW_ONLWW_OO_SFC_STEP;
WTR_WASH_WWACTIVE1_OR = SFC_STEP_WWCRANK_0_SFC_STEP || SFC_STEP_WWCRANK_1_SFC_STEP || SFC_STEP_WWCRANK_2_SFC_STEP || SFC_STEP_WWCRANK_3_SFC_STEP || SFC_STEP_WWCRANK_4_SFC_STEP || SFC_STEP_WWCRANK_5_SFC_STEP || SFC_STEP_WWCRANK_11_SFC_STEP || SFC_STEP_WWACTIVE2_OR;
WTR_WASH_WW_ACTIVE_B_NAME = WTR_WASH_WWACTIVE1_OR;
WTR_WASH_WW_NTACTIV_NOT =! WTR_INJ_WWNACTVAND_AND;
