FUEL_SYS_GAS100_B_NAME = B_NAME_FUNCTION( TRUE );
FUEL_SYS_K336_DLY_DELAY = DELAY_FUNCTION( 0 , FUEL_SYS_K336_PERM_B_NAME , 0 , *10_0 (0_5, 30_0) );
FUEL_SYS_K336_DLY_R_TIME = R_TIME_FUNCTION( 0 , FUEL_SYS_K336_PERM_B_NAME , 0 , *10_0 (0_5, 30_0) );
FUEL_SYS_PGAS_H_SW_B_SW = B_SW_FUNCTION( FUEL_SYS_PGAS_LT700_A_COMPARE , TRUE , 0 );
FUEL_SYS_PGAS_LT700_A_COMPARE = A_COMPARE_FUNCTION( FUEL_SYS_PT6227SW_A_SW , 1_0 , *700_0 (690_0, 720_0) );
FUEL_SYS_PGAS_LT700_A_EQUAL = A_EQUAL_FUNCTION( FUEL_SYS_PT6227SW_A_SW , 1_0 , *700_0 (690_0, 720_0) );
FUEL_SYS_PGS_ABS_A_NAME = A_NAME_FUNCTION( FUEL_SYS_PT6227_ABS_ADD );
FUEL_SYS_PGS_GT200_A_COMPARE = A_COMPARE_FUNCTION( FUEL_SYS_PT6227SW_A_SW , 200_0 , 1_0 );
FUEL_SYS_PGS_GT200_A_EQUAL = A_EQUAL_FUNCTION( FUEL_SYS_PT6227SW_A_SW , 200_0 , 1_0 );
FUEL_SYS_PGS_GT_200_B_NAME = B_NAME_FUNCTION( FUEL_SYS_PGS_GT200_A_COMPARE );
FUEL_SYS_PGS_LT_700_B_NAME = B_NAME_FUNCTION( FUEL_SYS_PGAS_H_SW_B_SW );
FUEL_SYS_PSHH6226_B_NAME = B_NAME_FUNCTION( N1N33_BI_PSHH6226_BI_L );
FUEL_SYS_PSHH6226AL_B_NAME = B_NAME_FUNCTION( FUEL_SYS_PSHH6226SW_NC );
FUEL_SYS_PSHH6226NT_NOT = NOT_FUNCTION( FUEL_SYS_PSHH6226_B_NAME );
FUEL_SYS_PSHH6226SD_B_NAME = B_NAME_FUNCTION( FUEL_SYS_PSHH6226SW_NO );
FUEL_SYS_PSHH6226SW_NC = NC_FUNCTION( FUEL_SYS_GAS100_B_NAME , FALSE , FUEL_SYS_PSHH6226NT_NOT );
FUEL_SYS_PSHH6226SW_NO = NO_FUNCTION( FUEL_SYS_GAS100_B_NAME , FALSE , FUEL_SYS_PSHH6226NT_NOT );
FUEL_SYS_PSL6224_B_NAME = B_NAME_FUNCTION( N1N33_BI_PSL6224_BI_L );
FUEL_SYS_PSL6224MSK_AND = AND_FUNCTION( FUEL_SYS_PSL6224NT_NOT , FUEL_SYS_K336_DLY_DELAY );
FUEL_SYS_PSL6224NT_NOT = NOT_FUNCTION( FUEL_SYS_PSL6224_B_NAME );
FUEL_SYS_PSL6224_AL_B_NAME = B_NAME_FUNCTION( FUEL_SYS_PSL6224MSK_AND );
FUEL_SYS_PT6227_A_NAME = A_NAME_FUNCTION( N1N1_AI_PT6227_AI_420_L );
FUEL_SYS_PT6227SW_A_SW = A_SW_FUNCTION( FUEL_SYS_PT6227VST_B_NAME , FUEL_SYS_PT6227_A_NAME , 665_0 );
FUEL_SYS_PT6227VST_B_NAME = B_NAME_FUNCTION( N1N1_AI_PT6227_LATCH_OR );
FUEL_SYS_PT6227_ABS_ADD = ADD_FUNCTION( 0 , FUEL_SYS_PT6227SW_A_SW , 14_696 );
FUEL_SYS_TE6232AB_A_NAME = A_NAME_FUNCTION( CORE_ANALOG_TGSSEL );
FUEL_SYS_TE6232ALOG_ALM = ALM_FUNCTION( shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , TRUE , enable , if (input > alm_sp && enable) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable) , { shutdown = true; } , else , { shutdown = false; } , 0 , 0 , aout1 , iout1 , alarm , shutdown , FUEL_SYS_TE6232AB_A_NAME , input , 275_0 , alm_sp , 300_0 );
FUEL_SYS_TE6232ALOG_A_OUT_1 = A_OUT_1_FUNCTION( shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , TRUE , enable , if (input > alm_sp && enable) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable) , { shutdown = true; } , else , { shutdown = false; } , 0 , 0 , aout1 , iout1 , alarm , shutdown , FUEL_SYS_TE6232AB_A_NAME , input , 275_0 , alm_sp , 300_0 );
FUEL_SYS_TE6232ALOG_I_OUT_1 = I_OUT_1_FUNCTION( shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , TRUE , enable , if (input > alm_sp && enable) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable) , { shutdown = true; } , else , { shutdown = false; } , 0 , 0 , aout1 , iout1 , alarm , shutdown , FUEL_SYS_TE6232AB_A_NAME , input , 275_0 , alm_sp , 300_0 );
FUEL_SYS_TE6232ALOG_B_OUT_1 = B_OUT_1_FUNCTION( shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , TRUE , enable , if (input > alm_sp && enable) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable) , { shutdown = true; } , else , { shutdown = false; } , 0 , 0 , aout1 , iout1 , alarm , shutdown , FUEL_SYS_TE6232AB_A_NAME , input , 275_0 , alm_sp , 300_0 );
FUEL_SYS_TE6232ALOG_B_OUT_2 = B_OUT_2_FUNCTION( shtdn_sp , 1 , iin_1 , TRUE , enable1 , TRUE , enable2 , TRUE , enable , if (input > alm_sp && enable) , { alarm = true; } , else , { alarm = false; } , if (input > shtdn_sp && enable) , { shutdown = true; } , else , { shutdown = false; } , 0 , 0 , aout1 , iout1 , alarm , shutdown , FUEL_SYS_TE6232AB_A_NAME , input , 275_0 , alm_sp , 300_0 );
FUEL_SYS_TE6232H_B_NAME = B_NAME_FUNCTION( FUEL_SYS_TE62544LOG_B_OUT_1 );
FUEL_SYS_TE6232HH_B_NAME = B_NAME_FUNCTION( FUEL_SYS_TE62544LOG_B_OUT_2 );
FUEL_SYS_TE6232SEL_A_NAME = A_NAME_FUNCTION( FUEL_SYS_TGSSEL_A_NAME );
FUEL_SYS_TE62544LOG_ALM = ALM_FUNCTION( 0 , 0 , aout1 , iout1 , alm1 , sd1 , FUEL_SYS_TGSSEL_A_NAME , input , 275_0 , alm_1_sp , 300_0 , sd_1_sp , 1 , iin_1 , FALSE , enable , if (input > alm_1_sp && enable) , { alm1 = true; } , else , { alm1 = false; } , if (input > sd_1_sp && enable) , { sd1 = true; } , else , { sd1 = false; } );
FUEL_SYS_TE62544LOG_A_OUT_1 = A_OUT_1_FUNCTION( 0 , 0 , aout1 , iout1 , alm1 , sd1 , FUEL_SYS_TGSSEL_A_NAME , input , 275_0 , alm_1_sp , 300_0 , sd_1_sp , 1 , iin_1 , FALSE , enable , if (input > alm_1_sp && enable) , { alm1 = true; } , else , { alm1 = false; } , if (input > sd_1_sp && enable) , { sd1 = true; } , else , { sd1 = false; } );
FUEL_SYS_TE62544LOG_I_OUT_1 = I_OUT_1_FUNCTION( 0 , 0 , aout1 , iout1 , alm1 , sd1 , FUEL_SYS_TGSSEL_A_NAME , input , 275_0 , alm_1_sp , 300_0 , sd_1_sp , 1 , iin_1 , FALSE , enable , if (input > alm_1_sp && enable) , { alm1 = true; } , else , { alm1 = false; } , if (input > sd_1_sp && enable) , { sd1 = true; } , else , { sd1 = false; } );
FUEL_SYS_TE62544LOG_B_OUT_1 = B_OUT_1_FUNCTION( 0 , 0 , aout1 , iout1 , alm1 , sd1 , FUEL_SYS_TGSSEL_A_NAME , input , 275_0 , alm_1_sp , 300_0 , sd_1_sp , 1 , iin_1 , FALSE , enable , if (input > alm_1_sp && enable) , { alm1 = true; } , else , { alm1 = false; } , if (input > sd_1_sp && enable) , { sd1 = true; } , else , { sd1 = false; } );
FUEL_SYS_TE62544LOG_B_OUT_2 = B_OUT_2_FUNCTION( 0 , 0 , aout1 , iout1 , alm1 , sd1 , FUEL_SYS_TGSSEL_A_NAME , input , 275_0 , alm_1_sp , 300_0 , sd_1_sp , 1 , iin_1 , FALSE , enable , if (input > alm_1_sp && enable) , { alm1 = true; } , else , { alm1 = false; } , if (input > sd_1_sp && enable) , { sd1 = true; } , else , { sd1 = false; } );
FUEL_SYS_TGSSEL_A_NAME = A_NAME_FUNCTION( CORE_ANALOG_TGSSEL );
FUEL_SYS_TGS_GT_275_B_NAME = B_NAME_FUNCTION( FUEL_SYS_TE6232ALOG_B_OUT_1 );
FUEL_SYS_TGS_GT_300_B_NAME = B_NAME_FUNCTION( FUEL_SYS_TE6232ALOG_B_OUT_2 );
