I_DPS3DT_A_DERIV_SW_A_SW = A_SW_FUNCTION( I_DPS3DT_DPS3DTATMP_DERIV , I_DPS3DT_DPS3DTBTMP_DERIV , I_PS3_PS3AALM_B_NAME );
I_DPS3DT_B_DERIV_SW_A_SW = A_SW_FUNCTION( I_DPS3DT_DPS3DTATMP_DERIV , I_DPS3DT_DPS3DTBTMP_DERIV , I_PS3_PS3BALM_B_NAME );
I_DPS3DT_DDTDEFAULT_A_SW = A_SW_FUNCTION( I_DPS3DT_DDTDEFAULT_A_SW , I_DPS3DT_DPS3DTTMP_A_MIN , I_PS3_PS3LOSSSD_B_NAME );
I_DPS3DT_DPS3DTA_A_NAME = I_DPS3DT_DPS3DTATMP_DERIV;
LAG_FUNCTION(1 , 0 , IFACE_HDWR_PS3A,&I_DPS3DT_DPS3DTATMP_DERIV,&I_DPS3DT_DPS3DTATMP_LAG);
I_DPS3DT_DPS3DTB_A_NAME = I_DPS3DT_DPS3DTBTMP_DERIV;
LAG_FUNCTION(1 , 0 , IFACE_HDWR_PS3B,&I_DPS3DT_DPS3DTBTMP_DERIV,&I_DPS3DT_DPS3DTBTMP_LAG);
I_DPS3DT_DPS3DTSEL_A_NAME = I_DPS3DT_DDTDEFAULT_A_SW;
I_DPS3DT_DPS3DTTMP_A_MIN = A_MIN_FUNCTION( I_DPS3DT_A_DERIV_SW_A_SW , I_DPS3DT_B_DERIV_SW_A_SW );
