FUEL_SYS_N25GT4600_B_NAME = SPEED_SW_N25GT4600_A_COMPARE;
SFC_STEP_CLRINIT_OR = SPEED_SW_N25GT4600_A_COMPARE || SHUTDOWN_ANY_SD_B_NAME || SHUTDOWN_FOURHRLOK_B_NAME;
SFC_STEP_DO_WASH_B_NAME = OP_INTRFC_WW_ENABLE_B_NAME;
SFC_STEP_HCSEL_NOSD_AND = START_PERM_C_READY_B_NAME && SFC_STEP_HI_CNK_OR_OR;
SFC_STEP_HICNKACTIV_OR = SFC_STEP_HICRANK_1_SFC_STEP || SFC_STEP_HICRANK_2_SFC_STEP || SFC_STEP_HICRANK_3_SFC_STEP || SFC_STEP_HICRANK_4_SFC_STEP;
SFC_STEP_HI_CNK_OR_OR = SFC_STEP_HI_CRANK_B_NAME;
SFC_STEP_HI_CRANK_B_NAME = OP_INTRFC_HISPD_CRNK_B_NAME;
SFC_STEP_LCSEL_NOSD_AND = START_PERM_C_READY_B_NAME && SFC_STEP_LO_CNK_OR_OR;
SFC_STEP_LOSPD_OR_OR = SFC_STEP_LOCRANK_1_SFC_STEP || SFC_STEP_LOCRANK_2_SFC_STEP || SFC_STEP_LOCRANK_3_SFC_STEP || SFC_STEP_LOCRANK_4_SFC_STEP;
SFC_STEP_LO_CNK_OR_OR = SFC_STEP_LO_CRANK_B_NAME;
SFC_STEP_LO_CRANK_B_NAME = OP_INTRFC_LO_SPDCRNK_B_NAME;
SFC_STEP_NOTOFFLINE_NOT =! SFC_STEP_WW_ENBL_LATCH;
SFC_STEP_NOTSTARTIN_NOT =! SFC_STEP_START_INIT_B_NAME;
SFC_STEP_NSEL_NOSD_AND = START_PERM_T_READY_B_NAME && SFC_STEP_START_OR_OR;
if(SFC_STEP_LOCRANK_4_TRAN_2 || SFC_STEP_HICRANK_4_TRAN_2 || SFC_STEP_ESN_TRAN_1 || SFC_STEP_HOLD_OFF_TRAN_1) { 
	if( SFC_STEP_SD_COND_OR_OR) {
		SFC_STEP_OUTOFOP_TRAN_1 = SFC_STEP_SD_COND_OR_OR;
	} else if( SFC_STEP_WW_SEL_AND_AND) {
		SFC_STEP_OUTOFOP_TRAN_2 = SFC_STEP_WW_SEL_AND_AND;
	} else if( SFC_STEP_HCSEL_NOSD_AND) {
		SFC_STEP_OUTOFOP_TRAN_3 = SFC_STEP_HCSEL_NOSD_AND;
	} else if( SFC_STEP_LCSEL_NOSD_AND) {
		SFC_STEP_OUTOFOP_TRAN_4 = SFC_STEP_LCSEL_NOSD_AND;
	} else if( SFC_STEP_NSEL_NOSD_AND) {
		SFC_STEP_OUTOFOP_TRAN_5 = SFC_STEP_NSEL_NOSD_AND;
	} else 
		SFC_STEP_OUTOFOP_SFC_STEP= 1
} else {
  SFC_STEP_OUTOFOP_ACTIVETIME= 0; 
  SFC_STEP_OUTOFOP_SFC_STEP= 0; 
  SFC_STEP_OUTOFOP_TRAN_1= 0; 
  SFC_STEP_OUTOFOP_TRAN_2= 0; 
  SFC_STEP_OUTOFOP_TRAN_3= 0; 
  SFC_STEP_OUTOFOP_TRAN_4= 0; 
  SFC_STEP_OUTOFOP_TRAN_5 = 0; 
}
SFC_STEP_RUNNING_B_NAME = SFC_STEP_RUNNINGLP_ZMINUS1_B;
SFC_STEP_RUNNINGLP_ZMINUS1_B = SFC_STEP_RUN_OR_OR;
SFC_STEP_RUN_AND_AND = CORE_DIGITAL_FUELON && FUEL_SYS_N25GT4600_B_NAME;
SFC_STEP_RUN_OR_OR = SFC_STEP_STARTINITL_LATCH || SFC_STEP_RUN_AND_AND;
SFC_STEP_RUN_RELAY_B_NAME = SFC_STEP_RUN_AND_AND;
DELAY_FUNCTION(1 , 1.0 , 0 , SFC_STEP_SD_Z_ZMINUS1_B,&SFC_STEP_SDRESETDLY_DELAY,&SFC_STEP_SDRESETDLY_R_TIME);
SFC_STEP_SD_COND_OR_OR = FALSE || SHUTDOWN_ANY_SD_B_NAME || SHUTDOWN_SDN_CORE_B_NAME;
SFC_STEP_SD_Z_ZMINUS1_B = SHUTDOWN_ANY_SD_B_NAME;
if(SFC_STEP_OUTOFOP_TRAN_5) { 
	if( SFC_STEP_START_INIT_B_NAME) {
		SFC_STEP_SFC_S_INIT_TRAN_1 = SFC_STEP_START_INIT_B_NAME;
	} else 
		SFC_STEP_SFC_S_INIT_SFC_STEP= 1
} else {
  SFC_STEP_SFC_S_INIT_ACTIVETIME= 0; 
  SFC_STEP_SFC_S_INIT_SFC_STEP= 0; 
  SFC_STEP_SFC_S_INIT_TRAN_1 = 0; 
}
SFC_STEP_SP_SW_A_SW = A_SW_FUNCTION( SFC_STEP_LOSPD_OR_OR , 1700.0 , 1000.0 );
DELAY_FUNCTION(1 , TIMERS_SYS_TIMER_MULTIPLY , 0 , SFC_STEP_ST_CRNKLT_LATCH,&SFC_STEP_SRTFL_DLY_DELAY,&SFC_STEP_SRTFL_DLY_R_TIME);
SFC_STEP_SRTR_CRNK_OR = SFC_STEP_OUTOFOP_TRAN_2 || SFC_STEP_OUTOFOP_TRAN_3 || SFC_STEP_OUTOFOP_TRAN_4 || SFC_STEP_OUTOFOP_TRAN_5;
SFC_STEP_START_B_NAME = OP_INTRFC_START_B_NAME;
SFC_STEP_STARTINILP_ZMINUS1_B = SFC_STEP_STARTINITL_LATCH;
SFC_STEP_STARTINITL_LATCH = LATCH_FUNCTION(1,SFC_STEP_CLRINIT_OR,SFC_STEP_SFC_S_INIT_SFC_STEP,SFC_STEP_STARTINITL_LATCH);
SFC_STEP_START_INIT_B_NAME = SFC_STEP_STARTINILP_ZMINUS1_B;
SFC_STEP_START_OR_OR = SFC_STEP_START_B_NAME || SFC_STEP_START_SW_B_SW;
SFC_STEP_START_SW_B_SW = B_SW_FUNCTION( LOC_REM_LOCAL_NOT , FALSE , N3N41_BI_LOC_START_BI_L );
SFC_STEP_STRTFL_RST_OR = SFC_STEP_SDRESETDLY_DELAY || SFC_STEP_TMR_RESET_A_COMPARE;
SFC_STEP_STR_FAIL_B_NAME = SFC_STEP_SRTFL_DLY_DELAY;
SFC_STEP_ST_CRNKLT_LATCH = LATCH_FUNCTION(1,SFC_STEP_STRTFL_RST_OR,SFC_STEP_SRTR_CRNK_OR,SFC_STEP_ST_CRNKLT_LATCH);
A_COMPARE_FUNCTION(0 , CORE_ANALOG_N25SEL , SFC_STEP_SP_SW_A_SW,&SFC_STEP_TMR_RESET_A_COMPARE,&SFC_STEP_TMR_RESET_A_EQUAL);
SFC_STEP_WWSEL_NOSD_AND = START_PERM_WW_PERM_B_NAME && SFC_STEP_DO_WASH_B_NAME;
SFC_STEP_WW_DISABLE_OR = SFC_STEP_WW_ABORT_LATCH1 || WTR_WASH_SOAK_DONE_B_NAME;
SFC_STEP_WW_ENBL_LATCH = LATCH_FUNCTION(1,SFC_STEP_WW_DISABLE_OR,SFC_STEP_WWSEL_NOSD_AND,SFC_STEP_WW_ENBL_LATCH);
SFC_STEP_WW_SEL_AND_AND = SFC_STEP_WW_ENBL_LATCH && WTR_WASH_HS6505_SW_NC;
