S_BRNDMDG_BLBFLSW_A_SW = A_SW_FUNCTION( 11 , ADJ_BRNMUXMXJ_OUT_1 , S_BRNDMDG_BLDFAILOR_OR );
S_BRNDMDG_BLDFAILOR_OR = I_GP2I_GP2ILOSS_B_NAME || O_CDP_CDPVLVSD_B_NAME || O_ST8_ST8VLVSD_B_NAME;
S_BRNDMDG_BLDVLVFAIL_B_NAME = S_BRNDMDG_BLDFAILOR_OR;
S_BRNDMDG_BRNDMD_I_NAME = S_BRNDMDG_BRNDMTMP_OUT_1;
switch(S_BRNDMDG_INC_INT_OUT_1) { 
  case 1:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 0;
  break;
  case 2:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 1;
  break;
  case 3:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 10;
  break;
  case 4:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 11;
  break;
  case 5:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 12;
  break;
  case 6:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 13;
  break;
  case 7:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 14;
  break;
  case 8:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 15;
  break;
  case 9:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 2;
  break;
  case 10:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 3;
  break;
  case 11:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 4;
  break;
  case 12:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 5;
  break;
  case 13:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 6;
  break;
  case 14:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 7;
  break;
  case 15:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 8;
  break;
  case 16:
    S_BRNDMDG_BRNDMDMUX_A_MUX_N_1 = 9;
  break;
}
S_BRNDMDG_BRNDMDPV_I_NAME = S_BRNDMDG_BRNDMDPVTP_OUT_1;
S_BRNDMDG_BRNDMDPVTP_OUT_1 =(int)S_BRNDMDG_BRNDMPVTMP_ZMINUS1;
S_BRNDMDG_BRNDMDR_A_NAME = S_BRNDMDG_BRNDMDMUX_A_MUX_N_1;
S_BRNDMDG_BRNDMDRPV_A_NAME = S_BRNDMDG_BRNDMPVTMP_ZMINUS1;
S_BRNDMDG_BRNDMPVTMP_ZMINUS1 = S_BRNDMDG_BRNDMDMUX_A_MUX_N_1;
S_BRNDMDG_BRNDMTMP_OUT_1 =(int)S_BRNDMDG_BRNDMDMUX_A_MUX_N_1;
S_BRNDMDG_DMDINTGRAT_ADD = S_BRNDMDG_INC_FB_ZMINUS1 + S_BRNINC_BRNINC_A_NAME;
S_BRNDMDG_DMDLIMIT_A_LIMITER = A_LIMITER_FUNCTION( 1 , 1 , S_BRNDMDG_DMDINTGRAT_ADD , S_BRNDMDG_STEPDN_A_SW );
S_BRNDMDG_INC_FB_ZMINUS1 = S_BRNDMDG_DMDLIMIT_A_LIMITER;
S_BRNDMDG_INC_INT_OUT_1 =(int)S_BRNDMDG_DMDLIMIT_A_LIMITER;
S_BRNDMDG_MINBRNDMD_ADD = 1 + S_STEP2MIN_BRNSTP2MN_A_NAME;
S_BRNDMDG_OSP_STEPDN_OR = C_N2RATE_N2OVRSPD_B_NAME || Z_SHUTDOWN_SHUTDOWN_B_NAME;
S_BRNDMDG_STEPDN_A_SW = A_SW_FUNCTION( 1 , S_BRNDMDG_OSP_STEPDN_OR , S_BRNDMDG_STEPMINSW_A_SW );
S_BRNDMDG_STEPMINSW_A_SW = A_SW_FUNCTION( S_BRNDMDG_BLBFLSW_A_SW , S_BRNDMDG_MINBRNDMD_ADD , S_STEP2MIN_STEP2MIN_B_NAME );
