X_INRGFSDG_INRDMD_MAX_A_MAX = A_MAX_FUNCTION( 1 , X_INRGFSDG_INRGS_LAG_LAG_2 );
LAG_2_FUNCTION(1 , ADJ_INRFILTTCJ_A_NAME , S_STGVLVG_INRDMDGS_A_NAME,&X_INRGFSDG_INRGS_LAG_DERIV,&X_INRGFSDG_INRGS_LAG_LAG_2);
X_INRGFSDG_LHV_NOM_DIVIDE = 19000 / I_LHV_LHVSELGS_A_NAME;
X_INRGFSDG_WFINRVDCGS_A_NAME = X_INRGFSDG_WFINRVDTMP_DIVIDE;
X_INRGFSDG_WFINRVDTMP_DIVIDE = X_INRGFSDG_INRDMD_MAX_A_MAX / X_INRGFSDG_WFIREFGSTP_MULTIPLY;
X_INRGFSDG_WFIREFGS_A_NAME = X_INRGFSDG_WFIREFGSTP_MULTIPLY;
X_INRGFSDG_WFIREFGSTP_MULTIPLY = X_INRGFSDG_LHV_NOM_DIVIDE * X_INRGFSDG_WFITGTGSTP_MULTIPLY;
X_INRGFSDG_WFITGTGS_A_NAME = X_INRGFSDG_WFITGTGSTP_MULTIPLY;
X_INRGFSDG_WFITGTGSTP_MULTIPLY = F_TFRNGACG_WFIQCUPGAS_A_NAME * X_INRGFSDG_INRGS_LAG_LAG_2;
