X_OTRGFSDG_LHV_NOM_DIVIDE = 19000 / I_LHV_LHVSELGS_A_NAME;
X_OTRGFSDG_OTRDMD_MAX_A_MAX = A_MAX_FUNCTION( 1 , X_OTRGFSDG_OTRGS_LAG_LAG_2 );
LAG_2_FUNCTION(1 , ADJ_OTRFILTTCJ_A_NAME , S_STGVLVG_OTRDMDGS_A_NAME,&X_OTRGFSDG_OTRGS_LAG_DERIV,&X_OTRGFSDG_OTRGS_LAG_LAG_2);
X_OTRGFSDG_WFOREFGS_A_NAME = X_OTRGFSDG_WFOREFGSTP_MULTIPLY;
X_OTRGFSDG_WFOREFGSTP_MULTIPLY = X_OTRGFSDG_LHV_NOM_DIVIDE * X_OTRGFSDG_WFOTGTGSTP_MULTIPLY;
X_OTRGFSDG_WFOTGTGS_A_NAME = X_OTRGFSDG_WFOTGTGSTP_MULTIPLY;
X_OTRGFSDG_WFOTGTGSTP_MULTIPLY = F_TFRNGACG_WFOQCUPGAS_A_NAME * X_OTRGFSDG_OTRGS_LAG_LAG_2;
X_OTRGFSDG_WFOTRVDCGS_A_NAME = X_OTRGFSDG_WFOTRVDTMP_DIVIDE;
X_OTRGFSDG_WFOTRVDTMP_DIVIDE = X_OTRGFSDG_OTRDMD_MAX_A_MAX / X_OTRGFSDG_WFOREFGSTP_MULTIPLY;
