IGV_CAL_AVERAGE_CALCULATE =  (20.0 )  -  (  (IGV_CAL_AVG1_A_OUT_7 +IGV_CAL_AVG2_A_OUT_7 +IGV_CAL_AVG3_A_OUT_7 +IGV_CAL_AVG4_A_OUT_7 +IGV_CAL_AVG5_A_OUT_7 )  / 5 ) ;
if (IGV_CAL_MIN_AND== TRUE){   IGV_CAL_AVG1_A_OUT_6 = IGV_CAL_AVG1_A_OUT_5;   IGV_CAL_AVG1_A_OUT_5 = IGV_CAL_AVG1_A_OUT_4;   IGV_CAL_AVG1_A_OUT_4 = IGV_CAL_AVG1_A_OUT_3;   IGV_CAL_AVG1_A_OUT_3 = IGV_CAL_AVG1_A_OUT_2;   IGV_CAL_AVG1_A_OUT_2 = IGV_CAL_AVG1_A_OUT_1;   IGV_CAL_AVG1_A_OUT_1 = IGV_CAL_CURRENT_A_NAME;   IGV_CAL_AVG1_A_OUT_7 = (IGV_CAL_AVG1_A_OUT_1+IGV_CAL_AVG1_A_OUT_2+IGV_CAL_AVG1_A_OUT_3+   IGV_CAL_AVG1_A_OUT_4+IGV_CAL_AVG1_A_OUT_5+IGV_CAL_AVG1_A_OUT_6)/6;}   else {   IGV_CAL_AVG1_A_OUT_6 = IGV_CAL_AVG1_A_OUT_6;   IGV_CAL_AVG1_A_OUT_5 = IGV_CAL_AVG1_A_OUT_5;   IGV_CAL_AVG1_A_OUT_4 = IGV_CAL_AVG1_A_OUT_4;   IGV_CAL_AVG1_A_OUT_3 = IGV_CAL_AVG1_A_OUT_3;   IGV_CAL_AVG1_A_OUT_2 = IGV_CAL_AVG1_A_OUT_2;   IGV_CAL_AVG1_A_OUT_1 = IGV_CAL_AVG1_A_OUT_1;   IGV_CAL_AVG1_A_OUT_7 = IGV_CAL_AVG1_A_OUT_7;};
if (IGV_CAL_LO_MID_AND== TRUE){   IGV_CAL_AVG2_A_OUT_6 = IGV_CAL_AVG2_A_OUT_5;   IGV_CAL_AVG2_A_OUT_5 = IGV_CAL_AVG2_A_OUT_4;   IGV_CAL_AVG2_A_OUT_4 = IGV_CAL_AVG2_A_OUT_3;   IGV_CAL_AVG2_A_OUT_3 = IGV_CAL_AVG2_A_OUT_2;   IGV_CAL_AVG2_A_OUT_2 = IGV_CAL_AVG2_A_OUT_1;   IGV_CAL_AVG2_A_OUT_1 = IGV_CAL_CURRENT_A_NAME;   IGV_CAL_AVG2_A_OUT_7 = (IGV_CAL_AVG2_A_OUT_1+IGV_CAL_AVG2_A_OUT_2+IGV_CAL_AVG2_A_OUT_3+   IGV_CAL_AVG2_A_OUT_4+IGV_CAL_AVG2_A_OUT_5+IGV_CAL_AVG2_A_OUT_6)/6;}   else {   IGV_CAL_AVG2_A_OUT_6 = IGV_CAL_AVG2_A_OUT_6;   IGV_CAL_AVG2_A_OUT_5 = IGV_CAL_AVG2_A_OUT_5;   IGV_CAL_AVG2_A_OUT_4 = IGV_CAL_AVG2_A_OUT_4;   IGV_CAL_AVG2_A_OUT_3 = IGV_CAL_AVG2_A_OUT_3;   IGV_CAL_AVG2_A_OUT_2 = IGV_CAL_AVG2_A_OUT_2;   IGV_CAL_AVG2_A_OUT_1 = IGV_CAL_AVG2_A_OUT_1;   IGV_CAL_AVG2_A_OUT_7 = IGV_CAL_AVG2_A_OUT_7;};
if (IGV_CAL_MID_AND== TRUE){   IGV_CAL_AVG3_A_OUT_6 = IGV_CAL_AVG3_A_OUT_5;   IGV_CAL_AVG3_A_OUT_5 = IGV_CAL_AVG3_A_OUT_4;   IGV_CAL_AVG3_A_OUT_4 = IGV_CAL_AVG3_A_OUT_3;   IGV_CAL_AVG3_A_OUT_3 = IGV_CAL_AVG3_A_OUT_2;   IGV_CAL_AVG3_A_OUT_2 = IGV_CAL_AVG3_A_OUT_1;   IGV_CAL_AVG3_A_OUT_1 = IGV_CAL_CURRENT_A_NAME;   IGV_CAL_AVG3_A_OUT_7 = (IGV_CAL_AVG3_A_OUT_1+IGV_CAL_AVG3_A_OUT_2+IGV_CAL_AVG3_A_OUT_3+   IGV_CAL_AVG3_A_OUT_4+IGV_CAL_AVG3_A_OUT_5+IGV_CAL_AVG3_A_OUT_6)/6;}   else {   IGV_CAL_AVG3_A_OUT_6 = IGV_CAL_AVG3_A_OUT_6;   IGV_CAL_AVG3_A_OUT_5 = IGV_CAL_AVG3_A_OUT_5;   IGV_CAL_AVG3_A_OUT_4 = IGV_CAL_AVG3_A_OUT_4;   IGV_CAL_AVG3_A_OUT_3 = IGV_CAL_AVG3_A_OUT_3;   IGV_CAL_AVG3_A_OUT_2 = IGV_CAL_AVG3_A_OUT_2;   IGV_CAL_AVG3_A_OUT_1 = IGV_CAL_AVG3_A_OUT_1;   IGV_CAL_AVG3_A_OUT_7 = IGV_CAL_AVG3_A_OUT_7;};
if (IGV_CAL_HI_MID_AND== TRUE){   IGV_CAL_AVG4_A_OUT_6 = IGV_CAL_AVG4_A_OUT_5;   IGV_CAL_AVG4_A_OUT_5 = IGV_CAL_AVG4_A_OUT_4;   IGV_CAL_AVG4_A_OUT_4 = IGV_CAL_AVG4_A_OUT_3;   IGV_CAL_AVG4_A_OUT_3 = IGV_CAL_AVG4_A_OUT_2;   IGV_CAL_AVG4_A_OUT_2 = IGV_CAL_AVG4_A_OUT_1;   IGV_CAL_AVG4_A_OUT_1 = IGV_CAL_CURRENT_A_NAME;   IGV_CAL_AVG4_A_OUT_7 = (IGV_CAL_AVG4_A_OUT_1+IGV_CAL_AVG4_A_OUT_2+IGV_CAL_AVG4_A_OUT_3+   IGV_CAL_AVG4_A_OUT_4+IGV_CAL_AVG4_A_OUT_5+IGV_CAL_AVG4_A_OUT_6)/6;}   else {   IGV_CAL_AVG4_A_OUT_6 = IGV_CAL_AVG4_A_OUT_6;   IGV_CAL_AVG4_A_OUT_5 = IGV_CAL_AVG4_A_OUT_5;   IGV_CAL_AVG4_A_OUT_4 = IGV_CAL_AVG4_A_OUT_4;   IGV_CAL_AVG4_A_OUT_3 = IGV_CAL_AVG4_A_OUT_3;   IGV_CAL_AVG4_A_OUT_2 = IGV_CAL_AVG4_A_OUT_2;   IGV_CAL_AVG4_A_OUT_1 = IGV_CAL_AVG4_A_OUT_1;   IGV_CAL_AVG4_A_OUT_7 = IGV_CAL_AVG4_A_OUT_7;};
if (IGV_CAL_MAX_AND== TRUE){   IGV_CAL_AVG5_A_OUT_6 = IGV_CAL_AVG5_A_OUT_5;   IGV_CAL_AVG5_A_OUT_5 = IGV_CAL_AVG5_A_OUT_4;   IGV_CAL_AVG5_A_OUT_4 = IGV_CAL_AVG5_A_OUT_3;   IGV_CAL_AVG5_A_OUT_3 = IGV_CAL_AVG5_A_OUT_2;   IGV_CAL_AVG5_A_OUT_2 = IGV_CAL_AVG5_A_OUT_1;   IGV_CAL_AVG5_A_OUT_1 = IGV_CAL_CURRENT_A_NAME;   IGV_CAL_AVG5_A_OUT_7 = (IGV_CAL_AVG5_A_OUT_1+IGV_CAL_AVG5_A_OUT_2+IGV_CAL_AVG5_A_OUT_3+   IGV_CAL_AVG5_A_OUT_4+IGV_CAL_AVG5_A_OUT_5+IGV_CAL_AVG5_A_OUT_6)/6;}   else {   IGV_CAL_AVG5_A_OUT_6 = IGV_CAL_AVG5_A_OUT_6;   IGV_CAL_AVG5_A_OUT_5 = IGV_CAL_AVG5_A_OUT_5;   IGV_CAL_AVG5_A_OUT_4 = IGV_CAL_AVG5_A_OUT_4;   IGV_CAL_AVG5_A_OUT_3 = IGV_CAL_AVG5_A_OUT_3;   IGV_CAL_AVG5_A_OUT_2 = IGV_CAL_AVG5_A_OUT_2;   IGV_CAL_AVG5_A_OUT_1 = IGV_CAL_AVG5_A_OUT_1;   IGV_CAL_AVG5_A_OUT_7 = IGV_CAL_AVG5_A_OUT_7;};
IGV_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 1 , IGV_CAL_AVERAGE_CALCULATE );
if(IGV_CAL_CAL_09_TRAN_3 || IGV_CAL_CAL_00_TRAN_2) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_10_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_TRAN_1_DELAY) {
		IGV_CAL_CAL_10_TRAN_2 = IGV_CAL_DLY_TRAN_1_DELAY;
	} else 
		IGV_CAL_CAL_10_SFC_STEP= 1
} else {
  IGV_CAL_CAL_10_ACTIVETIME= 0; 
  IGV_CAL_CAL_10_SFC_STEP= 0; 
  IGV_CAL_CAL_10_TRAN_1= 0; 
  IGV_CAL_CAL_10_TRAN_2 = 0; 
}
if(IGV_CAL_CAL_10_TRAN_2) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_11_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_TRAN_2_DELAY) {
		IGV_CAL_CAL_11_TRAN_2 = IGV_CAL_DLY_TRAN_2_DELAY;
	} else 
		IGV_CAL_CAL_11_SFC_STEP= 1
} else {
  IGV_CAL_CAL_11_ACTIVETIME= 0; 
  IGV_CAL_CAL_11_SFC_STEP= 0; 
  IGV_CAL_CAL_11_TRAN_1= 0; 
  IGV_CAL_CAL_11_TRAN_2 = 0; 
}
if(IGV_CAL_CAL_11_TRAN_2) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_12_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_TRAN_3_DELAY) {
		IGV_CAL_CAL_12_TRAN_2 = IGV_CAL_DLY_TRAN_3_DELAY;
	} else 
		IGV_CAL_CAL_12_SFC_STEP= 1
} else {
  IGV_CAL_CAL_12_ACTIVETIME= 0; 
  IGV_CAL_CAL_12_SFC_STEP= 0; 
  IGV_CAL_CAL_12_TRAN_1= 0; 
  IGV_CAL_CAL_12_TRAN_2 = 0; 
}
if(IGV_CAL_CAL_12_TRAN_2) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_13_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_TRAN_4_DELAY) {
		IGV_CAL_CAL_13_TRAN_2 = IGV_CAL_DLY_TRAN_4_DELAY;
	} else 
		IGV_CAL_CAL_13_SFC_STEP= 1
} else {
  IGV_CAL_CAL_13_ACTIVETIME= 0; 
  IGV_CAL_CAL_13_SFC_STEP= 0; 
  IGV_CAL_CAL_13_TRAN_1= 0; 
  IGV_CAL_CAL_13_TRAN_2 = 0; 
}
if(IGV_CAL_CAL_13_TRAN_2) { 
	if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_14_TRAN_1 = IGV_CAL_PUNCH_OR_OR;
	} else if( IGV_CAL_DLY_TRAN_5_DELAY) {
		IGV_CAL_CAL_14_TRAN_2 = IGV_CAL_DLY_TRAN_5_DELAY;
	} else 
		IGV_CAL_CAL_14_SFC_STEP= 1
} else {
  IGV_CAL_CAL_14_ACTIVETIME= 0; 
  IGV_CAL_CAL_14_SFC_STEP= 0; 
  IGV_CAL_CAL_14_TRAN_1= 0; 
  IGV_CAL_CAL_14_TRAN_2 = 0; 
}
  bool IGV_CAL_CAL_14_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , IGV_CAL_CAL_15_SFC_STEP,&IGV_CAL_CAL_14_OS_ONE_SHOT,&IGV_CAL_CAL_14_OS_R_TIME,&IGV_CAL_CAL_14_OS_LAST_TRIGGER);
if(IGV_CAL_CAL_14_TRAN_2) { 
	if( IGV_CAL_CAL_14_OS_ONE_SHOT) {
		IGV_CAL_CAL_15_TRAN_1 = IGV_CAL_CAL_14_OS_ONE_SHOT;
	} else 
		IGV_CAL_CAL_15_SFC_STEP= 1
} else {
  IGV_CAL_CAL_15_ACTIVETIME= 0; 
  IGV_CAL_CAL_15_SFC_STEP= 0; 
  IGV_CAL_CAL_15_TRAN_1 = 0; 
}
if(IGV_CAL_CAL_00_TRAN_1) { 
	if( IGV_CAL_NOTSTROKE_NOT) {
		IGV_CAL_CAL_16_TRAN_1 = IGV_CAL_NOTSTROKE_NOT;
	} else if( IGV_CAL_PUNCH_OR_OR) {
		IGV_CAL_CAL_16_TRAN_2 = IGV_CAL_PUNCH_OR_OR;
	} else 
		IGV_CAL_CAL_16_SFC_STEP= 1
} else {
  IGV_CAL_CAL_16_ACTIVETIME= 0; 
  IGV_CAL_CAL_16_SFC_STEP= 0; 
  IGV_CAL_CAL_16_TRAN_1= 0; 
  IGV_CAL_CAL_16_TRAN_2 = 0; 
}
DELAY_FUNCTION(1 , 5 , 0 , IGV_CAL_DMDVSFDBK_B_OUT_1,&IGV_CAL_DLY_DFCMP_DELAY,&IGV_CAL_DLY_DFCMP_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , IGV_CAL_TRAN_1_AND,&IGV_CAL_DLY_TRAN_1_DELAY,&IGV_CAL_DLY_TRAN_1_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , IGV_CAL_TRAN_2_AND,&IGV_CAL_DLY_TRAN_2_DELAY,&IGV_CAL_DLY_TRAN_2_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , IGV_CAL_TRAN_3_AND,&IGV_CAL_DLY_TRAN_3_DELAY,&IGV_CAL_DLY_TRAN_3_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , IGV_CAL_TRAN_4_AND,&IGV_CAL_DLY_TRAN_4_DELAY,&IGV_CAL_DLY_TRAN_4_R_TIME);
DELAY_FUNCTION(1 , 15 , 0 , IGV_CAL_TRAN_5_AND,&IGV_CAL_DLY_TRAN_5_DELAY,&IGV_CAL_DLY_TRAN_5_R_TIME);
if (fabs(IGV_CAL_DEMAND_A_NAME-IGV_CAL_AVG_POS_A_NAME) < IGV_CAL_ERROR_A_NAME)   { IGV_CAL_DMDVSFDBK_B_OUT_1 = true; }   else   { IGV_CAL_DMDVSFDBK_B_OUT_1 = false; };
IGV_CAL_HI_MID_AND = IGV_CAL_CAL_13_SFC_STEP && IGV_CAL_I_CNT_ONE_DELAY && IGV_CAL_DLY_DFCMP_DELAY;
IGV_CAL_I_CNT_NOT =! IGV_CAL_I_CNT_ONE_DELAY;
IGV_CAL_I_CNTPV_ZMINUS1_B = IGV_CAL_I_CNT_NOT;
DELAY_FUNCTION(1 , 0.32 , 0 , IGV_CAL_I_CNTPV_ZMINUS1_B,&IGV_CAL_I_CNT_ONE_DELAY,&IGV_CAL_I_CNT_ONE_R_TIME);
IGV_CAL_LO_MID_AND = IGV_CAL_CAL_11_SFC_STEP && IGV_CAL_I_CNT_ONE_DELAY && IGV_CAL_DLY_DFCMP_DELAY;
IGV_CAL_MAX_AND = IGV_CAL_CAL_14_SFC_STEP && IGV_CAL_I_CNT_ONE_DELAY && IGV_CAL_DLY_DFCMP_DELAY;
IGV_CAL_MID_AND = IGV_CAL_CAL_12_SFC_STEP && IGV_CAL_I_CNT_ONE_DELAY && IGV_CAL_DLY_DFCMP_DELAY;
IGV_CAL_MIN_AND = IGV_CAL_CAL_10_SFC_STEP && IGV_CAL_I_CNT_ONE_DELAY && IGV_CAL_DLY_DFCMP_DELAY;
IGV_CAL_NOTSTROKE_NOT =! IGV_CAL_CALMODE_B_NAME;
IGV_CAL_NULJA_A_NAME = IGV_CAL_NULLBIAS_NO;
A_SW_REV_FUNCTION(IGV_CAL_CAL_14_OS_ONE_SHOT , IGV_CAL_NULLBIAS_NC , IGV_CAL_AVG_NEGATE_NEGATE,&IGV_CAL_NULLBIAS_NC,&IGV_CAL_NULLBIAS_NO);
IGV_CAL_TRAN_1_AND = IGV_CAL_DLY_DFCMP_DELAY && IGV_CAL_CAL_10_SFC_STEP;
IGV_CAL_TRAN_2_AND = IGV_CAL_DLY_DFCMP_DELAY && IGV_CAL_CAL_11_SFC_STEP;
IGV_CAL_TRAN_3_AND = IGV_CAL_DLY_DFCMP_DELAY && IGV_CAL_CAL_12_SFC_STEP;
IGV_CAL_TRAN_4_AND = IGV_CAL_DLY_DFCMP_DELAY && IGV_CAL_CAL_13_SFC_STEP;
IGV_CAL_TRAN_5_AND = IGV_CAL_DLY_DFCMP_DELAY && IGV_CAL_CAL_14_SFC_STEP;
