TBV_CAL_AVERAGE_CALCULATE = CALCULATE_FUNCTION( 0 , 0 , TBV_CAL_AVG1_A_OUT_7 , in1 , TBV_CAL_AVG2_A_OUT_7 , in2 , TBV_CAL_AVG3_A_OUT_7 , in3 , TBV_CAL_AVG4_A_OUT_7 , in4 , TBV_CAL_AVG5_A_OUT_7 , in5 , -20_0 , null , (null)-((in1+in2+in3+in4+in5)/5) );
TBV_CAL_AVG1_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , TBV_CAL_AVG1_A_OUT_1 , in1 , TBV_CAL_AVG1_A_OUT_2 , in2 , TBV_CAL_AVG1_A_OUT_3 , in3 , TBV_CAL_AVG1_A_OUT_4 , in4 , TBV_CAL_AVG1_A_OUT_5 , in5 , TBV_CAL_AVG1_A_OUT_6 , in6 , TBV_CAL_AVG1_A_OUT_7 , pvavg , TBV_CAL_CURRENT_A_NAME , xin , 1 , I_in , TBV_CAL_MIN_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
TBV_CAL_AVG2_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , TBV_CAL_AVG2_A_OUT_1 , in1 , TBV_CAL_AVG2_A_OUT_2 , in2 , TBV_CAL_AVG2_A_OUT_3 , in3 , TBV_CAL_AVG2_A_OUT_4 , in4 , TBV_CAL_AVG2_A_OUT_5 , in5 , TBV_CAL_AVG2_A_OUT_6 , in6 , TBV_CAL_AVG2_A_OUT_7 , pvavg , TBV_CAL_CURRENT_A_NAME , xin , 1 , I_in , TBV_CAL_LO_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
TBV_CAL_AVG3_CALC_PLUS = CALC_PLUS_FUNCTION( smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} , 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , TBV_CAL_AVG3_A_OUT_1 , in1 , TBV_CAL_AVG3_A_OUT_2 , in2 , TBV_CAL_AVG3_A_OUT_3 , in3 , TBV_CAL_AVG3_A_OUT_4 , in4 , TBV_CAL_AVG3_A_OUT_5 , in5 , TBV_CAL_AVG3_A_OUT_6 , in6 , TBV_CAL_AVG3_A_OUT_7 , pvavg , TBV_CAL_CURRENT_A_NAME , xin , 1 , I_in , TBV_CAL_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; );
TBV_CAL_AVG4_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , TBV_CAL_AVG4_A_OUT_1 , in1 , TBV_CAL_AVG4_A_OUT_2 , in2 , TBV_CAL_AVG4_A_OUT_3 , in3 , TBV_CAL_AVG4_A_OUT_4 , in4 , TBV_CAL_AVG4_A_OUT_5 , in5 , TBV_CAL_AVG4_A_OUT_6 , in6 , TBV_CAL_AVG4_A_OUT_7 , pvavg , TBV_CAL_CURRENT_A_NAME , xin , 1 , I_in , TBV_CAL_HI_MID_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; , smp1 = in1; , xavg = pvavg;} );
TBV_CAL_AVG5_CALC_PLUS = CALC_PLUS_FUNCTION( smp1 = in1; , xavg = pvavg;} , 0 , 0 , smp1 , smp2 , smp3 , smp4 , smp5 , smp6 , xavg , i_out , b_out , TBV_CAL_AVG5_A_OUT_1 , in1 , TBV_CAL_AVG5_A_OUT_2 , in2 , TBV_CAL_AVG5_A_OUT_3 , in3 , TBV_CAL_AVG5_A_OUT_4 , in4 , TBV_CAL_AVG5_A_OUT_5 , in5 , TBV_CAL_AVG5_A_OUT_6 , in6 , TBV_CAL_AVG5_A_OUT_7 , pvavg , TBV_CAL_CURRENT_A_NAME , xin , 1 , I_in , TBV_CAL_MAX_AND , trig , if (trig== TRUE){ , smp6 = in5; , smp5 = in4; , smp4 = in3; , smp3 = in2; , smp2 = in1; , smp1 = xin; , xavg = (smp1+smp2+smp3+ , smp4+smp5+smp6)/6;} , else { , smp6 = in6; , smp5 = in5; , smp4 = in4; , smp3 = in3; , smp2 = in2; );
TBV_CAL_AVG_NEGATE_NEGATE = NEGATE_FUNCTION( 0 , TBV_CAL_AVERAGE_CALCULATE );
TBV_CAL_CAL_10_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_09_TRAN_3 , TBV_CAL_CAL_00_TRAN_2 , TBV_CAL_PUNCH_OR_OR , TBV_CAL_DLY_TRAN_1_DELAY );
TBV_CAL_CAL_11_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_10_TRAN_2 , TBV_CAL_PUNCH_OR_OR , TBV_CAL_DLY_TRAN_2_DELAY );
TBV_CAL_CAL_12_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_11_TRAN_2 , TBV_CAL_PUNCH_OR_OR , TBV_CAL_DLY_TRAN_3_DELAY );
TBV_CAL_CAL_13_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_12_TRAN_2 , TBV_CAL_PUNCH_OR_OR , TBV_CAL_DLY_TRAN_4_DELAY );
TBV_CAL_CAL_14_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_13_TRAN_2 , TBV_CAL_PUNCH_OR_OR , TBV_CAL_DLY_TRAN_5_DELAY );
TBV_CAL_CAL_14_OS_ONE_SHOT = ONE_SHOT_FUNCTION( TBV_CAL_CAL_15_SFC_STEP , 1_0 , 0 , 0 );
TBV_CAL_CAL_15_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_14_TRAN_2 , TBV_CAL_CAL_14_OS_ONE_SHOT );
TBV_CAL_CAL_16_SFC_STEP = SFC_STEP_FUNCTION( 0 , 0 , TBV_CAL_CAL_00_TRAN_1 , TBV_CAL_NOTSTROKE_NOT , TBV_CAL_PUNCH_OR_OR );
TBV_CAL_DLY_DFCMP_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_DMDVSFDBK_B_OUT_1 , 0 , *5_0 (0_0, 20_0) );
TBV_CAL_DLY_TRAN_1_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_TRAN_1_AND , 0 , *15_0 (6_0, 50_0) );
TBV_CAL_DLY_TRAN_2_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_TRAN_2_AND , 0 , *15_0 (6_0, 50_0) );
TBV_CAL_DLY_TRAN_3_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_TRAN_3_AND , 0 , *15_0 (6_0, 50_0) );
TBV_CAL_DLY_TRAN_4_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_TRAN_4_AND , 0 , *15_0 (6_0, 50_0) );
TBV_CAL_DLY_TRAN_5_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_TRAN_5_AND , 0 , *15_0 (6_0, 50_0) );
TBV_CAL_DMDVSFDBK_CALC_PLUS = CALC_PLUS_FUNCTION( 0 , 0 , aout1 , iout1 , out , TBV_CAL_DEMAND_A_NAME , dmd , TBV_CAL_AVG_POS_A_NAME , fdbk , TBV_CAL_ERROR_A_NAME , err , 1 , iin_1 , TRUE , enable2 , if (fabs(dmd-fdbk) < err) , { out = true; } , else , { out = false; } );
TBV_CAL_HI_MID_AND = AND_FUNCTION( TBV_CAL_CAL_13_SFC_STEP , TBV_CAL_I_CNT_ONE_DELAY , TBV_CAL_DLY_DFCMP_DELAY );
TBV_CAL_I_CNT_NOT = NOT_FUNCTION( TBV_CAL_I_CNT_ONE_DELAY );
TBV_CAL_I_CNTPV_ZMINUS1_B = ZMINUS1_B_FUNCTION( TBV_CAL_I_CNT_NOT );
TBV_CAL_I_CNT_ONE_DELAY = DELAY_FUNCTION( 0 , TBV_CAL_I_CNTPV_ZMINUS1_B , 0_32 , 0 );
TBV_CAL_LO_MID_AND = AND_FUNCTION( TBV_CAL_CAL_11_SFC_STEP , TBV_CAL_I_CNT_ONE_DELAY , TBV_CAL_DLY_DFCMP_DELAY );
TBV_CAL_MAX_AND = AND_FUNCTION( TBV_CAL_CAL_14_SFC_STEP , TBV_CAL_I_CNT_ONE_DELAY , TBV_CAL_DLY_DFCMP_DELAY );
TBV_CAL_MID_AND = AND_FUNCTION( TBV_CAL_CAL_12_SFC_STEP , TBV_CAL_I_CNT_ONE_DELAY , TBV_CAL_DLY_DFCMP_DELAY );
TBV_CAL_MIN_AND = AND_FUNCTION( TBV_CAL_CAL_10_SFC_STEP , TBV_CAL_I_CNT_ONE_DELAY , TBV_CAL_DLY_DFCMP_DELAY );
TBV_CAL_NOTSTROKE_NOT = NOT_FUNCTION( TBV_CAL_CALMODE_B_NAME );
TBV_CAL_NULJA_A_NAME = A_NAME_FUNCTION( TBV_CAL_NULLBIAS_NO );
TBV_CAL_NULLBIAS_A_SW_REV = A_SW_REV_FUNCTION( TBV_CAL_CAL_14_OS_ONE_SHOT , TBV_CAL_NULLBIAS_NC , TBV_CAL_AVG_NEGATE_NEGATE );
TBV_CAL_TRAN_1_AND = AND_FUNCTION( TBV_CAL_DLY_DFCMP_DELAY , TBV_CAL_CAL_10_SFC_STEP );
TBV_CAL_TRAN_2_AND = AND_FUNCTION( TBV_CAL_DLY_DFCMP_DELAY , TBV_CAL_CAL_11_SFC_STEP );
TBV_CAL_TRAN_3_AND = AND_FUNCTION( TBV_CAL_DLY_DFCMP_DELAY , TBV_CAL_CAL_12_SFC_STEP );
TBV_CAL_TRAN_4_AND = AND_FUNCTION( TBV_CAL_DLY_DFCMP_DELAY , TBV_CAL_CAL_13_SFC_STEP );
TBV_CAL_TRAN_5_AND = AND_FUNCTION( TBV_CAL_DLY_DFCMP_DELAY , TBV_CAL_CAL_14_SFC_STEP );
