R_ISSL_FUELCHOP_A_SW = A_SW_FUNCTION( 0 , 101 , Z_SHUTDOWN_SHUTDOWN_B_NAME );
R_ISSL_FUELLIM_ZMINUS1 = R_ISSL_FUELCHOP_A_SW;
HSS_BUS_FUNCTION(1 , 0 , 100 , R_ISSL_LSS_1_LSS_BUS , R_NCDREG_NCDPRX_A_NAME,&R_ISSL_HSS_1_HI_LIM_I,&R_ISSL_HSS_1_HSS_BUS,&R_ISSL_HSS_1_LO_LIM_I,&R_ISSL_HSS_1_SEL_1,&R_ISSL_HSS_1_SEL_2);
HSS_BUS_FUNCTION(1 , 0 , 100 , R_ISSL_LSS_2_LSS_BUS , R_WF36MIN_WFLPRX_A_NAME,&R_ISSL_HSS_2_HI_LIM_I,&R_ISSL_HSS_2_HSS_BUS,&R_ISSL_HSS_2_LO_LIM_I,&R_ISSL_HSS_2_SEL_1,&R_ISSL_HSS_2_SEL_2);
LSS_BUS_FUNCTION(1 , 0 , 100 , R_N25REG_N25PRX_A_NAME , R_NSDREG_NSDPRX_A_NAME,&R_ISSL_LSS_1_HI_LIM_I,&R_ISSL_LSS_1_LO_LIM_I,&R_ISSL_LSS_1_LSS_BUS,&R_ISSL_LSS_1_SEL_1,&R_ISSL_LSS_1_SEL_2);
LSS_BUS_FUNCTION(1 , 0 , 100 , R_ISSL_HSS_1_HSS_BUS , R_NCAREG_NCAPRX_A_NAME,&R_ISSL_LSS_2_HI_LIM_I,&R_ISSL_LSS_2_LO_LIM_I,&R_ISSL_LSS_2_LSS_BUS,&R_ISSL_LSS_2_SEL_1,&R_ISSL_LSS_2_SEL_2);
LSS_BUS_FUNCTION(1 , 0 , 100 , R_ISSL_FUELLIM_ZMINUS1 , R_ISSL_HSS_2_HSS_BUS , R_N25HREG_N25HPRX_A_NAME , R_PS3REG_PS3PRX_A_NAME , R_T3HREG_T3HPRX_A_NAME , R_T48REG_T48PRX_A_NAME , R_WF36MAX_WFHPRX_A_NAME,&R_ISSL_LSS_3_HI_LIM_I,&R_ISSL_LSS_3_LO_LIM_I,&R_ISSL_LSS_3_LSS_BUS,&R_ISSL_LSS_3_SEL_1,&R_ISSL_LSS_3_SEL_2,&R_ISSL_LSS_3_SEL_3,&R_ISSL_LSS_3_SEL_4,&R_ISSL_LSS_3_SEL_5,&R_ISSL_LSS_3_SEL_6,&R_ISSL_LSS_3_SEL_7);
