O_SHUTDN_BOVOR_OR = C_N2RATE_LPSHFTFAIL_B_NAME || C_N2RATE_NSDOVSPD_B_NAME;
  bool O_SHUTDN_BOVOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(0 , 1 , 0.15 , O_SHUTDN_BOVOR_OR,&O_SHUTDN_BOVOS_ONE_SHOT,&O_SHUTDN_BOVOS_R_TIME,&O_SHUTDN_BOVOS_LAST_TRIGGER);
O_SHUTDN_C_BOV_B_NAME = O_SHUTDN_BOVOS_ONE_SHOT;
