ONLINE_WW_ANLTOTIME_A_TO_T = A_TO_T_FUNCTION( ONLINE_WW_I_TO_A_OUT_1 );
ONLINE_WW_ENBL_RESET_OR = ONLINE_WW_ONLINEOFF_OR || ONLINE_WW_ONLINE02_TRAN_2;
ONLINE_WW_I_TO_A_OUT_1 = (double)ONLINE_WW_WW_WASHTMR_R_TIME;
A_COMPARE_FUNCTION(-0.5 , CORE_ANALOG_MWEST , 1.5,&ONLINE_WW_MW_ENBWW_A_COMPARE,&ONLINE_WW_MW_ENBWW_A_EQUAL);
  bool ONLINE_WW_NOTPURGEOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , 0 , ONLINE_WW_NOT_PURGE_NOT,&ONLINE_WW_NOTPURGEOS_ONE_SHOT,&ONLINE_WW_NOTPURGEOS_R_TIME,&ONLINE_WW_NOTPURGEOS_LAST_TRIGGER);
ONLINE_WW_NOT_PERM_NOT =! ONLINE_WW_ONLNRUNPRM_AND;
ONLINE_WW_NOT_PURGE_NOT =! ONLINE_WW_PURGE_OS_ONE_SHOT;
ONLINE_WW_OFFLNWASH_B_NAME = ONLINE_WW_ONLINE01_SFC_STEP;
ONLINE_WW_OLWWACTVOR_OR = ONLINE_WW_ONLINE01_SFC_STEP || ONLINE_WW_ONLINE02_SFC_STEP;
ONLINE_WW_OLWW_ACT_B_NAME = ONLINE_WW_OLWWACTVOR_OR;
if(ONLINE_WW_ONLWW_OO_TRAN_1) { 
	if( ONLINE_WW_ONLINEOFF_OR) {
		ONLINE_WW_ONLINE01_TRAN_1 = ONLINE_WW_ONLINEOFF_OR;
	} else if( ONLINE_WW_WWDONE_B_NAME) {
		ONLINE_WW_ONLINE01_TRAN_2 = ONLINE_WW_WWDONE_B_NAME;
	} else 
		ONLINE_WW_ONLINE01_SFC_STEP= 1
} else {
  ONLINE_WW_ONLINE01_ACTIVETIME= 0; 
  ONLINE_WW_ONLINE01_SFC_STEP= 0; 
  ONLINE_WW_ONLINE01_TRAN_1= 0; 
  ONLINE_WW_ONLINE01_TRAN_2 = 0; 
}
if(ONLINE_WW_ONLINE01_TRAN_2) { 
	if( ONLINE_WW_ONLINEOFF_OR) {
		ONLINE_WW_ONLINE02_TRAN_1 = ONLINE_WW_ONLINEOFF_OR;
	} else if( ONLINE_WW_PURGE_DONE_B_NAME) {
		ONLINE_WW_ONLINE02_TRAN_2 = ONLINE_WW_PURGE_DONE_B_NAME;
	} else 
		ONLINE_WW_ONLINE02_SFC_STEP= 1
} else {
  ONLINE_WW_ONLINE02_ACTIVETIME= 0; 
  ONLINE_WW_ONLINE02_SFC_STEP= 0; 
  ONLINE_WW_ONLINE02_TRAN_1= 0; 
  ONLINE_WW_ONLINE02_TRAN_2 = 0; 
}
ONLINE_WW_ONLINEDONE_OR = ONLINE_WW_WW_WASHTMR_DELAY || WTR_WASH_LS6543NT_NOT;
ONLINE_WW_ONLINEMIN_A_NAME = ONLINE_WW_TIMER_MIN;
ONLINE_WW_ONLINEOFF_OR = SFC_STEP_OL_WW_OFF_B_NAME || WTR_WASH_HS6505_SW_NO || ONLINE_WW_NOT_PERM_NOT;
ONLINE_WW_ONLINEPRM_AND = WTR_WASH_LS6543_B_NAME && ONLINE_WW_ONLNRUNPRM_AND;
ONLINE_WW_ONLINESEC_A_NAME = ONLINE_WW_TIMER_SEC;
ONLINE_WW_ONLINE_EN_LATCH = LATCH_FUNCTION(1,ONLINE_WW_ENBL_RESET_OR,SFC_STEP_OL_WW_ON_B_NAME,ONLINE_WW_ONLINE_EN_LATCH);
ONLINE_WW_ONLNPRGE_B_NAME = ONLINE_WW_ONLINE02_SFC_STEP;
ONLINE_WW_ONLNRUNPRM_AND = SPEED_SW_NSDGT3590_A_COMPARE && ONLINE_WW_T2GT50CMP_A_COMPARE && SHUTDOWN_NO_SHTDNS_B_NAME && SPRINT_SPRT_OFF_NOT && ONLINE_WW_MW_ENBWW_A_COMPARE;
if(ONLINE_WW_ONLINE01_TRAN_1 || ONLINE_WW_ONLINE02_TRAN_1 || ONLINE_WW_ONLINE02_TRAN_2) { 
	if( ONLINE_WW_WW_MASK_AND) {
		ONLINE_WW_ONLWW_OO_TRAN_1 = ONLINE_WW_WW_MASK_AND;
	} else 
		ONLINE_WW_ONLWW_OO_SFC_STEP= 1
} else {
  ONLINE_WW_ONLWW_OO_ACTIVETIME= 0; 
  ONLINE_WW_ONLWW_OO_SFC_STEP= 0; 
  ONLINE_WW_ONLWW_OO_TRAN_1 = 0; 
}
ONLINE_WW_PRGCNVT_A_TO_T = A_TO_T_FUNCTION( ONLINE_WW_WSHPRGTMR_OUT_1 );
T_TO_HMS_FUNCTION(1 , ONLINE_WW_PRGCNVT_A_TO_T,&ONLINE_WW_PRGTOHMS_DAY,&ONLINE_WW_PRGTOHMS_HOUR,&ONLINE_WW_PRGTOHMS_MICROSEC,&ONLINE_WW_PRGTOHMS_MIN,&ONLINE_WW_PRGTOHMS_MONTH,&ONLINE_WW_PRGTOHMS_SEC,&ONLINE_WW_PRGTOHMS_YEAR);
ONLINE_WW_PR_TMR_MIN_A_NAME = ONLINE_WW_PRGTOHMS_MIN;
ONLINE_WW_PR_TMR_SEC_A_NAME = ONLINE_WW_PRGTOHMS_SEC;
ONLINE_WW_PURGE_DONE_B_NAME = ONLINE_WW_NOTPURGEOS_ONE_SHOT;
ONLINE_WW_PURGE_OR_OR = ONLINE_WW_ONLNPRGE_B_NAME || ONLINE_WW_ONLINE01_TRAN_1;
  bool ONLINE_WW_PURGE_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , WTR_WASH_PRG_TIMER_A_NAME , 0 , ONLINE_WW_PURGE_OR_OR,&ONLINE_WW_PURGE_OS_ONE_SHOT,&ONLINE_WW_PURGE_OS_R_TIME,&ONLINE_WW_PURGE_OS_LAST_TRIGGER);
ONLINE_WW_SOV6516_B_NAME = ONLINE_WW_SOV6516_OR_OR;
ONLINE_WW_SOV6516_OR_OR = ONLINE_WW_OFFLNWASH_B_NAME || WTR_WASH_PRG_NEGDLY_DELAY;
A_COMPARE_FUNCTION(0 , CORE_ANALOG_T2SEL , 50.0,&ONLINE_WW_T2GT50CMP_A_COMPARE,&ONLINE_WW_T2GT50CMP_A_EQUAL);
T_TO_HMS_FUNCTION(1 , ONLINE_WW_ANLTOTIME_A_TO_T,&ONLINE_WW_TIMER_DAY,&ONLINE_WW_TIMER_HOUR,&ONLINE_WW_TIMER_MICROSEC,&ONLINE_WW_TIMER_MIN,&ONLINE_WW_TIMER_MONTH,&ONLINE_WW_TIMER_SEC,&ONLINE_WW_TIMER_YEAR);
ONLINE_WW_WSHPRGTMR_OUT_1 = (double)ONLINE_WW_PURGE_OS_R_TIME;
ONLINE_WW_WWDONE_B_NAME = ONLINE_WW_ONLINEDONE_OR;
ONLINE_WW_WW_MASK_AND = WTR_WASH_HS6505_SW_NC && ONLINE_WW_ONLINE_EN_LATCH && ONLINE_WW_ONLINEPRM_AND;
DELAY_FUNCTION(1 , 900 , 0 , ONLINE_WW_OFFLNWASH_B_NAME,&ONLINE_WW_WW_WASHTMR_DELAY,&ONLINE_WW_WW_WASHTMR_R_TIME);
SFC_STEP_OL_WW_OFF_B_NAME = OP_INTRFC_OL_WW_OFF_B_NAME;
SFC_STEP_OL_WW_ON_B_NAME = OP_INTRFC_OL_WW_ON_B_NAME;
