SFC_STEP_COND_A_AND = SFC_STEP_T0_GT_20_A_COMPARE && SFC_STEP_T0_LT_50_NOT;
SFC_STEP_COND_B_B_NAME = SFC_STEP_T0_LT_20_NOT;
SFC_STEP_COND_C_B_NAME = SFC_STEP_T0_GT_50_A_COMPARE;
if(SFC_STEP_WWCRANK_11_TRAN_2) { 
	if( SFC_STEP_NOT_ABORT_NOT) {
		SFC_STEP_HOLD_OFF_TRAN_1 = SFC_STEP_NOT_ABORT_NOT;
	} else 
		SFC_STEP_HOLD_OFF_SFC_STEP= 1
} else {
  SFC_STEP_HOLD_OFF_ACTIVETIME= 0; 
  SFC_STEP_HOLD_OFF_SFC_STEP= 0; 
  SFC_STEP_HOLD_OFF_TRAN_1 = 0; 
}
SFC_STEP_NOT_ABORT_NOT =! SFC_STEP_WW_ABORT_LATCH1;
SFC_STEP_SOV6504_B_NAME = FALSE;
SFC_STEP_SOV6516_B_NAME = FALSE;
SFC_STEP_SOV6540_B_NAME = FALSE;
SFC_STEP_SOV6560_B_NAME = FALSE;
SFC_STEP_SOV6561_B_NAME = FALSE;
SFC_STEP_SOV6562_B_NAME = FALSE;
SFC_STEP_SOV6563_B_NAME = FALSE;
SFC_STEP_SOV6564_B_NAME = FALSE;
SFC_STEP_T0_A_NAME = VENT_AIRFILTAVG_TC_MON;
A_COMPARE_FUNCTION(0 , SFC_STEP_T0_A_NAME , 20.0,&SFC_STEP_T0_GT_20_A_COMPARE,&SFC_STEP_T0_GT_20_A_EQUAL);
A_COMPARE_FUNCTION(0 , SFC_STEP_T0_A_NAME , 50.0,&SFC_STEP_T0_GT_50_A_COMPARE,&SFC_STEP_T0_GT_50_A_EQUAL);
SFC_STEP_T0_LT_20_NOT =! SFC_STEP_T0_GT_20_A_COMPARE;
SFC_STEP_T0_LT_50_NOT =! SFC_STEP_T0_GT_50_A_COMPARE;
SFC_STEP_TE6559_H_B_NAME = FALSE;
SFC_STEP_WW_OK_OR = SFC_STEP_COND_A_AND || SFC_STEP_COND_C_B_NAME;
