GLUB_AUTO_SEL_AND = GLUB_SWAP_Z_ZMINUS1_B;
GLUB_AUXON_UNSC_B_NAME = GLUB_DLY_STDBY_DELAY;
GLUB_A_FLT_OR = GLUB_PSL6018AL_B_NAME || GLUB_PT6026ASD_B_NAME || GLUB_PSL6073AAL_B_NAME;
GLUB_A_OK_NOT =! GLUB_AC_A_FAIL_B_NAME;
GLUB_A_PRIMARY_B_NAME = GLUB_SEL_A_NOT;
GLUB_B_FLT_OR = GLUB_PSL6018AL_B_NAME || GLUB_PT6026ASD_B_NAME || GLUB_PSL6073BAL_B_NAME;
GLUB_B_OK_NOT =! GLUB_AC_B_FAIL_B_NAME;
GLUB_B_PRIMARY_B_NAME = GLUB_SEL_B_T_FLIPFLOP;
DELAY_FUNCTION(1 , 1 , 0 , GLUB_STDBY__AND,&GLUB_DLY_STDBY_DELAY,&GLUB_DLY_STDBY_R_TIME);
GLUB_FREQ_50_B_NAME = IFACE_CNFG_FREQ_50_HZ_B_NAME;
GLUB_FREQ_60_NOT =! GLUB_FREQ_50_B_NAME;
GLUB_HMI_ACSWAP_B_NAME = OP_INTRFC_PMP_SW_B_NAME;
if(GLUB_M6075B_SEL_TRAN_1 || GLUB_M6075B_SEL_TRAN_3 || GLUB_M6075B_SEL_TRAN_2) { 
	if( GLUB_SWAP_TO_B_OR) {
		GLUB_M6075A_SEL_TRAN_1 = GLUB_SWAP_TO_B_OR;
	} else if( GLUB_AC_2_4_SFC_STEP) {
		GLUB_M6075A_SEL_TRAN_2 = GLUB_AC_2_4_SFC_STEP;
	} else if( GLUB_SELB_OS_ONE_SHOT) {
		GLUB_M6075A_SEL_TRAN_3 = GLUB_SELB_OS_ONE_SHOT;
	} else 
		GLUB_M6075A_SEL_SFC_STEP= 1
} else {
  GLUB_M6075A_SEL_ACTIVETIME= 0; 
  GLUB_M6075A_SEL_SFC_STEP= 0; 
  GLUB_M6075A_SEL_TRAN_1= 0; 
  GLUB_M6075A_SEL_TRAN_2= 0; 
  GLUB_M6075A_SEL_TRAN_3 = 0; 
}
if(GLUB_M6075A_SEL_TRAN_1 || GLUB_M6075A_SEL_TRAN_3 || GLUB_M6075A_SEL_TRAN_2) { 
	if( GLUB_SWAP_TO_A_OR) {
		GLUB_M6075B_SEL_TRAN_1 = GLUB_SWAP_TO_A_OR;
	} else if( GLUB_AC_1_4_SFC_STEP) {
		GLUB_M6075B_SEL_TRAN_2 = GLUB_AC_1_4_SFC_STEP;
	} else if( GLUB_SELA_OS_ONE_SHOT) {
		GLUB_M6075B_SEL_TRAN_3 = GLUB_SELA_OS_ONE_SHOT;
	} else 
		GLUB_M6075B_SEL_SFC_STEP= 1
} else {
  GLUB_M6075B_SEL_ACTIVETIME= 0; 
  GLUB_M6075B_SEL_SFC_STEP= 0; 
  GLUB_M6075B_SEL_TRAN_1= 0; 
  GLUB_M6075B_SEL_TRAN_2= 0; 
  GLUB_M6075B_SEL_TRAN_3 = 0; 
}
GLUB_MSK_A_SWP_AND = GLUB_ACTIVE_LATCH1 && GLUB_NOT_STDBY_NOT && GLUB_A_FLT_OR && GLUB_B_OK_NOT;
GLUB_MSK_B_SWP_AND = GLUB_ACTIVE_LATCH1 && GLUB_B_OK_NOT && GLUB_B_FLT_OR && GLUB_A_OK_NOT;
GLUB_NOT_STDBY_NOT =! GLUB_DLY_STDBY_DELAY;
GLUB_RNDN_SWTCH_B_NAME = *FALSE;
GLUB_RNDN_XMTR_NOT =! GLUB_RNDN_SWTCH_B_NAME;
  bool GLUB_SELA_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , CORE_DIGITAL_PWR_UP , GLUB_SEL_A_NOT,&GLUB_SELA_OS_ONE_SHOT,&GLUB_SELA_OS_R_TIME,&GLUB_SELA_OS_LAST_TRIGGER);
  bool GLUB_SELA_OS2_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , CORE_DIGITAL_PWR_UP , GLUB_MSK_B_SWP_AND,&GLUB_SELA_OS2_ONE_SHOT,&GLUB_SELA_OS2_R_TIME,&GLUB_SELA_OS2_LAST_TRIGGER);
  bool GLUB_SELB_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , CORE_DIGITAL_PWR_UP , GLUB_SEL_B_T_FLIPFLOP,&GLUB_SELB_OS_ONE_SHOT,&GLUB_SELB_OS_R_TIME,&GLUB_SELB_OS_LAST_TRIGGER);
  bool GLUB_SELB_OS1_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.16 , CORE_DIGITAL_PWR_UP , GLUB_MSK_A_SWP_AND,&GLUB_SELB_OS1_ONE_SHOT,&GLUB_SELB_OS1_R_TIME,&GLUB_SELB_OS1_LAST_TRIGGER);
GLUB_SEL_A_NOT =! GLUB_SEL_B_T_FLIPFLOP;
  bool GLUB_SEL_B_IN_1_LAST; 
  bool GLUB_SEL_B_IN_2_LAST; 
T_FLIPFLOP_FUNCTION(1 , GLUB_HMI_ACSWAP_B_NAME , GLUB_AUTO_SEL_AND , CORE_DIGITAL_PWR_UP,&GLUB_SEL_B_T_FLIPFLOP,&GLUB_SEL_B_IN_1_LAST, &GLUB_SEL_B_IN_2_LAST); 
 GLUB_STANDBY_OR_OR = GLUB_STDBYAAND_AND || GLUB_STDBYBAND_AND;
GLUB_STDBYAAND_AND = GLUB_SEL_A_NOT && GLUB_M6075B_SEL_SFC_STEP;
GLUB_STDBYBAND_AND = GLUB_SEL_B_T_FLIPFLOP && GLUB_M6075A_SEL_SFC_STEP;
GLUB_STDBY__AND = GLUB_ACTIVE_LATCH1 && GLUB_STANDBY_OR_OR && GLUB_FREQ_50_B_NAME;
GLUB_SWAP_TO_A_OR = GLUB_SELA_OS_ONE_SHOT || GLUB_SELA_OS2_ONE_SHOT;
GLUB_SWAP_TO_B_OR = GLUB_SELB_OS_ONE_SHOT || GLUB_SELB_OS1_ONE_SHOT;
GLUB_SWAP_Z_ZMINUS1_B = GLUB_CLDNTMRDN_B_NAME;
