DATA_IO_AW_7_GO_OR_OR = DATA_IO_LCRAW_7_GO_B_SW || DATA_IO_MCRAW_7_GO_B_SW;
A_MUX_HSS_FUNCTION(1 , DATA_IO_AW_7_Z_ZMINUS1 , DATA_IO_LCRAW_7DMD_A_NAME , DATA_IO_MCRAW_7DMD_A_NAME , DATA_IO_LCRAW_7_GO_B_SW , DATA_IO_MCRAW_7_GO_B_SW,&DATA_IO_AW_7_SEL_A_MUX_HSS,&DATA_IO_AW_7_SEL_INT_SEL);
DATA_IO_AW_7_Z_ZMINUS1 = DATA_IO_AW_7_SEL_A_MUX_HSS;
DATA_IO_AW_V_6_A_NAME = DATA_IO_ROUNDOFF6_A_OUT_1;
DATA_IO_AW_V_7_A_NAME = DATA_IO_AW_7_SEL_A_MUX_HSS;
DATA_IO_A_TO_INT_6_OUT_1 =(int)DATA_IO_DIV_IN_6_DIVIDE;
DATA_IO_DIV_IN_6_DIVIDE = DATA_IO_AW_6_SEL_A_MUX_HSS / 10.0;
DATA_IO_INT_TO_A_6_OUT_1 = (double)DATA_IO_A_TO_INT_6_OUT_1;
// MODBUS_S 
DATA_IO_LCRAW_7DMD_A_NAME = DATA_IO_LL2_AW_V_7;
DATA_IO_LCRAW_7_GO_B_SW = B_SW_FUNCTION( N3N40_BI_LOC_REM_BI_L , DATA_IO_MAP_OR_BW1_OR , FALSE );
DATA_IO_LINKERR_OR_OR = DATA_IO_LCR_LNK_ERR_1 || DATA_IO_LL2_LNK_ERR_1 || FALSE;
// MODBUS_S 
DATA_IO_LOGRATE_A_OUT_1 = (double)CORE_ANALOG_LOG_RATE;
DATA_IO_MAP_OR_BW1_OR = DATA_IO_LL2_BW_V_114 || DATA_IO_LL2_BW_V_123 || DATA_IO_LL2_BW_V_115 || DATA_IO_LL2_BW_V_116 || DATA_IO_LL2_BW_V_117 || DATA_IO_LL2_BW_V_118 || DATA_IO_LL2_BW_V_119 || DATA_IO_LL2_BW_V_120 || DATA_IO_LL2_BW_V_121 || DATA_IO_LL2_BW_V_122;
DATA_IO_MAP_OR_BW2_OR = DATA_IO_RL2_BW_V_114 || DATA_IO_RL2_BW_V_123 || DATA_IO_RL2_BW_V_115 || DATA_IO_RL2_BW_V_116 || DATA_IO_RL2_BW_V_117 || DATA_IO_RL2_BW_V_118 || DATA_IO_RL2_BW_V_119 || DATA_IO_RL2_BW_V_120 || DATA_IO_RL2_BW_V_121 || DATA_IO_RL2_BW_V_122;
DATA_IO_MCRAW_7DMD_A_NAME = DATA_IO_RL2_AW_V_7;
DATA_IO_MCRAW_7_GO_B_SW = B_SW_FUNCTION( N3N40_BI_LOC_REM_BI_L , DATA_IO_MAP_OR_BW2_OR , FALSE );
DATA_IO_RATE_ADJ2_ZMINUS1 = DATA_IO_RL2_AW_V_7;
// MODBUS_S 
if ( ( DATA_IO_DIV_IN_6_DIVIDE - DATA_IO_INT_TO_A_6_OUT_1 ) > 0.5)   { DATA_IO_ROUNDOFF6_A_OUT_1 = ( DATA_IO_INT_TO_A_6_OUT_1 + 1) ; }   else   { DATA_IO_ROUNDOFF6_A_OUT_1 = DATA_IO_INT_TO_A_6_OUT_1; };
DATA_IO_SML_TM_Z2_ZMINUS1 = 3.0;
DATA_IO_TFLDMDHAZ2_ZMINUS1 = DATA_IO_RL2_AW_V_1;
DATA_IO_TFLISCHJA2_ZMINUS1 = DATA_IO_RL2_AW_V_5;
DATA_IO_TFLMAXJAZ2_ZMINUS1 = DATA_IO_RL2_AW_V_2;
DATA_IO_TFLMINJAZ2_ZMINUS1 = DATA_IO_RL2_AW_V_3;
DATA_IO_TFLOSCHJA2_ZMINUS1 = DATA_IO_RL2_AW_V_4;
MAPPING_RATE_ADJ1_ZMINUS1 = DATA_IO_LL2_AW_V_7;
MAPPING_SML_TM_Z1_ZMINUS1 = 3.0;
MAPPING_TFLDMDHAZ1_ZMINUS1 = DATA_IO_LL2_AW_V_1;
MAPPING_TFLISCHJA1_ZMINUS1 = DATA_IO_LL2_AW_V_5;
MAPPING_TFLMAXJAZ1_ZMINUS1 = DATA_IO_LL2_AW_V_2;
MAPPING_TFLMINJAZ1_ZMINUS1 = DATA_IO_LL2_AW_V_3;
MAPPING_TFLOSCHJA1_ZMINUS1 = DATA_IO_LL2_AW_V_4;
SIMMS_CO_A_NAME = 0;
SIMMS_NO_A_NAME = 0;
SIMMS_O2_A_NAME = 0;
SIMMS_UHC_A_NAME = 0;
