G_IGVSCH_IGVDMD_A_NAME = G_IGVSCH_IGVDMDLIM_A_LIMITER;
G_IGVSCH_IGVDMDADD_ADD = ADJ_IGVDMDJA_A_NAME + G_IGVSCH_PG_MD_SW_A_SW;
G_IGVSCH_IGVDMDLIM_A_LIMITER = A_LIMITER_FUNCTION( 1 , 28.57 , 98.4 , G_IGVSCH_IGVDMDADD_ADD );
G_IGVSCH_IGVSPRTSW_A_SW = A_SW_FUNCTION( G_IGVSCH_T_IGVPES_CURVES_3 , G_IGVSCH_T_IGVPG_CURVES_3 , Q_CLBCFG_SPRSWACTIV_B_NAME );
G_IGVSCH_PG_MD_SW_A_SW = A_SW_FUNCTION( G_IGVSCH_IGVSPRTSW_A_SW , G_IGVSCH_SWMW_3_EQ , G_IGVSCH_T_IGVMD_CURVES_3 );
I_COMPARE_FUNCTION(3 , ADJ_SWMWJ_I_NAME,&G_IGVSCH_SWMW_3_EQ,&G_IGVSCH_SWMW_3_GT,&G_IGVSCH_SWMW_3_LT);
CURVES_3_FUNCTION(1 , 0 , 5418-2587A_GE , C_INLETCAL_T2RTE_A_NAME , I_NSD_N2ROTOR_A_NAME , T_IGVMD,&G_IGVSCH_T_IGVMD_CURVES_3,&G_IGVSCH_T_IGVMD_REV_OUT);
CURVES_3_FUNCTION(1 , 0 , 5418-2587A_GE , C_INLETCAL_T2RTE_A_NAME , C_P3COR_PS3QA_A_NAME , T_IGVPES,&G_IGVSCH_T_IGVPES_CURVES_3,&G_IGVSCH_T_IGVPES_REV_OUT);
CURVES_3_FUNCTION(1 , 0 , 5418-2587A_GE , C_INLETCAL_T2RTE_A_NAME , C_P3COR_PS3QA_A_NAME , T_IGVPG,&G_IGVSCH_T_IGVPG_CURVES_3,&G_IGVSCH_T_IGVPG_REV_OUT);
