IFACE_COMM_DAT_FPORT_I_NAME = I_NAME_FUNCTION( 0 );
IFACE_COMM_DAT_TPORT_I_NAME = I_NAME_FUNCTION( 0 );
IFACE_COMM_GEDATALON_I_NAME = I_NAME_FUNCTION( 0 );
MODBUS_S_FUNCTION();
IFACE_COMM_TOD_T_NAME = T_NAME_FUNCTION( A1_A01_CPU_CLOCK_TOD );
