VENT_A_DUTYSEL_AND = VENT_MOT6413_B_NAME && VENT_GF_B_SEL_NOT && VENT_FAN_A_OK_NOT;
VENT_A_SEL_Z_ZMINUS1_B = VENT_A_DUTYSEL_AND;
VENT_BOTHGFAILZ_ZMINUS1_B = VENT_RUNBOTH_G_ZMINUS1_B;
VENT_BOTHGFLMSK_AND = VENT_BOTHGFAILZ_ZMINUS1_B && VENT_G_OFF_OPT_B_NAME;
VENT_B_DUTYSEL_AND = VENT_MOT6416_B_NAME && VENT_GF_A_SEL_T_FLIPFLOP && VENT_FAN_B_OK_NOT;
VENT_B_SEL_Z_ZMINUS1_B = VENT_B_DUTYSEL_AND;
VENT_FAN_A_OK_NOT =! VENT_AFAIL_G_LT_LATCH;
  bool VENT_FAN_A_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , VENT_A_SEL_Z_ZMINUS1_B,&VENT_FAN_A_OS_ONE_SHOT,&VENT_FAN_A_OS_R_TIME,&VENT_FAN_A_OS_LAST_TRIGGER);
VENT_FAN_B_OK_NOT =! VENT_BFAIL_G_LT_LATCH;
  bool VENT_FAN_B_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , VENT_B_SEL_Z_ZMINUS1_B,&VENT_FAN_B_OS_ONE_SHOT,&VENT_FAN_B_OS_R_TIME,&VENT_FAN_B_OS_LAST_TRIGGER);
DELAY_FUNCTION(1 , 5 , 0 , VENT_STRT_GFAN_OR,&VENT_GFANON_DLY_DELAY,&VENT_GFANON_DLY_R_TIME);
if(VENT_GFANS_RDY_TRAN_1 || VENT_MOT6413SFC_TRAN_1 || VENT_MOT6416SFC_TRAN_1 || VENT_MOT6413SFC_TRAN_3 || VENT_MOT6416SFC_TRAN_3 || VENT_MOT6413SFC_TRAN_4 || VENT_MOT6416SFC_TRAN_4) { 
	if( VENT_GFAN_RESET_OR) {
		VENT_GFANSOFF_TRAN_1 = VENT_GFAN_RESET_OR;
	} else 
		VENT_GFANSOFF_SFC_STEP= 1
} else {
  VENT_GFANSOFF_ACTIVETIME= 0; 
  VENT_GFANSOFF_SFC_STEP= 0; 
  VENT_GFANSOFF_TRAN_1 = 0; 
}
VENT_GFANS_OFF_OR = VENT_STTR_LT120_A_COMPARE || VENT_STARTLTAMB_A_COMPARE;
VENT_GFANS_ON_NOT =! VENT_GFANS_RDY_SFC_STEP;
if(VENT_GFANSOFF_TRAN_1) { 
	if( VENT_G_FAN_OFF_OR) {
		VENT_GFANS_RDY_TRAN_1 = VENT_G_FAN_OFF_OR;
	} else if( VENT_GFA_OR_OR) {
		VENT_GFANS_RDY_TRAN_2 = VENT_GFA_OR_OR;
	} else if( VENT_GFB_OR_OR) {
		VENT_GFANS_RDY_TRAN_3 = VENT_GFB_OR_OR;
	} else 
		VENT_GFANS_RDY_SFC_STEP= 1
} else {
  VENT_GFANS_RDY_ACTIVETIME= 0; 
  VENT_GFANS_RDY_SFC_STEP= 0; 
  VENT_GFANS_RDY_TRAN_1= 0; 
  VENT_GFANS_RDY_TRAN_2= 0; 
  VENT_GFANS_RDY_TRAN_3 = 0; 
}
VENT_GFAN_DN_LATCH = LATCH_FUNCTION(1,VENT_GFANS_RDY_SFC_STEP,VENT_GPSTVENTDN_B_NAME,VENT_GFAN_DN_LATCH);
VENT_GFAN_RESET_OR = VENT_RESET_B_NAME || VENT_PSTTMP_MSK_AND;
VENT_GFA_OR_OR = VENT_GOTOGFA_AND || VENT_TSTGF_A_AND;
  bool VENT_GFA_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , VENT_GF_A_SEL_T_FLIPFLOP,&VENT_GFA_OS_ONE_SHOT,&VENT_GFA_OS_R_TIME,&VENT_GFA_OS_LAST_TRIGGER);
VENT_GFB_OR_OR = VENT_GOTOGFB_AND || VENT_TSTGF_B_AND;
  bool VENT_GFB_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , VENT_GF_B_SEL_NOT,&VENT_GFB_OS_ONE_SHOT,&VENT_GFB_OS_R_TIME,&VENT_GFB_OS_LAST_TRIGGER);
VENT_GFXFRA_AND_AND = TRUE && VENT_FSL6409ALM_B_NAME;
VENT_GFXFRB_AND_AND = TRUE && VENT_FSL6410ALM_B_NAME;
  bool VENT_GF_A_SEL_IN_1_LAST; 
  bool VENT_GF_A_SEL_IN_2_LAST; 
T_FLIPFLOP_FUNCTION(1 , VENT_GF_SEL_OR_OR , *FALSE , 0,&VENT_GF_A_SEL_T_FLIPFLOP,&VENT_GF_A_SEL_IN_1_LAST, &VENT_GF_A_SEL_IN_2_LAST); 
 VENT_GF_B_SEL_NOT =! VENT_GF_A_SEL_T_FLIPFLOP;
VENT_GF_SELDCS_B_NAME = FALSE;
VENT_GF_SELHMI_B_NAME = OP_INTRFC_GFAN_SW_B_NAME;
VENT_GF_SEL_OR_OR = VENT_GF_SELHMI_B_NAME || VENT_GF_SELDCS_B_NAME || VENT_G_CHG_OS_ONE_SHOT || VENT_FAN_A_OS_ONE_SHOT || VENT_FAN_B_OS_ONE_SHOT;
VENT_GOTOGFA_AND = VENT_GF_A_SEL_T_FLIPFLOP && VENT_GFANON_DLY_DELAY;
VENT_GOTOGFB_AND = VENT_GFANON_DLY_DELAY && VENT_GF_B_SEL_NOT;
VENT_GTEST_DCS_B_NAME = *FALSE;
VENT_GTEST_HMI_B_NAME = OP_INTRFC_GFAN_TSTSW_B_NAME;
VENT_GTEST_OR_OR = VENT_GTEST_HMI_B_NAME || VENT_GTEST_DCS_B_NAME;
  bool VENT_G_CHG_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , VENT_PSTTMP_MSK_AND,&VENT_G_CHG_OS_ONE_SHOT,&VENT_G_CHG_OS_R_TIME,&VENT_G_CHG_OS_LAST_TRIGGER);
VENT_G_FAN_OFF_OR = VENT_STOPFANS_LATCH || VENT_BOTHGFLMSK_AND;
VENT_G_OFF_OPT_B_NAME = *FALSE;
if(VENT_GFANS_RDY_TRAN_2 || VENT_MOT6416SFC_TRAN_2 || VENT_MOT6416SFC_TRAN_5) { 
	if( VENT_G_FAN_OFF_OR) {
		VENT_MOT6413SFC_TRAN_1 = VENT_G_FAN_OFF_OR;
	} else if( VENT_GFXFRA_AND_AND) {
		VENT_MOT6413SFC_TRAN_2 = VENT_GFXFRA_AND_AND;
	} else if( VENT_PSTTMP_MSK_AND) {
		VENT_MOT6413SFC_TRAN_3 = VENT_PSTTMP_MSK_AND;
	} else if( VENT_TSTGFA_OS_ONE_SHOT) {
		VENT_MOT6413SFC_TRAN_4 = VENT_TSTGFA_OS_ONE_SHOT;
	} else if( VENT_GFB_OS_ONE_SHOT) {
		VENT_MOT6413SFC_TRAN_5 = VENT_GFB_OS_ONE_SHOT;
	} else 
		VENT_MOT6413SFC_SFC_STEP= 1
} else {
  VENT_MOT6413SFC_ACTIVETIME= 0; 
  VENT_MOT6413SFC_SFC_STEP= 0; 
  VENT_MOT6413SFC_TRAN_1= 0; 
  VENT_MOT6413SFC_TRAN_2= 0; 
  VENT_MOT6413SFC_TRAN_3= 0; 
  VENT_MOT6413SFC_TRAN_4= 0; 
  VENT_MOT6413SFC_TRAN_5 = 0; 
}
if(VENT_GFANS_RDY_TRAN_3 || VENT_MOT6413SFC_TRAN_2 || VENT_MOT6413SFC_TRAN_5) { 
	if( VENT_G_FAN_OFF_OR) {
		VENT_MOT6416SFC_TRAN_1 = VENT_G_FAN_OFF_OR;
	} else if( VENT_GFXFRB_AND_AND) {
		VENT_MOT6416SFC_TRAN_2 = VENT_GFXFRB_AND_AND;
	} else if( VENT_PSTTMP_MSK_AND) {
		VENT_MOT6416SFC_TRAN_3 = VENT_PSTTMP_MSK_AND;
	} else if( VENT_TSTGFB_OS_ONE_SHOT) {
		VENT_MOT6416SFC_TRAN_4 = VENT_TSTGFB_OS_ONE_SHOT;
	} else if( VENT_GFA_OS_ONE_SHOT) {
		VENT_MOT6416SFC_TRAN_5 = VENT_GFA_OS_ONE_SHOT;
	} else 
		VENT_MOT6416SFC_SFC_STEP= 1
} else {
  VENT_MOT6416SFC_ACTIVETIME= 0; 
  VENT_MOT6416SFC_SFC_STEP= 0; 
  VENT_MOT6416SFC_TRAN_1= 0; 
  VENT_MOT6416SFC_TRAN_2= 0; 
  VENT_MOT6416SFC_TRAN_3= 0; 
  VENT_MOT6416SFC_TRAN_4= 0; 
  VENT_MOT6416SFC_TRAN_5 = 0; 
}
VENT_NOTTESTGFA_NOT =! VENT_TSTGF_A_AND;
VENT_NOTTESTGFB_NOT =! VENT_TSTGF_B_AND;
VENT_NOT_GSTDBY_NOT =! VENT_DLY_STDBYG_DELAY;
VENT_PSTTMP_MSK_AND = VENT_GFANS_OFF_OR && VENT_NOTTESTTFA_NOT && VENT_NOTTESTTFB_NOT && VENT_GFAN_DN_LATCH;
VENT_RUN_RELAY_B_NAME = SFC_STEP_RUN_RELAY_B_NAME;
VENT_STRT_GFAN_OR = VENT_START_INI_B_NAME || VENT_RUN_RELAY_B_NAME || SFC_STEP_HISPD_OR_OR || SFC_STEP_LOSPD_OR_OR || VENT_GFAN_HITMP_OR;
  bool VENT_TSTGFA_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , VENT_NOTTESTGFA_NOT,&VENT_TSTGFA_OS_ONE_SHOT,&VENT_TSTGFA_OS_R_TIME,&VENT_TSTGFA_OS_LAST_TRIGGER);
  bool VENT_TSTGFB_OS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 1.0 , 0 , VENT_NOTTESTGFB_NOT,&VENT_TSTGFB_OS_ONE_SHOT,&VENT_TSTGFB_OS_R_TIME,&VENT_TSTGFB_OS_LAST_TRIGGER);
VENT_TSTGF_A_AND = VENT_MAINTMODE_B_NAME && VENT_GTEST_OR_OR && VENT_GF_A_SEL_T_FLIPFLOP;
VENT_TSTGF_B_AND = VENT_MAINTMODE_B_NAME && VENT_GTEST_OR_OR && VENT_GF_B_SEL_NOT;
