I_FLAMOUT_FLAMEOUT_B_NAME = I_FLAMOUT_FLAMLOSS_LATCH;
I_FLAMOUT_FLAMLOSS_LATCH = LATCH_FUNCTION(1,I_FLAMOUT_FLAMOPTSW2_B_SW,RESET_RESET_B_NAME,I_FLAMOUT_FLAMLOSS_LATCH);
I_FLAMOUT_FLAMOPTSW1_B_SW = B_SW_FUNCTION( I_FLAM_N25_FLMOUT_N25_B_NAME , I_FLAMOUT_FLAMOUTOR_OR , I_FLAMOUT_FLMOPT2_EQ );
I_FLAMOUT_FLAMOPTSW2_B_SW = B_SW_FUNCTION( I_FLAM_FLMOUT_OPT_B_NAME , I_FLAMOUT_FLAMOPTSW1_B_SW , I_FLAMOUT_FLMOPT0_EQ );
I_FLAMOUT_FLAMOUTOR_OR = I_FLAM_FLMOUT_OPT_B_NAME || I_FLAM_N25_FLMOUT_N25_B_NAME;
I_COMPARE_FUNCTION(0 , ADJ_FLMDTMODEJ_I_NAME,&I_FLAMOUT_FLMOPT0_EQ,&I_FLAMOUT_FLMOPT0_GT,&I_FLAMOUT_FLMOPT0_LT);
I_COMPARE_FUNCTION(2 , ADJ_FLMDTMODEJ_I_NAME,&I_FLAMOUT_FLMOPT2_EQ,&I_FLAMOUT_FLMOPT2_GT,&I_FLAMOUT_FLMOPT2_LT);
