IFACE_HDWR_MW_A_NAME = A_NAME_FUNCTION( IFACE_HDWR_MWSEL_A_SW );
IFACE_HDWR_MWFAILSW_B_SW = B_SW_FUNCTION( IFACE_HDWR_Z_BREAKER_DELAY , FALSE , A1_A06_AIO_WX_LATCH_OR );
IFACE_HDWR_MWSEL_A_SW = A_SW_FUNCTION( IFACE_HDWR_Z_BREAKER_DELAY , 0_0 , A1_A06_AIO_WX_AI_COMBO );
IFACE_HDWR_MWVST_B_NAME = B_NAME_FUNCTION( IFACE_HDWR_MWFAILSW_B_SW );
IFACE_HDWR_Z_BREAKER_DELAY = DELAY_FUNCTION( 0 , IFACE_CORE_Z_BREAKER_B_NAME , 0 , *0_0 (0_0, 10_0) );
