switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_97;
  break;
  case_3:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_97;
  break;
  case_4:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_97;
  break;
  case_6:
    OP_INTRFC_ABALOFF_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_ABAL_OFF_B_NAME = OP_INTRFC_ABALOFF_MX_B_MUX_N_1;
OP_INTRFC_ABAL_ON_B_NAME = OP_INTRFC_ACTABAL_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_96;
  break;
  case_3:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_96;
  break;
  case_4:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_96;
  break;
  case_6:
    OP_INTRFC_ACTABAL_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_106;
  break;
  case_3:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_106;
  break;
  case_4:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_106;
  break;
  case_6:
    OP_INTRFC_AUXSW_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_AUX_SW_B_NAME = OP_INTRFC_AUXSW_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_95;
  break;
  case_3:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_95;
  break;
  case_4:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_95;
  break;
  case_6:
    OP_INTRFC_CLRABAL_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_CLR_ABAL_B_NAME = OP_INTRFC_CLRABAL_MX_B_MUX_N_1;
OP_INTRFC_GFAN_SW_B_NAME = OP_INTRFC_GFNSWAP_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_105;
  break;
  case_3:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_105;
  break;
  case_4:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_105;
  break;
  case_6:
    OP_INTRFC_GFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_99;
  break;
  case_3:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_99;
  break;
  case_4:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_99;
  break;
  case_6:
    OP_INTRFC_LGRTDEC_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_100;
  break;
  case_3:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_100;
  break;
  case_4:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_100;
  break;
  case_6:
    OP_INTRFC_LGRTINC_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_LOGRATEDEC_B_NAME = OP_INTRFC_LGRTDEC_MX_B_MUX_N_1;
OP_INTRFC_LOGRATEINC_B_NAME = OP_INTRFC_LGRTINC_MX_B_MUX_N_1;
OP_INTRFC_MAINT_MODE_B_NAME = OP_INTRFC_MNTMODE_MX_B_MUX_N_1;
OP_INTRFC_MAP_MODE_B_NAME = OP_INTRFC_SELMAP_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_94;
  break;
  case_3:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_94;
  break;
  case_4:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_94;
  break;
  case_6:
    OP_INTRFC_MNTMODE_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_103;
  break;
  case_3:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_103;
  break;
  case_4:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_103;
  break;
  case_6:
    OP_INTRFC_PMPSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_PMP_SW_B_NAME = OP_INTRFC_PMPSWAP_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_98;
  break;
  case_3:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_98;
  break;
  case_4:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_98;
  break;
  case_6:
    OP_INTRFC_SELMAP_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = DATA_IO_LL2_BW_V_101;
  break;
  case_3:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = DATA_IO_RL2_BW_V_101;
  break;
  case_4:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = DATA_IO_DCS_BW_V_101;
  break;
  case_6:
    OP_INTRFC_SP101_MUX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_SP_SW_101_B_NAME = OP_INTRFC_SP101_MUX_B_MUX_N_1;
OP_INTRFC_TFAN_SW_B_NAME = OP_INTRFC_TFNSWAP_MX_B_MUX_N_1;
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = DATA_IO_LL2_BW_V_104;
  break;
  case_3:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = DATA_IO_RL2_BW_V_104;
  break;
  case_4:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = DATA_IO_DCS_BW_V_104;
  break;
  case_6:
    OP_INTRFC_TFNSWAP_MX_B_MUX_N_1 = *FALSE;
  break;
}
switch(CNTRL_MODE_SELECT_I_NAME) { 
  case_1:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = *FALSE;
  break;
  case_2:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = DATA_IO_LL2_BW_V_102;
  break;
  case_3:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = DATA_IO_RL2_BW_V_102;
  break;
  case_4:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = *FALSE;
  break;
  case_5:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = DATA_IO_DCS_BW_V_102;
  break;
  case_6:
    OP_INTRFC_WWDSBL_MUX_B_MUX_N_1 = *FALSE;
  break;
}
OP_INTRFC_WW_DSBL_SW_B_NAME = OP_INTRFC_WWDSBL_MUX_B_MUX_N_1;
