GLUB_ACTIVATE_OR = SFC_STEP_GLUB_SFC_STEP || SFC_STEP_LOCRANK_1_SFC_STEP || SFC_STEP_HICRANK_1_SFC_STEP || SFC_STEP_WWCRANK_1_SFC_STEP || GLUB_FSTRT_1SHT_ONE_SHOT;
GLUB_ACTIVATE50_AND = GLUB_ACTIVATEOS_ONE_SHOT && GLUB_FREQ_50_B_NAME;
GLUB_ACTIVATE60_AND = GLUB_FREQ_60_NOT && GLUB_ACTIVATEOS_ONE_SHOT;
  bool GLUB_ACTIVATEOS_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , GLUB_ACTIVATE_OR,&GLUB_ACTIVATEOS_ONE_SHOT,&GLUB_ACTIVATEOS_R_TIME,&GLUB_ACTIVATEOS_LAST_TRIGGER);
LATCH1_FUNCTION(0 , 1 , 0 , 0 , 0 , 0 , 0 , GLUB_ABORT_SFC_STEP , GLUB_AC_RDY_SFC_STEP , 0 , GLUB_CLDNTMRDN_B_NAME,&GLUB_ACTIVE_ALM_NO_1,&GLUB_ACTIVE_ALM_NO_2,&GLUB_ACTIVE_FIRST_ALM,&GLUB_ACTIVE_HORN,&GLUB_ACTIVE_LATCH1,&GLUB_ACTIVE_SEL_1,&GLUB_ACTIVE_SEL_2);
if(GLUB_GLUB_DC_TRAN_4) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_1_1_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_1_1_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_A_VERIF_OR_OR) {
		GLUB_AC_1_1_TRAN_3 = GLUB_A_VERIF_OR_OR;
	} else 
		GLUB_AC_1_1_SFC_STEP= 1
} else {
  GLUB_AC_1_1_ACTIVETIME= 0; 
  GLUB_AC_1_1_SFC_STEP= 0; 
  GLUB_AC_1_1_TRAN_1= 0; 
  GLUB_AC_1_1_TRAN_2= 0; 
  GLUB_AC_1_1_TRAN_3 = 0; 
}
if(GLUB_AC_1_1_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_1_2_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_1_2_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_N_6073A_NOT) {
		GLUB_AC_1_2_TRAN_3 = GLUB_N_6073A_NOT;
	} else 
		GLUB_AC_1_2_SFC_STEP= 1
} else {
  GLUB_AC_1_2_ACTIVETIME= 0; 
  GLUB_AC_1_2_SFC_STEP= 0; 
  GLUB_AC_1_2_TRAN_1= 0; 
  GLUB_AC_1_2_TRAN_2= 0; 
  GLUB_AC_1_2_TRAN_3 = 0; 
}
if(GLUB_AC_1_2_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_1_3_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_1_3_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_AC_B_FAIL_B_NAME) {
		GLUB_AC_1_3_TRAN_3 = GLUB_AC_B_FAIL_B_NAME;
	} else if( GLUB_ACB_VERLTC_LATCH_R) {
		GLUB_AC_1_3_TRAN_4 = GLUB_ACB_VERLTC_LATCH_R;
	} else 
		GLUB_AC_1_3_SFC_STEP= 1
} else {
  GLUB_AC_1_3_ACTIVETIME= 0; 
  GLUB_AC_1_3_SFC_STEP= 0; 
  GLUB_AC_1_3_TRAN_1= 0; 
  GLUB_AC_1_3_TRAN_2= 0; 
  GLUB_AC_1_3_TRAN_3= 0; 
  GLUB_AC_1_3_TRAN_4 = 0; 
}
if(GLUB_AC_1_3_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_1_4_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_1_4_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_ACAPRESSOK_B_NAME) {
		GLUB_AC_1_4_TRAN_3 = GLUB_ACAPRESSOK_B_NAME;
	} else 
		GLUB_AC_1_4_SFC_STEP= 1
} else {
  GLUB_AC_1_4_ACTIVETIME= 0; 
  GLUB_AC_1_4_SFC_STEP= 0; 
  GLUB_AC_1_4_TRAN_1= 0; 
  GLUB_AC_1_4_TRAN_2= 0; 
  GLUB_AC_1_4_TRAN_3 = 0; 
}
if(GLUB_GLUB_DC_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_2_1_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_2_1_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_B_VERIF_OR_OR) {
		GLUB_AC_2_1_TRAN_3 = GLUB_B_VERIF_OR_OR;
	} else 
		GLUB_AC_2_1_SFC_STEP= 1
} else {
  GLUB_AC_2_1_ACTIVETIME= 0; 
  GLUB_AC_2_1_SFC_STEP= 0; 
  GLUB_AC_2_1_TRAN_1= 0; 
  GLUB_AC_2_1_TRAN_2= 0; 
  GLUB_AC_2_1_TRAN_3 = 0; 
}
if(GLUB_AC_2_1_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_2_2_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_2_2_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_N_6073B_NOT) {
		GLUB_AC_2_2_TRAN_3 = GLUB_N_6073B_NOT;
	} else 
		GLUB_AC_2_2_SFC_STEP= 1
} else {
  GLUB_AC_2_2_ACTIVETIME= 0; 
  GLUB_AC_2_2_SFC_STEP= 0; 
  GLUB_AC_2_2_TRAN_1= 0; 
  GLUB_AC_2_2_TRAN_2= 0; 
  GLUB_AC_2_2_TRAN_3 = 0; 
}
if(GLUB_AC_2_2_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_2_3_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_2_3_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_AC_A_FAIL_B_NAME) {
		GLUB_AC_2_3_TRAN_3 = GLUB_AC_A_FAIL_B_NAME;
	} else if( GLUB_ACA_VERLTC_LATCH_R) {
		GLUB_AC_2_3_TRAN_4 = GLUB_ACA_VERLTC_LATCH_R;
	} else 
		GLUB_AC_2_3_SFC_STEP= 1
} else {
  GLUB_AC_2_3_ACTIVETIME= 0; 
  GLUB_AC_2_3_SFC_STEP= 0; 
  GLUB_AC_2_3_TRAN_1= 0; 
  GLUB_AC_2_3_TRAN_2= 0; 
  GLUB_AC_2_3_TRAN_3= 0; 
  GLUB_AC_2_3_TRAN_4 = 0; 
}
if(GLUB_AC_2_3_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_2_4_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_2_4_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_ACBPRESSOK_B_NAME) {
		GLUB_AC_2_4_TRAN_3 = GLUB_ACBPRESSOK_B_NAME;
	} else 
		GLUB_AC_2_4_SFC_STEP= 1
} else {
  GLUB_AC_2_4_ACTIVETIME= 0; 
  GLUB_AC_2_4_SFC_STEP= 0; 
  GLUB_AC_2_4_TRAN_1= 0; 
  GLUB_AC_2_4_TRAN_2= 0; 
  GLUB_AC_2_4_TRAN_3 = 0; 
}
if(GLUB_OUTOFOP_TRAN_2) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_AC_60_VER_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_AC_60_VER_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_AC60VERLTC_LATCH_R) {
		GLUB_AC_60_VER_TRAN_3 = GLUB_AC60VERLTC_LATCH_R;
	} else 
		GLUB_AC_60_VER_SFC_STEP= 1
} else {
  GLUB_AC_60_VER_ACTIVETIME= 0; 
  GLUB_AC_60_VER_SFC_STEP= 0; 
  GLUB_AC_60_VER_TRAN_1= 0; 
  GLUB_AC_60_VER_TRAN_2= 0; 
  GLUB_AC_60_VER_TRAN_3 = 0; 
}
if(GLUB_OUTOFOP_TRAN_1 || GLUB_OPERATE_OR || GLUB_ABORT_TRAN_1) { 
	if( GLUB_ACTIVE_LATCH1) {
		GLUB_AC_RDY_TRAN_1 = GLUB_ACTIVE_LATCH1;
	} else 
		GLUB_AC_RDY_SFC_STEP= 1
} else {
  GLUB_AC_RDY_ACTIVETIME= 0; 
  GLUB_AC_RDY_SFC_STEP= 0; 
  GLUB_AC_RDY_TRAN_1 = 0; 
}
GLUB_A_VERIF_OR_OR = GLUB_ACA_VERLTC_LATCH_R || GLUB_AC_A_FAIL_B_NAME;
GLUB_B_VERIF_OR_OR = GLUB_ACB_VERLTC_LATCH_R || GLUB_AC_B_FAIL_B_NAME;
GLUB_CLDN_NOTDN_NOT =! GLUB_CLDNTMRDN_B_NAME;
GLUB_FSTART_MSK_AND = TIMERS_DO_F_START_B_NAME && GLUB_TMR_STRT_AND;
  bool GLUB_FSTRT_1SHT_LAST_TRIGGER;
ONE_SHOT_FUNCTION(1 , 0.5 , 0 , GLUB_FSTART_MSK_AND,&GLUB_FSTRT_1SHT_ONE_SHOT,&GLUB_FSTRT_1SHT_R_TIME,&GLUB_FSTRT_1SHT_LAST_TRIGGER);
if(GLUB_OUTOFOP_TRAN_3) { 
	if( GLUB_SD_PSTDN_AND) {
		GLUB_GLUB_DC_TRAN_1 = GLUB_SD_PSTDN_AND;
	} else if( GLUB_SD_NPSTDN_AND) {
		GLUB_GLUB_DC_TRAN_2 = GLUB_SD_NPSTDN_AND;
	} else if( GLUB_OK_AND_A_AND) {
		GLUB_GLUB_DC_TRAN_3 = GLUB_OK_AND_A_AND;
	} else if( GLUB_OK_AND_B_AND) {
		GLUB_GLUB_DC_TRAN_4 = GLUB_OK_AND_B_AND;
	} else 
		GLUB_GLUB_DC_SFC_STEP= 1
} else {
  GLUB_GLUB_DC_ACTIVETIME= 0; 
  GLUB_GLUB_DC_SFC_STEP= 0; 
  GLUB_GLUB_DC_TRAN_1= 0; 
  GLUB_GLUB_DC_TRAN_2= 0; 
  GLUB_GLUB_DC_TRAN_3= 0; 
  GLUB_GLUB_DC_TRAN_4 = 0; 
}
GLUB_MSK_ACTIVE_AND = GLUB_NOT_ACTIVE_NOT && GLUB_ZERO_NOT_NOT;
GLUB_NOTOUTOFOP_NOT =! GLUB_OUTOFOP_SFC_STEP;
GLUB_NOT_ACTIVE_NOT =! GLUB_ACTIVE_LATCH1;
GLUB_OK_AND_A_AND = GLUB_DC_VERIFID_B_NAME && GLUB_M6075A_SEL_SFC_STEP;
GLUB_OK_AND_B_AND = GLUB_DC_VERIFID_B_NAME && GLUB_M6075B_SEL_SFC_STEP;
GLUB_OPERATE_OR = GLUB_AC_1_4_TRAN_3 || GLUB_AC_1_3_TRAN_4 || GLUB_AC_2_4_TRAN_3 || GLUB_AC_2_3_TRAN_4 || GLUB_AC_60_VER_TRAN_3;
if(GLUB_AC_RDY_TRAN_1) { 
	if( GLUB_MSK_ACTIVE_AND) {
		GLUB_OUTOFOP_TRAN_1 = GLUB_MSK_ACTIVE_AND;
	} else if( GLUB_ACTIVATE60_AND) {
		GLUB_OUTOFOP_TRAN_2 = GLUB_ACTIVATE60_AND;
	} else if( GLUB_ACTIVATE50_AND) {
		GLUB_OUTOFOP_TRAN_3 = GLUB_ACTIVATE50_AND;
	} else 
		GLUB_OUTOFOP_SFC_STEP= 1
} else {
  GLUB_OUTOFOP_ACTIVETIME= 0; 
  GLUB_OUTOFOP_SFC_STEP= 0; 
  GLUB_OUTOFOP_TRAN_1= 0; 
  GLUB_OUTOFOP_TRAN_2= 0; 
  GLUB_OUTOFOP_TRAN_3 = 0; 
}
GLUB_SD_NPSTDN_AND = SHUTDOWN_ANY_SD_B_NAME && GLUB_CLDN_NOTDN_NOT;
GLUB_SD_PSTDN_AND = SHUTDOWN_ANY_SD_B_NAME && GLUB_CLDNTMRDN_B_NAME;
GLUB_ZERO_B_NAME = SPEED_SW_ZERO_AND;
GLUB_ZERO_NOT_NOT =! GLUB_ZERO_B_NAME;
