SPRINT_ACT_OR_INI_NOR =! SPRINT_SPRT_READY_SFC_STEP || SPRINT_OFF_1_SFC_STEP || SPRINT_OFF_2_SFC_STEP || SPRINT_OFF_3_SFC_STEP || SPRINT_MASK_PURGE_AND || SPRINT_NOTREADY_SFC_STEP || SPRINT_LP_ON_1_SFC_STEP || SPRINT_LP_OFF_1_SFC_STEP || SPRINT_LP_OFF_3_SFC_STEP || SPRINT_LP_OFF_5_SFC_STEP || SPRINT_HP_ON_1_SFC_STEP || SPRINT_HP_OFF_1_SFC_STEP || SPRINT_HP_OFF_2_SFC_STEP;
SPRINT_ALLOWTEST_AND = SFC_STEP_OUTOFOP_SFC_STEP && SPRINT_TEST_SPRT_B_NAME;
SPRINT_NOTTEST_NOT =! SPRINT_ALLOWTEST_AND;
SPRINT_TEST_SPRT_B_NAME = *FALSE;
