M_DATAIO_M_TOT_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_M_TOT_LOAD;
M_DATAIO_RG10_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG10_LOAD;
M_DATAIO_RG160_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG160_LOAD;
M_DATAIO_RG20_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG20_LOAD;
M_DATAIO_RG40_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG40_LOAD;
M_DATAIO_RG5_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG5_LOAD;
M_DATAIO_RG80_LOAD_OUT_1 = (double)_MASTER__SYS_INFO_RG80_LOAD;
