W_WFTFDM_G_WFMID_A_NAME = W_WFTFDM_G_WFMIDTMP_CALCULATE;
W_WFTFDM_G_WFMIDTMP_CALCULATE =  ( (F_TFWFLIMG_WFMXG_A_NAME -F_TFWFLIMG_WFMNG_A_NAME ) *W_PRFSSTRM_WFMIDSCALE_A_NAME ) +    wfmng;
W_WFTFDM_G_WFMN_A_NAME = F_TFWFLIMG_WFMNG_A_NAME;
W_WFTFDM_G_WFMNPV_A_NAME = W_WFTFDM_G_WFMNZ_ZMINUS1;
W_WFTFDM_G_WFMNZ_ZMINUS1 = F_TFWFLIMG_WFMNG_A_NAME;
W_WFTFDM_G_WFMX_A_NAME = F_TFWFLIMG_WFMXG_A_NAME;
W_WFTFDM_G_WFMXPV_A_NAME = W_WFTFDM_G_WFMXZ_ZMINUS1;
W_WFTFDM_G_WFMXZ_ZMINUS1 = F_TFWFLIMG_WFMXG_A_NAME;
